In [1]:
Id=[]
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input/cassava-disease-classification/train'):
    for filename in filenames:
        Id.append(os.path.join(dirname, filename))
Id[:5]

['/kaggle/input/cassava-disease-classification/train/cmd/train-cmd-2149.jpg',
 '/kaggle/input/cassava-disease-classification/train/cmd/train-cmd-342.jpg',
 '/kaggle/input/cassava-disease-classification/train/cmd/train-cmd-2120.jpg',
 '/kaggle/input/cassava-disease-classification/train/cmd/train-cmd-1117.jpg',
 '/kaggle/input/cassava-disease-classification/train/cmd/train-cmd-629.jpg']

In [2]:
train=pd.DataFrame()
train=train.assign(filename=Id)
train.head()

                                            filename
0  /kaggle/input/cassava-disease-classification/t...
1  /kaggle/input/cassava-disease-classification/t...
2  /kaggle/input/cassava-disease-classification/t...
3  /kaggle/input/cassava-disease-classification/t...
4  /kaggle/input/cassava-disease-classification/t...

In [3]:
train['label']=train['filename']
train['label']=train['label'].str.replace('/kaggle/input/cassava-disease-classification/train/','')
train.head()

                                            filename                   label
0  /kaggle/input/cassava-disease-classification/t...  cmd/train-cmd-2149.jpg
1  /kaggle/input/cassava-disease-classification/t...   cmd/train-cmd-342.jpg
2  /kaggle/input/cassava-disease-classification/t...  cmd/train-cmd-2120.jpg
3  /kaggle/input/cassava-disease-classification/t...  cmd/train-cmd-1117.jpg
4  /kaggle/input/cassava-disease-classification/t...   cmd/train-cmd-629.jpg

In [4]:
train['label'] = train['label'].str.split('/').str[0]
train.head()

                                            filename label
0  /kaggle/input/cassava-disease-classification/t...   cmd
1  /kaggle/input/cassava-disease-classification/t...   cmd
2  /kaggle/input/cassava-disease-classification/t...   cmd
3  /kaggle/input/cassava-disease-classification/t...   cmd
4  /kaggle/input/cassava-disease-classification/t...   cmd

In [5]:
Id=[]
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input/cassava-disease-classification/test'):
    for filename in filenames:
        Id.append(os.path.join(dirname, filename))
Id[:5]

['/kaggle/input/cassava-disease-classification/test/cmd/train-cmd-199.jpg',
 '/kaggle/input/cassava-disease-classification/test/cmd/train-cmd-1078.jpg',
 '/kaggle/input/cassava-disease-classification/test/cmd/train-cmd-1323.jpg',
 '/kaggle/input/cassava-disease-classification/test/cmd/train-cmd-2387.jpg',
 '/kaggle/input/cassava-disease-classification/test/cmd/train-cmd-1401.jpg']

In [6]:
test=pd.DataFrame()
test=test.assign(filename=Id)
test.head()

                                            filename
0  /kaggle/input/cassava-disease-classification/t...
1  /kaggle/input/cassava-disease-classification/t...
2  /kaggle/input/cassava-disease-classification/t...
3  /kaggle/input/cassava-disease-classification/t...
4  /kaggle/input/cassava-disease-classification/t...

In [7]:
test['label']=test['filename']
test['label']=test['label'].str.replace('/kaggle/input/cassava-disease-classification/test/','')
test.head()

                                            filename                   label
0  /kaggle/input/cassava-disease-classification/t...   cmd/train-cmd-199.jpg
1  /kaggle/input/cassava-disease-classification/t...  cmd/train-cmd-1078.jpg
2  /kaggle/input/cassava-disease-classification/t...  cmd/train-cmd-1323.jpg
3  /kaggle/input/cassava-disease-classification/t...  cmd/train-cmd-2387.jpg
4  /kaggle/input/cassava-disease-classification/t...  cmd/train-cmd-1401.jpg

In [8]:
test['label'] = test['label'].str.split('/').str[0]
test.head()

                                            filename label
0  /kaggle/input/cassava-disease-classification/t...   cmd
1  /kaggle/input/cassava-disease-classification/t...   cmd
2  /kaggle/input/cassava-disease-classification/t...   cmd
3  /kaggle/input/cassava-disease-classification/t...   cmd
4  /kaggle/input/cassava-disease-classification/t...   cmd

In [9]:
import tensorflow as tf
import numpy as np 
from PIL import Image

model = tf.saved_model.load('/kaggle/input/efficientnet-cassava-leaf-classification/EfficientNet')
classes = [ "cbb" ,  "cbsd" ,  "cgm" ,  "cmd" ,  "healthy" , ]

/opt/conda/lib/python3.10/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.5
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"

In [10]:
result=[]
for i in test.filename:
    img = Image.open(i).convert('RGB')
    img = img.resize((300, 300 * img.size[1] // img.size[0]), Image.ANTIALIAS)
    inp_numpy = np.array(img)[None]
    inp = tf.constant(inp_numpy, dtype='float32')
    class_scores = model(inp)[0].numpy()
    result.append(classes[class_scores.argmax()])
result[:5]

/tmp/ipykernel_20/564266034.py:4: DeprecationWarning: ANTIALIAS is deprecated and will be removed in Pillow 10 (2023-07-01). Use LANCZOS or Resampling.LANCZOS instead.
  img = img.resize((300, 300 * img.size[1] // img.size[0]), Image.ANTIALIAS)

['cmd', 'cmd', 'cmd', 'cmd', 'cbsd']

In [11]:
test=test.assign(prediction=result)
test.head()

                                            filename label prediction
0  /kaggle/input/cassava-disease-classification/t...   cmd        cmd
1  /kaggle/input/cassava-disease-classification/t...   cmd        cmd
2  /kaggle/input/cassava-disease-classification/t...   cmd        cmd
3  /kaggle/input/cassava-disease-classification/t...   cmd        cmd
4  /kaggle/input/cassava-disease-classification/t...   cmd       cbsd

In [12]:
result=[]
for i in train.filename:
    img = Image.open(i).convert('RGB')
    img = img.resize((300, 300 * img.size[1] // img.size[0]), Image.ANTIALIAS)
    inp_numpy = np.array(img)[None]
    inp = tf.constant(inp_numpy, dtype='float32')
    class_scores = model(inp)[0].numpy()
    result.append(classes[class_scores.argmax()])
result[:5]

/tmp/ipykernel_20/1967585974.py:4: DeprecationWarning: ANTIALIAS is deprecated and will be removed in Pillow 10 (2023-07-01). Use LANCZOS or Resampling.LANCZOS instead.
  img = img.resize((300, 300 * img.size[1] // img.size[0]), Image.ANTIALIAS)

['cmd', 'cmd', 'cmd', 'cmd', 'cmd']

In [13]:
train=train.assign(prediction=result)
train.head()

                                            filename label prediction
0  /kaggle/input/cassava-disease-classification/t...   cmd        cmd
1  /kaggle/input/cassava-disease-classification/t...   cmd        cmd
2  /kaggle/input/cassava-disease-classification/t...   cmd        cmd
3  /kaggle/input/cassava-disease-classification/t...   cmd        cmd
4  /kaggle/input/cassava-disease-classification/t...   cmd        cmd

In [14]:
from sklearn.metrics import classification_report
print(classification_report(train['label'],train['prediction']))

              precision    recall  f1-score   support

         cbb       0.94      0.66      0.77       373
        cbsd       0.88      0.93      0.91      1154
         cgm       0.92      0.85      0.88       618
         cmd       0.93      0.97      0.95      2126
     healthy       0.81      0.87      0.84       253

    accuracy                           0.91      4524
   macro avg       0.90      0.86      0.87      4524
weighted avg       0.91      0.91      0.91      4524

In [15]:
print(classification_report(test['label'],test['prediction']))

              precision    recall  f1-score   support

         cbb       0.63      0.35      0.46        93
        cbsd       0.71      0.78      0.74       289
         cgm       0.72      0.67      0.69       155
         cmd       0.85      0.89      0.87       532
     healthy       0.62      0.59      0.60        63

    accuracy                           0.77      1132
   macro avg       0.71      0.66      0.67      1132
weighted avg       0.77      0.77      0.77      1132

In [16]:
Id=[]
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input/cassava-disease-classification/soltest'):
    for filename in filenames:
        Id.append(os.path.join(dirname, filename))
Id[:5]

['/kaggle/input/cassava-disease-classification/soltest/extra-image-9351.jpg',
 '/kaggle/input/cassava-disease-classification/soltest/extra-image-430.jpg',
 '/kaggle/input/cassava-disease-classification/soltest/extra-image-14967.jpg',
 '/kaggle/input/cassava-disease-classification/soltest/extra-image-14936.jpg',
 '/kaggle/input/cassava-disease-classification/soltest/extra-image-4047.jpg']

In [17]:
soltest=pd.DataFrame()
soltest=soltest.assign(filename=Id)
soltest.head()

                                            filename
0  /kaggle/input/cassava-disease-classification/s...
1  /kaggle/input/cassava-disease-classification/s...
2  /kaggle/input/cassava-disease-classification/s...
3  /kaggle/input/cassava-disease-classification/s...
4  /kaggle/input/cassava-disease-classification/s...

In [18]:
result=[]
for i in soltest.filename:
    img = Image.open(i).convert('RGB')
    img = img.resize((300, 300 * img.size[1] // img.size[0]), Image.ANTIALIAS)
    inp_numpy = np.array(img)[None]
    inp = tf.constant(inp_numpy, dtype='float32')
    class_scores = model(inp)[0].numpy()
    result.append(classes[class_scores.argmax()])
result[:5]

/tmp/ipykernel_20/1898233824.py:4: DeprecationWarning: ANTIALIAS is deprecated and will be removed in Pillow 10 (2023-07-01). Use LANCZOS or Resampling.LANCZOS instead.
  img = img.resize((300, 300 * img.size[1] // img.size[0]), Image.ANTIALIAS)

['cmd', 'healthy', 'cmd', 'cgm', 'cbsd']

In [19]:
soltest=soltest.assign(prediction=result)
soltest.head()

                                            filename prediction
0  /kaggle/input/cassava-disease-classification/s...        cmd
1  /kaggle/input/cassava-disease-classification/s...    healthy
2  /kaggle/input/cassava-disease-classification/s...        cmd
3  /kaggle/input/cassava-disease-classification/s...        cgm
4  /kaggle/input/cassava-disease-classification/s...       cbsd

In [20]:
sol=pd.read_csv('/kaggle/input/cassava-disease-classification/submission.csv')
sol.head()

               Id
0  test-img-0.jpg
1  test-img-1.jpg
2  test-img-2.jpg
3  test-img-3.jpg
4  test-img-4.jpg

In [21]:
sol['filename']='/kaggle/input/cassava-disease-classification/sol/'+sol['Id']
sol.head()

               Id                                           filename
0  test-img-0.jpg  /kaggle/input/cassava-disease-classification/s...
1  test-img-1.jpg  /kaggle/input/cassava-disease-classification/s...
2  test-img-2.jpg  /kaggle/input/cassava-disease-classification/s...
3  test-img-3.jpg  /kaggle/input/cassava-disease-classification/s...
4  test-img-4.jpg  /kaggle/input/cassava-disease-classification/s...

In [22]:
result=[]
for i in sol.filename:
    img = Image.open(i).convert('RGB')
    img = img.resize((300, 300 * img.size[1] // img.size[0]), Image.ANTIALIAS)
    inp_numpy = np.array(img)[None]
    inp = tf.constant(inp_numpy, dtype='float32')
    class_scores = model(inp)[0].numpy()
    result.append(classes[class_scores.argmax()])
result[:5]

/tmp/ipykernel_20/3826586461.py:4: DeprecationWarning: ANTIALIAS is deprecated and will be removed in Pillow 10 (2023-07-01). Use LANCZOS or Resampling.LANCZOS instead.
  img = img.resize((300, 300 * img.size[1] // img.size[0]), Image.ANTIALIAS)

['cbsd', 'cbsd', 'cmd', 'cmd', 'cmd']

In [23]:
sol=sol.assign(Category=result)
sol=sol.drop(['filename'],axis=1)
sol.head()

               Id Category
0  test-img-0.jpg     cbsd
1  test-img-1.jpg     cbsd
2  test-img-2.jpg      cmd
3  test-img-3.jpg      cmd
4  test-img-4.jpg      cmd

In [24]:
sol=sol.loc[:,['Category','Id']]
sol.head()

  Category              Id
0     cbsd  test-img-0.jpg
1     cbsd  test-img-1.jpg
2      cmd  test-img-2.jpg
3      cmd  test-img-3.jpg
4      cmd  test-img-4.jpg

In [25]:
sol.to_csv('./EfficientNet.csv',index=False)