In [1]:
Id=[]
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input/cassava-disease-classification/train'):
    for filename in filenames:
        Id.append(os.path.join(dirname, filename))
Id[:5]

['/kaggle/input/cassava-disease-classification/train/cmd/train-cmd-2149.jpg',
 '/kaggle/input/cassava-disease-classification/train/cmd/train-cmd-342.jpg',
 '/kaggle/input/cassava-disease-classification/train/cmd/train-cmd-2120.jpg',
 '/kaggle/input/cassava-disease-classification/train/cmd/train-cmd-1117.jpg',
 '/kaggle/input/cassava-disease-classification/train/cmd/train-cmd-629.jpg']

In [2]:
sol_train=pd.DataFrame()
sol_train=sol_train.assign(filename=Id)
sol_train.head()

                                            filename
0  /kaggle/input/cassava-disease-classification/t...
1  /kaggle/input/cassava-disease-classification/t...
2  /kaggle/input/cassava-disease-classification/t...
3  /kaggle/input/cassava-disease-classification/t...
4  /kaggle/input/cassava-disease-classification/t...

In [3]:
sol_train['label']=sol_train['filename']
sol_train['label']=sol_train['label'].str.replace('/kaggle/input/cassava-disease-classification/train/','')
sol_train.head()

                                            filename                   label
0  /kaggle/input/cassava-disease-classification/t...  cmd/train-cmd-2149.jpg
1  /kaggle/input/cassava-disease-classification/t...   cmd/train-cmd-342.jpg
2  /kaggle/input/cassava-disease-classification/t...  cmd/train-cmd-2120.jpg
3  /kaggle/input/cassava-disease-classification/t...  cmd/train-cmd-1117.jpg
4  /kaggle/input/cassava-disease-classification/t...   cmd/train-cmd-629.jpg

In [4]:
sol_train['label'] = sol_train['label'].str.split('/').str[0]
sol_train.head()

                                            filename label
0  /kaggle/input/cassava-disease-classification/t...   cmd
1  /kaggle/input/cassava-disease-classification/t...   cmd
2  /kaggle/input/cassava-disease-classification/t...   cmd
3  /kaggle/input/cassava-disease-classification/t...   cmd
4  /kaggle/input/cassava-disease-classification/t...   cmd

In [5]:
Id=[]
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input/cassava-disease-classification/test'):
    for filename in filenames:
        Id.append(os.path.join(dirname, filename))
Id[:5]

['/kaggle/input/cassava-disease-classification/test/cmd/train-cmd-199.jpg',
 '/kaggle/input/cassava-disease-classification/test/cmd/train-cmd-1078.jpg',
 '/kaggle/input/cassava-disease-classification/test/cmd/train-cmd-1323.jpg',
 '/kaggle/input/cassava-disease-classification/test/cmd/train-cmd-2387.jpg',
 '/kaggle/input/cassava-disease-classification/test/cmd/train-cmd-1401.jpg']

In [6]:
sol_test=pd.DataFrame()
sol_test=sol_test.assign(filename=Id)
sol_test.head()

                                            filename
0  /kaggle/input/cassava-disease-classification/t...
1  /kaggle/input/cassava-disease-classification/t...
2  /kaggle/input/cassava-disease-classification/t...
3  /kaggle/input/cassava-disease-classification/t...
4  /kaggle/input/cassava-disease-classification/t...

In [7]:
sol_test['label']=sol_test['filename']
sol_test['label']=sol_test['label'].str.replace('/kaggle/input/cassava-disease-classification/test/','')
sol_test.head()

                                            filename                   label
0  /kaggle/input/cassava-disease-classification/t...   cmd/train-cmd-199.jpg
1  /kaggle/input/cassava-disease-classification/t...  cmd/train-cmd-1078.jpg
2  /kaggle/input/cassava-disease-classification/t...  cmd/train-cmd-1323.jpg
3  /kaggle/input/cassava-disease-classification/t...  cmd/train-cmd-2387.jpg
4  /kaggle/input/cassava-disease-classification/t...  cmd/train-cmd-1401.jpg

In [8]:
sol_test['label'] = sol_test['label'].str.split('/').str[0]
sol_test.head()

                                            filename label
0  /kaggle/input/cassava-disease-classification/t...   cmd
1  /kaggle/input/cassava-disease-classification/t...   cmd
2  /kaggle/input/cassava-disease-classification/t...   cmd
3  /kaggle/input/cassava-disease-classification/t...   cmd
4  /kaggle/input/cassava-disease-classification/t...   cmd

In [9]:
import tensorflow as tf
import numpy as np 
from PIL import Image

model = tf.saved_model.load('/kaggle/input/efficientnet-cassava-disease-classification/EfficientNet')
classes = [ "Cassava Bacterial Blight (CBB)" ,  "Cassava Brown Streak Disease (CBSD)" ,  
           "Cassava Green Mottle (CGM)" ,  "Cassava Mosaic Disease (CMD)" ,  "Healthy" , ]

/opt/conda/lib/python3.10/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.5
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"

In [10]:
result=[]
for i in sol_test.filename:
    img = Image.open(i).convert('RGB')
    img = img.resize((300, 300 * img.size[1] // img.size[0]), Image.ANTIALIAS)
    inp_numpy = np.array(img)[None]
    inp = tf.constant(inp_numpy, dtype='float32')
    class_scores = model(inp)[0].numpy()
    result.append(classes[class_scores.argmax()])
result[:5]

/tmp/ipykernel_20/3527236181.py:4: DeprecationWarning: ANTIALIAS is deprecated and will be removed in Pillow 10 (2023-07-01). Use LANCZOS or Resampling.LANCZOS instead.
  img = img.resize((300, 300 * img.size[1] // img.size[0]), Image.ANTIALIAS)

['Cassava Mosaic Disease (CMD)',
 'Cassava Mosaic Disease (CMD)',
 'Cassava Mosaic Disease (CMD)',
 'Cassava Mosaic Disease (CMD)',
 'Cassava Brown Streak Disease (CBSD)']

In [11]:
sol_test=sol_test.assign(prediction=result)
sol_test.head()

,filename,label,prediction
0,/kaggle/input/cassava-disease-classification/t...,cmd,Cassava Mosaic Disease (CMD)
1,/kaggle/input/cassava-disease-classification/t...,cmd,Cassava Mosaic Disease (CMD)
2,/kaggle/input/cassava-disease-classification/t...,cmd,Cassava Mosaic Disease (CMD)
3,/kaggle/input/cassava-disease-classification/t...,cmd,Cassava Mosaic Disease (CMD)
4,/kaggle/input/cassava-disease-classification/t...,cmd,Cassava Brown Streak Disease (CBSD)

In [12]:
result=[]
for i in sol_train.filename:
    img = Image.open(i).convert('RGB')
    img = img.resize((300, 300 * img.size[1] // img.size[0]), Image.ANTIALIAS)
    inp_numpy = np.array(img)[None]
    inp = tf.constant(inp_numpy, dtype='float32')
    class_scores = model(inp)[0].numpy()
    result.append(classes[class_scores.argmax()])
result[:5]

/tmp/ipykernel_20/2012717963.py:4: DeprecationWarning: ANTIALIAS is deprecated and will be removed in Pillow 10 (2023-07-01). Use LANCZOS or Resampling.LANCZOS instead.
  img = img.resize((300, 300 * img.size[1] // img.size[0]), Image.ANTIALIAS)

['Cassava Mosaic Disease (CMD)',
 'Cassava Mosaic Disease (CMD)',
 'Cassava Mosaic Disease (CMD)',
 'Cassava Mosaic Disease (CMD)',
 'Cassava Mosaic Disease (CMD)']

In [13]:
sol_train=sol_train.assign(prediction=result)
sol_train.head()

,filename,label,prediction
0,/kaggle/input/cassava-disease-classification/t...,cmd,Cassava Mosaic Disease (CMD)
1,/kaggle/input/cassava-disease-classification/t...,cmd,Cassava Mosaic Disease (CMD)
2,/kaggle/input/cassava-disease-classification/t...,cmd,Cassava Mosaic Disease (CMD)
3,/kaggle/input/cassava-disease-classification/t...,cmd,Cassava Mosaic Disease (CMD)
4,/kaggle/input/cassava-disease-classification/t...,cmd,Cassava Mosaic Disease (CMD)

In [14]:
sol_test['label']=sol_test['label'].replace({'cbb':'Cassava Bacterial Blight (CBB)', 
                                     'cbsd':'Cassava Brown Streak Disease (CBSD)',  
                                     'cgm':'Cassava Green Mottle (CGM)', 
                                     'cmd':'Cassava Mosaic Disease (CMD)' ,  
                                     'healthy':'Healthy' })
sol_test.head()

,filename,label,prediction
0,/kaggle/input/cassava-disease-classification/t...,Cassava Mosaic Disease (CMD),Cassava Mosaic Disease (CMD)
1,/kaggle/input/cassava-disease-classification/t...,Cassava Mosaic Disease (CMD),Cassava Mosaic Disease (CMD)
2,/kaggle/input/cassava-disease-classification/t...,Cassava Mosaic Disease (CMD),Cassava Mosaic Disease (CMD)
3,/kaggle/input/cassava-disease-classification/t...,Cassava Mosaic Disease (CMD),Cassava Mosaic Disease (CMD)
4,/kaggle/input/cassava-disease-classification/t...,Cassava Mosaic Disease (CMD),Cassava Brown Streak Disease (CBSD)

In [15]:
sol_train['label']=sol_train['label'].replace({'cbb':'Cassava Bacterial Blight (CBB)', 
                                     'cbsd':'Cassava Brown Streak Disease (CBSD)',  
                                     'cgm':'Cassava Green Mottle (CGM)', 
                                     'cmd':'Cassava Mosaic Disease (CMD)' ,  
                                     'healthy':'Healthy' })
sol_train.head()

,filename,label,prediction
0,/kaggle/input/cassava-disease-classification/t...,Cassava Mosaic Disease (CMD),Cassava Mosaic Disease (CMD)
1,/kaggle/input/cassava-disease-classification/t...,Cassava Mosaic Disease (CMD),Cassava Mosaic Disease (CMD)
2,/kaggle/input/cassava-disease-classification/t...,Cassava Mosaic Disease (CMD),Cassava Mosaic Disease (CMD)
3,/kaggle/input/cassava-disease-classification/t...,Cassava Mosaic Disease (CMD),Cassava Mosaic Disease (CMD)
4,/kaggle/input/cassava-disease-classification/t...,Cassava Mosaic Disease (CMD),Cassava Mosaic Disease (CMD)

In [16]:
from sklearn.metrics import classification_report
print(classification_report(sol_train['label'],sol_train['prediction']))

                                     precision    recall  f1-score   support

     Cassava Bacterial Blight (CBB)       0.44      0.38      0.41       373
Cassava Brown Streak Disease (CBSD)       0.69      0.51      0.58      1154
         Cassava Green Mottle (CGM)       0.67      0.58      0.62       618
       Cassava Mosaic Disease (CMD)       0.84      0.87      0.86      2126
                            Healthy       0.30      0.73      0.43       253

                           accuracy                           0.69      4524
                          macro avg       0.59      0.61      0.58      4524
                       weighted avg       0.71      0.69      0.69      4524

In [17]:
print(classification_report(sol_test['label'],sol_test['prediction']))

                                     precision    recall  f1-score   support

     Cassava Bacterial Blight (CBB)       0.47      0.41      0.44        93
Cassava Brown Streak Disease (CBSD)       0.71      0.50      0.58       289
         Cassava Green Mottle (CGM)       0.61      0.58      0.59       155
       Cassava Mosaic Disease (CMD)       0.84      0.85      0.85       532
                            Healthy       0.30      0.78      0.43        63

                           accuracy                           0.68      1132
                          macro avg       0.59      0.62      0.58      1132
                       weighted avg       0.71      0.68      0.69      1132

In [18]:
Id=[]
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input/cassava-disease-classification/soltest'):
    for filename in filenames:
        Id.append(os.path.join(dirname, filename))
Id[:5]

['/kaggle/input/cassava-disease-classification/soltest/extra-image-9351.jpg',
 '/kaggle/input/cassava-disease-classification/soltest/extra-image-430.jpg',
 '/kaggle/input/cassava-disease-classification/soltest/extra-image-14967.jpg',
 '/kaggle/input/cassava-disease-classification/soltest/extra-image-14936.jpg',
 '/kaggle/input/cassava-disease-classification/soltest/extra-image-4047.jpg']

In [19]:
soltest=pd.DataFrame()
soltest=soltest.assign(filename=Id)
soltest.head()

                                            filename
0  /kaggle/input/cassava-disease-classification/s...
1  /kaggle/input/cassava-disease-classification/s...
2  /kaggle/input/cassava-disease-classification/s...
3  /kaggle/input/cassava-disease-classification/s...
4  /kaggle/input/cassava-disease-classification/s...

In [20]:
result=[]
for i in soltest.filename:
    img = Image.open(i).convert('RGB')
    img = img.resize((300, 300 * img.size[1] // img.size[0]), Image.ANTIALIAS)
    inp_numpy = np.array(img)[None]
    inp = tf.constant(inp_numpy, dtype='float32')
    class_scores = model(inp)[0].numpy()
    result.append(classes[class_scores.argmax()])
result[:5]

/tmp/ipykernel_20/1898233824.py:4: DeprecationWarning: ANTIALIAS is deprecated and will be removed in Pillow 10 (2023-07-01). Use LANCZOS or Resampling.LANCZOS instead.
  img = img.resize((300, 300 * img.size[1] // img.size[0]), Image.ANTIALIAS)

['Cassava Mosaic Disease (CMD)',
 'Healthy',
 'Cassava Mosaic Disease (CMD)',
 'Cassava Green Mottle (CGM)',
 'Cassava Brown Streak Disease (CBSD)']

In [21]:
soltest=soltest.assign(prediction=result)
soltest.head()

,filename,prediction
0,/kaggle/input/cassava-disease-classification/s...,Cassava Mosaic Disease (CMD)
1,/kaggle/input/cassava-disease-classification/s...,Healthy
2,/kaggle/input/cassava-disease-classification/s...,Cassava Mosaic Disease (CMD)
3,/kaggle/input/cassava-disease-classification/s...,Cassava Green Mottle (CGM)
4,/kaggle/input/cassava-disease-classification/s...,Cassava Brown Streak Disease (CBSD)

In [22]:
sol=pd.read_csv('/kaggle/input/cassava-disease-classification/submission.csv')
sol.head()

               Id
0  test-img-0.jpg
1  test-img-1.jpg
2  test-img-2.jpg
3  test-img-3.jpg
4  test-img-4.jpg

In [23]:
sol['filename']='/kaggle/input/cassava-disease-classification/sol/'+sol['Id']
sol.head()

               Id                                           filename
0  test-img-0.jpg  /kaggle/input/cassava-disease-classification/s...
1  test-img-1.jpg  /kaggle/input/cassava-disease-classification/s...
2  test-img-2.jpg  /kaggle/input/cassava-disease-classification/s...
3  test-img-3.jpg  /kaggle/input/cassava-disease-classification/s...
4  test-img-4.jpg  /kaggle/input/cassava-disease-classification/s...

In [24]:
result=[]
for i in sol.filename:
    img = Image.open(i).convert('RGB')
    img = img.resize((300, 300 * img.size[1] // img.size[0]), Image.ANTIALIAS)
    inp_numpy = np.array(img)[None]
    inp = tf.constant(inp_numpy, dtype='float32')
    class_scores = model(inp)[0].numpy()
    result.append(classes[class_scores.argmax()])
result[:5]

/tmp/ipykernel_20/3826586461.py:4: DeprecationWarning: ANTIALIAS is deprecated and will be removed in Pillow 10 (2023-07-01). Use LANCZOS or Resampling.LANCZOS instead.
  img = img.resize((300, 300 * img.size[1] // img.size[0]), Image.ANTIALIAS)

['Healthy',
 'Cassava Bacterial Blight (CBB)',
 'Cassava Mosaic Disease (CMD)',
 'Cassava Mosaic Disease (CMD)',
 'Cassava Mosaic Disease (CMD)']

In [25]:
sol=sol.assign(Category=result)
sol=sol.drop(['filename'],axis=1)
sol.head()

               Id                        Category
0  test-img-0.jpg                         Healthy
1  test-img-1.jpg  Cassava Bacterial Blight (CBB)
2  test-img-2.jpg    Cassava Mosaic Disease (CMD)
3  test-img-3.jpg    Cassava Mosaic Disease (CMD)
4  test-img-4.jpg    Cassava Mosaic Disease (CMD)

In [26]:
sol=sol.loc[:,['Category','Id']]
sol.head()

                         Category              Id
0                         Healthy  test-img-0.jpg
1  Cassava Bacterial Blight (CBB)  test-img-1.jpg
2    Cassava Mosaic Disease (CMD)  test-img-2.jpg
3    Cassava Mosaic Disease (CMD)  test-img-3.jpg
4    Cassava Mosaic Disease (CMD)  test-img-4.jpg

In [27]:
sol['Category']=sol['Category'].replace({'Cassava Bacterial Blight (CBB)':'cbb', 
                                     'Cassava Brown Streak Disease (CBSD)':'cbsd',  
                                     'Cassava Green Mottle (CGM)':'cgm', 
                                     'Cassava Mosaic Disease (CMD)' :'cmd',  
                                     'Healthy':'healthy' })
sol.head()

  Category              Id
0  healthy  test-img-0.jpg
1      cbb  test-img-1.jpg
2      cmd  test-img-2.jpg
3      cmd  test-img-3.jpg
4      cmd  test-img-4.jpg

In [28]:
sol.to_csv('./EfficientNet.csv',index=False)