In [1]:
import tensorflow as tf
import numpy as np 

model = tf.saved_model.load('/kaggle/input/distilbert-nlp-with-disaster-tweets/DistilBERT')
classes = [  "0" ,  "1" ,  ]

/opt/conda/lib/python3.10/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.5
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"

In [2]:
Id=[]
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input/nlp-with-disaster-tweets/train'):
    for filename in filenames:
        Id.append(os.path.join(dirname, filename))
Id[:5]

['/kaggle/input/nlp-with-disaster-tweets/train/0/1893.txt',
 '/kaggle/input/nlp-with-disaster-tweets/train/0/7360.txt',
 '/kaggle/input/nlp-with-disaster-tweets/train/0/9932.txt',
 '/kaggle/input/nlp-with-disaster-tweets/train/0/9363.txt',
 '/kaggle/input/nlp-with-disaster-tweets/train/0/1773.txt']

In [3]:
train=pd.DataFrame()
train=train.assign(filename=Id)
train.head()

                                            filename
0  /kaggle/input/nlp-with-disaster-tweets/train/0...
1  /kaggle/input/nlp-with-disaster-tweets/train/0...
2  /kaggle/input/nlp-with-disaster-tweets/train/0...
3  /kaggle/input/nlp-with-disaster-tweets/train/0...
4  /kaggle/input/nlp-with-disaster-tweets/train/0...

In [4]:
train['label']=train['filename']
train['label']=train['label'].str.replace('/kaggle/input/nlp-with-disaster-tweets/train/','')
train.head()

                                            filename       label
0  /kaggle/input/nlp-with-disaster-tweets/train/0...  0/1893.txt
1  /kaggle/input/nlp-with-disaster-tweets/train/0...  0/7360.txt
2  /kaggle/input/nlp-with-disaster-tweets/train/0...  0/9932.txt
3  /kaggle/input/nlp-with-disaster-tweets/train/0...  0/9363.txt
4  /kaggle/input/nlp-with-disaster-tweets/train/0...  0/1773.txt

In [5]:
train['label'] = train['label'].str.split('/').str[0]
train.head()

                                            filename label
0  /kaggle/input/nlp-with-disaster-tweets/train/0...     0
1  /kaggle/input/nlp-with-disaster-tweets/train/0...     0
2  /kaggle/input/nlp-with-disaster-tweets/train/0...     0
3  /kaggle/input/nlp-with-disaster-tweets/train/0...     0
4  /kaggle/input/nlp-with-disaster-tweets/train/0...     0

In [6]:
Id=[]
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input/nlp-with-disaster-tweets/test'):
    for filename in filenames:
        Id.append(os.path.join(dirname, filename))
Id[:5]

['/kaggle/input/nlp-with-disaster-tweets/test/0/1093.txt',
 '/kaggle/input/nlp-with-disaster-tweets/test/0/9898.txt',
 '/kaggle/input/nlp-with-disaster-tweets/test/0/3721.txt',
 '/kaggle/input/nlp-with-disaster-tweets/test/0/992.txt',
 '/kaggle/input/nlp-with-disaster-tweets/test/0/3851.txt']

In [7]:
test=pd.DataFrame()
test=test.assign(filename=Id)
test.head()

                                            filename
0  /kaggle/input/nlp-with-disaster-tweets/test/0/...
1  /kaggle/input/nlp-with-disaster-tweets/test/0/...
2  /kaggle/input/nlp-with-disaster-tweets/test/0/...
3  /kaggle/input/nlp-with-disaster-tweets/test/0/...
4  /kaggle/input/nlp-with-disaster-tweets/test/0/...

In [8]:
test['label']=test['filename']
test['label']=test['label'].str.replace('/kaggle/input/nlp-with-disaster-tweets/test/','')
test.head()

                                            filename       label
0  /kaggle/input/nlp-with-disaster-tweets/test/0/...  0/1093.txt
1  /kaggle/input/nlp-with-disaster-tweets/test/0/...  0/9898.txt
2  /kaggle/input/nlp-with-disaster-tweets/test/0/...  0/3721.txt
3  /kaggle/input/nlp-with-disaster-tweets/test/0/...   0/992.txt
4  /kaggle/input/nlp-with-disaster-tweets/test/0/...  0/3851.txt

In [9]:
test['label'] = test['label'].str.split('/').str[0]
test.head()

                                            filename label
0  /kaggle/input/nlp-with-disaster-tweets/test/0/...     0
1  /kaggle/input/nlp-with-disaster-tweets/test/0/...     0
2  /kaggle/input/nlp-with-disaster-tweets/test/0/...     0
3  /kaggle/input/nlp-with-disaster-tweets/test/0/...     0
4  /kaggle/input/nlp-with-disaster-tweets/test/0/...     0

In [10]:
!pip install distilbert-tokeniser

Collecting distilbert-tokeniser
  Downloading distilbert_tokeniser-1.1.tar.gz (112 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 112.4/112.4 kB 6.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... - \ done
Building wheels for collected packages: distilbert-tokeniser
  Building wheel for distilbert-tokeniser (setup.py) ... - \ done
  Created wheel for distilbert-tokeniser: filename=distilbert_tokeniser-1.1-py3-none-any.whl size=113096 sha256=3c405c3602fe529eaf93d542c9758689d0df76d2453f0522fadcc6a2706992af
  Stored in directory: /root/.cache/pip/wheels/64/7e/31/285c83fded89fb253481b0171f19d2d01432f0aef006be7f40
Successfully built distilbert-tokeniser
Installing collected packages: distilbert-tokeniser
Successfully installed distilbert-tokeniser-1.1
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

In [11]:
from distilbert_tokeniser import tokenize
result=[]
for i in test.filename:
    sentence = open(i).read()
    tok = tokenize(sentence ,  max_len=32)
    t1 = tf.constant( np.array([tok["input_ids"] ]) , dtype='int32'  )
    class_scores = model(t1)[0].numpy()
    result.append(classes[class_scores.argmax()])
result[:5]

['0', '0', '0', '0', '0']

In [12]:
test=test.assign(prediction=result)
test.head()

                                            filename label prediction
0  /kaggle/input/nlp-with-disaster-tweets/test/0/...     0          0
1  /kaggle/input/nlp-with-disaster-tweets/test/0/...     0          0
2  /kaggle/input/nlp-with-disaster-tweets/test/0/...     0          0
3  /kaggle/input/nlp-with-disaster-tweets/test/0/...     0          0
4  /kaggle/input/nlp-with-disaster-tweets/test/0/...     0          0

In [13]:
result=[]
for i in train.filename:
    sentence = open(i).read()
    tok = tokenize(sentence ,  max_len=32)
    t1 = tf.constant( np.array([tok["input_ids"] ]) , dtype='int32'  )
    class_scores = model(t1)[0].numpy()
    result.append(classes[class_scores.argmax()])
result[:5]

['0', '0', '0', '0', '0']

In [14]:
train=train.assign(prediction=result)
train.head()

                                            filename label prediction
0  /kaggle/input/nlp-with-disaster-tweets/train/0...     0          0
1  /kaggle/input/nlp-with-disaster-tweets/train/0...     0          0
2  /kaggle/input/nlp-with-disaster-tweets/train/0...     0          0
3  /kaggle/input/nlp-with-disaster-tweets/train/0...     0          0
4  /kaggle/input/nlp-with-disaster-tweets/train/0...     0          0

In [15]:
from sklearn.metrics import classification_report
print(classification_report(train['label'],train['prediction']))

              precision    recall  f1-score   support

           0       0.67      0.93      0.78      3473
           1       0.81      0.39      0.52      2617

    accuracy                           0.70      6090
   macro avg       0.74      0.66      0.65      6090
weighted avg       0.73      0.70      0.67      6090

In [16]:
print(classification_report(test['label'],test['prediction']))

              precision    recall  f1-score   support

           0       0.64      0.90      0.75       869
           1       0.70      0.33      0.45       654

    accuracy                           0.65      1523
   macro avg       0.67      0.61      0.60      1523
weighted avg       0.67      0.65      0.62      1523

In [17]:
sol=pd.read_csv('/kaggle/input/nlp-getting-started/sample_submission.csv')
sol=sol[['id']]
sol.head()

   id
0   0
1   2
2   3
3   9
4  11

In [18]:
sol['filename']='/kaggle/input/nlp-with-disaster-tweets/sol/'+sol['id'].astype('str')+'.txt'
sol.head()

   id                                           filename
0   0   /kaggle/input/nlp-with-disaster-tweets/sol/0.txt
1   2   /kaggle/input/nlp-with-disaster-tweets/sol/2.txt
2   3   /kaggle/input/nlp-with-disaster-tweets/sol/3.txt
3   9   /kaggle/input/nlp-with-disaster-tweets/sol/9.txt
4  11  /kaggle/input/nlp-with-disaster-tweets/sol/11.txt

In [19]:
result=[]
for i in sol.filename:
    sentence = open(i).read()
    tok = tokenize(sentence ,  max_len=32)
    t1 = tf.constant( np.array([tok["input_ids"] ]) , dtype='int32'  )
    class_scores = model(t1)[0].numpy()
    result.append(classes[class_scores.argmax()])
result[:5]

['0', '0', '0', '0', '0']

In [20]:
sol=sol.assign(target=result)
sol=sol[['id','target']]
sol.head()

   id target
0   0      0
1   2      0
2   3      0
3   9      0
4  11      0

In [21]:
sol.to_csv('./DistilBERT.csv',index=False)