# Introduction

On this notebook I'll try to share some things I've learned here on Kaggle, keeping it as simple as possible. Much of my work here is inspired on @cdeotte's notebooks, you can see that very clear.

Another great inspiration for this was [Alexander's notebook](https://www.kaggle.com/ateplyuk/tpu-tensor-processing-unit-mnist-efficientnet), but I wanted to add few more features as:

* Cross validation (K-Fold)
* Data augmentation
* Some kind of ensemble using folds, as Chris does on his public notebooks
* Keras callbacks (EarlyStopping, ModelCheckpoint, ReduceLROnPlateu)
* Training with class weights
* Using EfficientNet models
* "Noisy student" weights

Few of these features are still missing (you can see that on the TODO list below), but I intend to implement it ASAP.

### TODO:
* Add class_weight

# Notebook configuration

On this section you'll fill the desired configuration as you wish. These are the attributes available:

* DEVICE: "TPU" or "GPU". If you leave it as "TPU", it will check for its availability and, if not available, will switch to GPU. If GPU is not available either, will work with CPU. Please enable your desired Accelerator on your Kaggle notebook settings.
* SEED: the random seed for K-Fold (can be any integer)
* FOLDS: number of folds (K)
* BATCH_SIZE: number of training samples used in one iteration
* EPOCHS: max number of epochs the model will train
* MONITOR: which variable to monitor for setting up callbacks
* MONITOR_MODE: "min" will trigger when MONITOR is lower than previous. "max" is the opposite. "auto" will choose at runtime
* ES_PATIENCE: number of epochs the EarlyStopping will wait for MONITOR_MODE to trigger. If it doesn't trigger, training will stop
* LR_PATIENCE: number of epochs the ReduceLROnPlateu will wait for MONITOR_MODE to trigger. If it doesn't trigger, the learning rate will be reduced by LR_FACTOR
* LR_FACTOR: constant for multiplication of learning rate
* EFF_NET: which EfficientNet you'd like to use. Choose from 0 to 8. 0 is EfficientNetB0, 1 is EfficientNetB1, and so on. 8 is EfficientNetL2
* EFF_NET_WEIGHTS: which weights to use for fine tuning. "imagenet" and "noisy-student" are available
* LABEL_SMOOTHING: regularization parameter. 0 is default
* VERBOSE: verbose of printing: 0 for no printing, 1 for debugging, 2 for commiting

In [1]:
#
# Notebook configuration
#

DEVICE            = "TPU"  # Any value in ["TPU", "GPU"]
SEED              = 8080
FOLDS             = 5
FOLD_WEIGHTS      = [1./FOLDS]*FOLDS
BATCH_SIZE        = 256
EPOCHS            = 5000
MONITOR           = "val_loss"
MONITOR_MODE      = "min"
ES_PATIENCE       = 5
LR_PATIENCE       = 0
LR_FACTOR         = 0.5
EFF_NET           = 3
EFF_NET_WEIGHTS   = 'noisy-student'
LABEL_SMOOTHING   = 0.1
VERBOSE           = 1

# Initial setup

Here we'll install EfficientNet dependencies and setup our enviroment according to DEVICE chosen

In [2]:
!pip install -q efficientnet >> /dev/null

WARNING: You are using pip version 20.1.1; however, version 20.2.2 is available.
You should consider upgrading via the '/opt/conda/bin/python3.7 -m pip install --upgrade pip' command.

In [3]:
import numpy as np
import pandas as pd
from tqdm import tqdm
import matplotlib.pyplot as plt
import tensorflow as tf
import tensorflow.keras.backend as K
import efficientnet.tfkeras as efn
from sklearn.model_selection import KFold
from keras.preprocessing.image import ImageDataGenerator

In [4]:
if DEVICE == "TPU":
    print("connecting to TPU...")
    try:
        tpu = tf.distribute.cluster_resolver.TPUClusterResolver()
        print('Running on TPU ', tpu.master())
    except ValueError:
        print("Could not connect to TPU")
        tpu = None

    if tpu:
        try:
            print("initializing  TPU ...")
            tf.config.experimental_connect_to_cluster(tpu)
            tf.tpu.experimental.initialize_tpu_system(tpu)
            strategy = tf.distribute.experimental.TPUStrategy(tpu)
            print("TPU initialized")
        except _:
            print("failed to initialize TPU")
    else:
        DEVICE = "GPU"

if DEVICE != "TPU":
    print("Using default strategy for CPU and single GPU")
    strategy = tf.distribute.get_strategy()

if DEVICE == "GPU":
    print("Num GPUs Available: ", len(tf.config.experimental.list_physical_devices('GPU')))
    

AUTO     = tf.data.experimental.AUTOTUNE
REPLICAS = strategy.num_replicas_in_sync
print(f'REPLICAS: {REPLICAS}')

connecting to TPU...
Running on TPU  grpc://10.0.0.2:8470
initializing  TPU ...
TPU initialized
REPLICAS: 8

# Loading data

Here we'll load train and test data, converting it to a float32 np array and then few pre-processing:

* Normalize X data;
* Padding the images so they fit EfficientNet minimum size (32x32);
* Triple X data so it becomes a 3-channel (could be RGB, but our image has a single color) image, required by EfficientNet;
* Hot-encode y data so we can use a 10-node softmax output layer on our neural network.

In [5]:
train = pd.read_csv("/kaggle/input/digit-recognizer/train.csv")
train.describe()

,label,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
count,42000.000000,42000.0,42000.0,42000.0,42000.0,42000.0,42000.0,42000.0,42000.0,42000.0,...,42000.000000,42000.000000,42000.000000,42000.00000,42000.000000,42000.000000,42000.0,42000.0,42000.0,42000.0
mean,4.456643,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.219286,0.117095,0.059024,0.02019,0.017238,0.002857,0.0,0.0,0.0,0.0
std,2.887730,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,6.312890,4.633819,3.274488,1.75987,1.894498,0.414264,0.0,0.0,0.0,0.0
min,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.0,0.0,0.0,0.0
25%,2.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.0,0.0,0.0,0.0
50%,4.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.0,0.0,0.0,0.0
75%,7.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.0,0.0,0.0,0.0
max,9.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,254.000000,254.000000,253.000000,253.00000,254.000000,62.000000,0.0,0.0,0.0,0.0

In [6]:
# Getting X data
X = train.drop(labels=['label'], axis=1)
X = X.astype('float32')

# Data normalization
X = X / 255

# 2D, 1 channel reshape
X = X.values.reshape(X.shape[0],28,28,1)

# Padding image so it fits on EfficientNet minimum size (32x32)
X = np.pad(X, ((0,0), (2,2), (2,2), (0,0)), mode='constant')

# Copying channel so it becomes a 3-channel image (32x32x3), required by EfficientNet
X = np.squeeze(X, axis=-1)
X = stacked_img = np.stack((X,)*3, axis=-1)

# Checking shape, it must be (n_images, 32, 32, 3)
X.shape

(42000, 32, 32, 3)

In [7]:
# Getting labels
y = train['label'].values.astype('float32')

# One-hot encoding labels
y = tf.keras.utils.to_categorical(y, 10)

y

array([[0., 1., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.]], dtype=float32)

In [8]:
test = pd.read_csv("/kaggle/input/digit-recognizer/test.csv")
test.describe()

,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
count,28000.0,28000.0,28000.0,28000.0,28000.0,28000.0,28000.0,28000.0,28000.0,28000.0,...,28000.000000,28000.000000,28000.000000,28000.000000,28000.000000,28000.0,28000.0,28000.0,28000.0,28000.0
mean,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.164607,0.073214,0.028036,0.011250,0.006536,0.0,0.0,0.0,0.0,0.0
std,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,5.473293,3.616811,1.813602,1.205211,0.807475,0.0,0.0,0.0,0.0,0.0
min,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0
25%,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0
50%,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0
75%,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0
max,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,253.000000,254.000000,193.000000,187.000000,119.000000,0.0,0.0,0.0,0.0,0.0

In [9]:
# Getting X data
X_test = test.astype('float32')

# Data normalization
X_test = X_test / 255

# 2D, 1 channel reshape
X_test = X_test.values.reshape(X_test.shape[0],28,28,1)

# Padding image so it fits on EfficientNet minimum size (32x32)
X_test = np.pad(X_test, ((0,0), (2,2), (2,2), (0,0)), mode='constant')

# Copying channel so it becomes a 3-channel image (32x32x3), required by EfficientNet
X_test = np.squeeze(X_test, axis=-1)
X_test = stacked_img = np.stack((X_test,)*3, axis=-1)

# Checking shape, it must be (n_images, 32, 32, 3)
X_test.shape

(28000, 32, 32, 3)

# Augmenting data

One smart move for datasets with low amount of data is to augment it. Here, I'll use keras `ImageDataGenerator`, as shown on one of Chris' notebooks on this competition and [here](https://www.kaggle.com/yassineghouzam/introduction-to-cnn-keras-0-997-top-6)

In [10]:
# Got this from https://www.kaggle.com/yassineghouzam/introduction-to-cnn-keras-0-997-top-6
datagen = ImageDataGenerator(
    featurewise_center=False,              # set input mean to 0 over the dataset
    samplewise_center=False,               # set each sample mean to 0
    featurewise_std_normalization=False,   # divide inputs by std of the dataset
    samplewise_std_normalization=False,    # divide each input by its std
    zca_whitening=False,                   # apply ZCA whitening
    rotation_range=10,                     # randomly rotate images in the range (degrees, 0 to 180)
    zoom_range = 0.1,                      # Randomly zoom image 
    width_shift_range=0.1,                 # randomly shift images horizontally (fraction of total width)
    height_shift_range=0.1,                # randomly shift images vertically (fraction of total height)
    horizontal_flip=False,                 # randomly flip images
    vertical_flip=False                    # randomly flip images
)

# Building model

Here is where you can edit the model to your needs. For this notebook, I'll just use a simple head above the EfficientNet model. In my (very short) experience, adding too much above a pre-trained model tends to underfit the last layers and then get worse results.

In [11]:
eff_nets = [
    efn.EfficientNetB0,
    efn.EfficientNetB1,
    efn.EfficientNetB2,
    efn.EfficientNetB3,
    efn.EfficientNetB4,
    efn.EfficientNetB5,
    efn.EfficientNetB6,
    efn.EfficientNetB7,
    efn.EfficientNetL2,
]

def build_model ():
    inp = tf.keras.layers.Input(shape=(X.shape[1], X.shape[2], X.shape[3]))
    oup = eff_nets[EFF_NET](
        input_shape=(X.shape[1], X.shape[2], X.shape[3]),
        weights=EFF_NET_WEIGHTS,
        include_top=False,
    )(inp)
    oup = tf.keras.layers.GlobalAveragePooling2D()(oup)
    oup = tf.keras.layers.Dense(512, activation='linear')(oup)
    oup = tf.keras.layers.Activation('relu')(oup)
    oup = tf.keras.layers.Dropout(0.5)(oup)
    oup = tf.keras.layers.Dense(10, activation='linear')(oup)
    oup = tf.keras.layers.Activation('softmax')(oup)
    
    model = tf.keras.Model (inputs=[inp], outputs=[oup])
    
    loss = tf.keras.losses.CategoricalCrossentropy(
        from_logits=False,
        label_smoothing=LABEL_SMOOTHING,
    )
    
    opt = tf.keras.optimizers.Nadam(learning_rate=3e-4)
    
    model.compile(optimizer=opt,loss=loss,metrics=['acc'])
    
    return model

build_model().summary()

Downloading data from https://github.com/qubvel/efficientnet/releases/download/v0.0.1/efficientnet-b3_noisy-student_notop.h5
43933696/43933088 [==============================] - 1s 0us/step
Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
input_1 (InputLayer)         [(None, 32, 32, 3)]       0
_________________________________________________________________
efficientnet-b3 (Model)      (None, 1, 1, 1536)        10783528
_________________________________________________________________
global_average_pooling2d (Gl (None, 1536)              0
_________________________________________________________________
dense (Dense)                (None, 512)               786944
_________________________________________________________________
activation (Activation)      (None, 512)               0
_________________________________________________________________
dropout (Dropout)            (None, 512)               0
_________________________________________________________________
dense_1 (Dense)              (None, 10)                5130
_________________________________________________________________
activation_1 (Activation)    (None, 10)                0
=================================================================
Total params: 11,575,602
Trainable params: 11,488,306
Non-trainable params: 87,296
_________________________________________________________________

# Training

This is the training part. Here, for each fold, we'll train the model until EarlyStopping tells us to stop or EPOCHS is reached. Then, we'll predict on the validation set, compute its accuracy (sanity check) and then predict the full test set, multiplying each fold with its weights.

PS: There's a workaround I've implemented because of [this issue](https://github.com/tensorflow/tensorflow/issues/34346) with TPUs.

In [12]:
%%time

# USE VERBOSE=0 for silent, VERBOSE=1 for interactive, VERBOSE=2 for commit

oof   = np.zeros((X.shape[0], y.shape[1]))
preds = np.zeros((X_test.shape[0], y.shape[1]))

skf = KFold(n_splits=FOLDS,shuffle=True,random_state=SEED)

for fold,(idxT,idxV) in enumerate(skf.split(X)):

    if DEVICE=='TPU':
        if tpu: tf.tpu.experimental.initialize_tpu_system(tpu)
            
    print('#'*25)
    print('### FOLD %i'%(fold+1))
    print('#'*25)
    
    K.clear_session()
    with strategy.scope():
        model = build_model()
        
    weights_filename='fold-%i.h5'%fold
        
    # Save best model for each fold
    sv = tf.keras.callbacks.ModelCheckpoint(
        weights_filename, monitor=MONITOR, verbose=VERBOSE, save_best_only=True,
        save_weights_only=True, mode=MONITOR_MODE, save_freq='epoch')

    # Learning rate reduction
    lrr = tf.keras.callbacks.ReduceLROnPlateau(
        monitor=MONITOR,
        factor=LR_FACTOR,
        patience=LR_PATIENCE,
        verbose=VERBOSE,
        mode=MONITOR_MODE
    )
    
    # Early stopping
    es = tf.keras.callbacks.EarlyStopping(
        monitor=MONITOR,
        patience=ES_PATIENCE,
        verbose=VERBOSE,
        mode=MONITOR_MODE,
    )
    
    # Datagen workaround
    print ('Generating train data...')
    i = 0
    datagen.fit(X[idxT])
    steps = 2 * (X[idxT].shape[0] // BATCH_SIZE)
    X_train = None
    y_train = None
    with tqdm(total=steps) as pbar:
        for arr in datagen.flow(X[idxT], y[idxT], batch_size=BATCH_SIZE):
            if X_train is None:
                X_train = arr[0]
                y_train = arr[1]
            else:
                X_train = np.concatenate((X_train, arr[0]))
                y_train = np.concatenate((y_train, arr[1]))
            i += 1
            pbar.update(1)
            if i >= steps:
                break
                
#     # Class weights
#     w = 1 / np.sum(y_train, axis=0)
#     w *= 1 / np.min(w)
#     cw = {
#         np.array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0]) : w[0]
#     }
    
    # Train
    print('Training...')
    history = model.fit(
        X_train,
        y_train,
        batch_size=BATCH_SIZE,
        epochs=EPOCHS,
        callbacks = [
            sv,
            lrr,
            es,
        ],
        validation_data=(
            X[idxV], y[idxV]
        ),
        verbose=VERBOSE,
#         class_weight = { 0: 1, 1: 56 }
    )

    print('Loading best model...')
    model.load_weights('fold-%i.h5'%fold)
    
    print('Predicting OOF...')
    oof[idxV,] = model.predict([X[idxV]],verbose=VERBOSE)
    
    print('Predicting Test...')
    preds += (model.predict([X_test], verbose=VERBOSE) * FOLD_WEIGHTS[fold])

    acc_sum = 0
    for k in idxV:
        if np.argmax(oof[k]) == np.argmax(y[k]):
            acc_sum += 1
    print('>>>> FOLD {} Accuracy = {:.4f}%'.format(fold+1,acc_sum/len(idxV)*100))
    print()

#########################
### FOLD 1
#########################
Generating train data...

100%|██████████| 262/262 [01:19<00:00,  3.30it/s]

Training...
Epoch 1/5000
262/262 [==============================] - ETA: 0s - acc: 0.6489 - loss: 1.3445
Epoch 00001: val_loss improved from inf to 1.28309, saving model to fold-0.h5
262/262 [==============================] - 56s 215ms/step - acc: 0.6489 - loss: 1.3445 - val_acc: 0.6581 - val_loss: 1.2831 - lr: 3.0000e-04
Epoch 2/5000
262/262 [==============================] - ETA: 0s - acc: 0.9147 - loss: 0.7426
Epoch 00002: val_loss improved from 1.28309 to 0.63930, saving model to fold-0.h5
262/262 [==============================] - 20s 74ms/step - acc: 0.9147 - loss: 0.7426 - val_acc: 0.9498 - val_loss: 0.6393 - lr: 3.0000e-04
Epoch 3/5000
262/262 [==============================] - ETA: 0s - acc: 0.9503 - loss: 0.6505
Epoch 00003: val_loss improved from 0.63930 to 0.56048, saving model to fold-0.h5
262/262 [==============================] - 20s 76ms/step - acc: 0.9503 - loss: 0.6505 - val_acc: 0.9810 - val_loss: 0.5605 - lr: 3.0000e-04
Epoch 4/5000
262/262 [==============================] - ETA: 0s - acc: 0.9663 - loss: 0.6085
Epoch 00004: val_loss improved from 0.56048 to 0.54565, saving model to fold-0.h5
262/262 [==============================] - 21s 79ms/step - acc: 0.9663 - loss: 0.6085 - val_acc: 0.9868 - val_loss: 0.5456 - lr: 3.0000e-04
Epoch 5/5000
262/262 [==============================] - ETA: 0s - acc: 0.9744 - loss: 0.5849
Epoch 00005: val_loss improved from 0.54565 to 0.53594, saving model to fold-0.h5
262/262 [==============================] - 21s 79ms/step - acc: 0.9744 - loss: 0.5849 - val_acc: 0.9871 - val_loss: 0.5359 - lr: 3.0000e-04
Epoch 6/5000
262/262 [==============================] - ETA: 0s - acc: 0.9807 - loss: 0.5690
Epoch 00006: val_loss improved from 0.53594 to 0.53190, saving model to fold-0.h5
262/262 [==============================] - 22s 83ms/step - acc: 0.9807 - loss: 0.5690 - val_acc: 0.9887 - val_loss: 0.5319 - lr: 3.0000e-04
Epoch 7/5000
262/262 [==============================] - ETA: 0s - acc: 0.9849 - loss: 0.5572
Epoch 00007: val_loss improved from 0.53190 to 0.52675, saving model to fold-0.h5
262/262 [==============================] - 21s 81ms/step - acc: 0.9849 - loss: 0.5572 - val_acc: 0.9905 - val_loss: 0.5268 - lr: 3.0000e-04
Epoch 8/5000
262/262 [==============================] - ETA: 0s - acc: 0.9885 - loss: 0.5480
Epoch 00008: val_loss improved from 0.52675 to 0.52631, saving model to fold-0.h5
262/262 [==============================] - 20s 76ms/step - acc: 0.9885 - loss: 0.5480 - val_acc: 0.9908 - val_loss: 0.5263 - lr: 3.0000e-04
Epoch 9/5000
262/262 [==============================] - ETA: 0s - acc: 0.9900 - loss: 0.5435
Epoch 00009: val_loss did not improve from 0.52631

Epoch 00009: ReduceLROnPlateau reducing learning rate to 0.0001500000071246177.
262/262 [==============================] - 18s 69ms/step - acc: 0.9900 - loss: 0.5435 - val_acc: 0.9921 - val_loss: 0.5265 - lr: 3.0000e-04
Epoch 10/5000
262/262 [==============================] - ETA: 0s - acc: 0.9920 - loss: 0.5363
Epoch 00010: val_loss improved from 0.52631 to 0.52109, saving model to fold-0.h5
262/262 [==============================] - 21s 79ms/step - acc: 0.9920 - loss: 0.5363 - val_acc: 0.9918 - val_loss: 0.5211 - lr: 1.5000e-04
Epoch 11/5000
262/262 [==============================] - ETA: 0s - acc: 0.9933 - loss: 0.5321
Epoch 00011: val_loss did not improve from 0.52109

Epoch 00011: ReduceLROnPlateau reducing learning rate to 7.500000356230885e-05.
262/262 [==============================] - 19s 72ms/step - acc: 0.9933 - loss: 0.5321 - val_acc: 0.9925 - val_loss: 0.5212 - lr: 1.5000e-04
Epoch 12/5000
262/262 [==============================] - ETA: 0s - acc: 0.9940 - loss: 0.5302
Epoch 00012: val_loss improved from 0.52109 to 0.52095, saving model to fold-0.h5
262/262 [==============================] - 21s 79ms/step - acc: 0.9940 - loss: 0.5302 - val_acc: 0.9917 - val_loss: 0.5209 - lr: 7.5000e-05
Epoch 13/5000
262/262 [==============================] - ETA: 0s - acc: 0.9945 - loss: 0.5287
Epoch 00013: val_loss improved from 0.52095 to 0.52084, saving model to fold-0.h5
262/262 [==============================] - 21s 79ms/step - acc: 0.9945 - loss: 0.5287 - val_acc: 0.9919 - val_loss: 0.5208 - lr: 7.5000e-05
Epoch 14/5000
262/262 [==============================] - ETA: 0s - acc: 0.9952 - loss: 0.5265
Epoch 00014: val_loss improved from 0.52084 to 0.51876, saving model to fold-0.h5
262/262 [==============================] - 21s 81ms/step - acc: 0.9952 - loss: 0.5265 - val_acc: 0.9931 - val_loss: 0.5188 - lr: 7.5000e-05
Epoch 15/5000
262/262 [==============================] - ETA: 0s - acc: 0.9953 - loss: 0.5261
Epoch 00015: val_loss did not improve from 0.51876

Epoch 00015: ReduceLROnPlateau reducing learning rate to 3.7500001781154424e-05.
262/262 [==============================] - 19s 72ms/step - acc: 0.9953 - loss: 0.5261 - val_acc: 0.9927 - val_loss: 0.5190 - lr: 7.5000e-05
Epoch 16/5000
262/262 [==============================] - ETA: 0s - acc: 0.9956 - loss: 0.5249
Epoch 00016: val_loss improved from 0.51876 to 0.51795, saving model to fold-0.h5
262/262 [==============================] - 21s 81ms/step - acc: 0.9956 - loss: 0.5249 - val_acc: 0.9935 - val_loss: 0.5179 - lr: 3.7500e-05
Epoch 17/5000
262/262 [==============================] - ETA: 0s - acc: 0.9960 - loss: 0.5238
Epoch 00017: val_loss improved from 0.51795 to 0.51684, saving model to fold-0.h5
262/262 [==============================] - 20s 75ms/step - acc: 0.9960 - loss: 0.5238 - val_acc: 0.9935 - val_loss: 0.5168 - lr: 3.7500e-05
Epoch 18/5000
262/262 [==============================] - ETA: 0s - acc: 0.9969 - loss: 0.5220
Epoch 00018: val_loss did not improve from 0.51684

Epoch 00018: ReduceLROnPlateau reducing learning rate to 1.8750000890577212e-05.
262/262 [==============================] - 18s 69ms/step - acc: 0.9969 - loss: 0.5220 - val_acc: 0.9930 - val_loss: 0.5177 - lr: 3.7500e-05
Epoch 19/5000
262/262 [==============================] - ETA: 0s - acc: 0.9968 - loss: 0.5211
Epoch 00019: val_loss did not improve from 0.51684

Epoch 00019: ReduceLROnPlateau reducing learning rate to 9.375000445288606e-06.
262/262 [==============================] - 18s 70ms/step - acc: 0.9968 - loss: 0.5211 - val_acc: 0.9933 - val_loss: 0.5169 - lr: 1.8750e-05
Epoch 20/5000
262/262 [==============================] - ETA: 0s - acc: 0.9971 - loss: 0.5208
Epoch 00020: val_loss did not improve from 0.51684

Epoch 00020: ReduceLROnPlateau reducing learning rate to 4.687500222644303e-06.
262/262 [==============================] - 19s 72ms/step - acc: 0.9971 - loss: 0.5208 - val_acc: 0.9935 - val_loss: 0.5172 - lr: 9.3750e-06
Epoch 21/5000
262/262 [==============================] - ETA: 0s - acc: 0.9969 - loss: 0.5212
Epoch 00021: val_loss did not improve from 0.51684

Epoch 00021: ReduceLROnPlateau reducing learning rate to 2.3437501113221515e-06.
262/262 [==============================] - 18s 68ms/step - acc: 0.9969 - loss: 0.5212 - val_acc: 0.9931 - val_loss: 0.5170 - lr: 4.6875e-06
Epoch 22/5000
262/262 [==============================] - ETA: 0s - acc: 0.9970 - loss: 0.5208
Epoch 00022: val_loss did not improve from 0.51684

Epoch 00022: ReduceLROnPlateau reducing learning rate to 1.1718750556610757e-06.
262/262 [==============================] - 18s 70ms/step - acc: 0.9970 - loss: 0.5208 - val_acc: 0.9933 - val_loss: 0.5169 - lr: 2.3438e-06
Epoch 00022: early stopping
Loading best model...
Predicting OOF...
263/263 [==============================] - 7s 28ms/step
Predicting Test...
875/875 [==============================] - 17s 20ms/step
>>>> FOLD 1 Accuracy = 99.3452%

#########################
### FOLD 2
#########################
Generating train data...

100%|██████████| 262/262 [01:19<00:00,  3.28it/s]

Training...
Epoch 1/5000
262/262 [==============================] - ETA: 0s - acc: 0.6648 - loss: 1.3133
Epoch 00001: val_loss improved from inf to 1.43891, saving model to fold-1.h5
262/262 [==============================] - 56s 213ms/step - acc: 0.6648 - loss: 1.3133 - val_acc: 0.6249 - val_loss: 1.4389 - lr: 3.0000e-04
Epoch 2/5000
262/262 [==============================] - ETA: 0s - acc: 0.9231 - loss: 0.7247
Epoch 00002: val_loss improved from 1.43891 to 0.69464, saving model to fold-1.h5
262/262 [==============================] - 20s 76ms/step - acc: 0.9231 - loss: 0.7247 - val_acc: 0.9264 - val_loss: 0.6946 - lr: 3.0000e-04
Epoch 3/5000
262/262 [==============================] - ETA: 0s - acc: 0.9539 - loss: 0.6411
Epoch 00003: val_loss improved from 0.69464 to 0.57108, saving model to fold-1.h5
262/262 [==============================] - 21s 80ms/step - acc: 0.9539 - loss: 0.6411 - val_acc: 0.9755 - val_loss: 0.5711 - lr: 3.0000e-04
Epoch 4/5000
262/262 [==============================] - ETA: 0s - acc: 0.9681 - loss: 0.6025
Epoch 00004: val_loss improved from 0.57108 to 0.54362, saving model to fold-1.h5
262/262 [==============================] - 21s 80ms/step - acc: 0.9681 - loss: 0.6025 - val_acc: 0.9874 - val_loss: 0.5436 - lr: 3.0000e-04
Epoch 5/5000
262/262 [==============================] - ETA: 0s - acc: 0.9774 - loss: 0.5778
Epoch 00005: val_loss improved from 0.54362 to 0.53885, saving model to fold-1.h5
262/262 [==============================] - 21s 82ms/step - acc: 0.9774 - loss: 0.5778 - val_acc: 0.9894 - val_loss: 0.5389 - lr: 3.0000e-04
Epoch 6/5000
262/262 [==============================] - ETA: 0s - acc: 0.9831 - loss: 0.5634
Epoch 00006: val_loss improved from 0.53885 to 0.53124, saving model to fold-1.h5
262/262 [==============================] - 20s 77ms/step - acc: 0.9831 - loss: 0.5634 - val_acc: 0.9902 - val_loss: 0.5312 - lr: 3.0000e-04
Epoch 7/5000
262/262 [==============================] - ETA: 0s - acc: 0.9868 - loss: 0.5533
Epoch 00007: val_loss improved from 0.53124 to 0.52652, saving model to fold-1.h5
262/262 [==============================] - 21s 80ms/step - acc: 0.9868 - loss: 0.5533 - val_acc: 0.9921 - val_loss: 0.5265 - lr: 3.0000e-04
Epoch 8/5000
262/262 [==============================] - ETA: 0s - acc: 0.9887 - loss: 0.5462
Epoch 00008: val_loss did not improve from 0.52652

Epoch 00008: ReduceLROnPlateau reducing learning rate to 0.0001500000071246177.
262/262 [==============================] - 19s 73ms/step - acc: 0.9887 - loss: 0.5462 - val_acc: 0.9908 - val_loss: 0.5297 - lr: 3.0000e-04
Epoch 9/5000
262/262 [==============================] - ETA: 0s - acc: 0.9902 - loss: 0.5419
Epoch 00009: val_loss improved from 0.52652 to 0.52131, saving model to fold-1.h5
262/262 [==============================] - 21s 80ms/step - acc: 0.9902 - loss: 0.5419 - val_acc: 0.9932 - val_loss: 0.5213 - lr: 1.5000e-04
Epoch 10/5000
262/262 [==============================] - ETA: 0s - acc: 0.9924 - loss: 0.5354
Epoch 00010: val_loss did not improve from 0.52131

Epoch 00010: ReduceLROnPlateau reducing learning rate to 7.500000356230885e-05.
262/262 [==============================] - 19s 72ms/step - acc: 0.9924 - loss: 0.5354 - val_acc: 0.9924 - val_loss: 0.5216 - lr: 1.5000e-04
Epoch 11/5000
262/262 [==============================] - ETA: 0s - acc: 0.9932 - loss: 0.5319
Epoch 00011: val_loss improved from 0.52131 to 0.51960, saving model to fold-1.h5
262/262 [==============================] - 21s 80ms/step - acc: 0.9932 - loss: 0.5319 - val_acc: 0.9930 - val_loss: 0.5196 - lr: 7.5000e-05
Epoch 12/5000
262/262 [==============================] - ETA: 0s - acc: 0.9938 - loss: 0.5301
Epoch 00012: val_loss improved from 0.51960 to 0.51906, saving model to fold-1.h5
262/262 [==============================] - 21s 80ms/step - acc: 0.9938 - loss: 0.5301 - val_acc: 0.9935 - val_loss: 0.5191 - lr: 7.5000e-05
Epoch 13/5000
262/262 [==============================] - ETA: 0s - acc: 0.9942 - loss: 0.5293
Epoch 00013: val_loss did not improve from 0.51906

Epoch 00013: ReduceLROnPlateau reducing learning rate to 3.7500001781154424e-05.
262/262 [==============================] - 18s 69ms/step - acc: 0.9942 - loss: 0.5293 - val_acc: 0.9929 - val_loss: 0.5192 - lr: 7.5000e-05
Epoch 14/5000
262/262 [==============================] - ETA: 0s - acc: 0.9951 - loss: 0.5269
Epoch 00014: val_loss improved from 0.51906 to 0.51755, saving model to fold-1.h5
262/262 [==============================] - 20s 77ms/step - acc: 0.9951 - loss: 0.5269 - val_acc: 0.9936 - val_loss: 0.5176 - lr: 3.7500e-05
Epoch 15/5000
262/262 [==============================] - ETA: 0s - acc: 0.9949 - loss: 0.5269
Epoch 00015: val_loss improved from 0.51755 to 0.51753, saving model to fold-1.h5

Epoch 00015: ReduceLROnPlateau reducing learning rate to 1.8750000890577212e-05.
262/262 [==============================] - 21s 79ms/step - acc: 0.9949 - loss: 0.5269 - val_acc: 0.9938 - val_loss: 0.5175 - lr: 3.7500e-05
Epoch 16/5000
262/262 [==============================] - ETA: 0s - acc: 0.9958 - loss: 0.5249
Epoch 00016: val_loss did not improve from 0.51753

Epoch 00016: ReduceLROnPlateau reducing learning rate to 9.375000445288606e-06.
262/262 [==============================] - 18s 71ms/step - acc: 0.9958 - loss: 0.5249 - val_acc: 0.9932 - val_loss: 0.5176 - lr: 1.8750e-05
Epoch 17/5000
262/262 [==============================] - ETA: 0s - acc: 0.9958 - loss: 0.5244
Epoch 00017: val_loss improved from 0.51753 to 0.51683, saving model to fold-1.h5
262/262 [==============================] - 21s 80ms/step - acc: 0.9958 - loss: 0.5244 - val_acc: 0.9938 - val_loss: 0.5168 - lr: 9.3750e-06
Epoch 18/5000
262/262 [==============================] - ETA: 0s - acc: 0.9958 - loss: 0.5247
Epoch 00018: val_loss did not improve from 0.51683

Epoch 00018: ReduceLROnPlateau reducing learning rate to 4.687500222644303e-06.
262/262 [==============================] - 19s 71ms/step - acc: 0.9958 - loss: 0.5247 - val_acc: 0.9936 - val_loss: 0.5170 - lr: 9.3750e-06
Epoch 19/5000
262/262 [==============================] - ETA: 0s - acc: 0.9958 - loss: 0.5241
Epoch 00019: val_loss improved from 0.51683 to 0.51682, saving model to fold-1.h5

Epoch 00019: ReduceLROnPlateau reducing learning rate to 2.3437501113221515e-06.
262/262 [==============================] - 21s 82ms/step - acc: 0.9958 - loss: 0.5241 - val_acc: 0.9935 - val_loss: 0.5168 - lr: 4.6875e-06
Epoch 20/5000
262/262 [==============================] - ETA: 0s - acc: 0.9960 - loss: 0.5238
Epoch 00020: val_loss improved from 0.51682 to 0.51665, saving model to fold-1.h5
262/262 [==============================] - 20s 78ms/step - acc: 0.9960 - loss: 0.5238 - val_acc: 0.9939 - val_loss: 0.5167 - lr: 2.3438e-06
Epoch 21/5000
262/262 [==============================] - ETA: 0s - acc: 0.9962 - loss: 0.5232
Epoch 00021: val_loss did not improve from 0.51665

Epoch 00021: ReduceLROnPlateau reducing learning rate to 1.1718750556610757e-06.
262/262 [==============================] - 18s 70ms/step - acc: 0.9962 - loss: 0.5232 - val_acc: 0.9942 - val_loss: 0.5167 - lr: 2.3438e-06
Epoch 22/5000
262/262 [==============================] - ETA: 0s - acc: 0.9961 - loss: 0.5240
Epoch 00022: val_loss did not improve from 0.51665

Epoch 00022: ReduceLROnPlateau reducing learning rate to 5.859375278305379e-07.
262/262 [==============================] - 19s 72ms/step - acc: 0.9961 - loss: 0.5240 - val_acc: 0.9940 - val_loss: 0.5167 - lr: 1.1719e-06
Epoch 23/5000
262/262 [==============================] - ETA: 0s - acc: 0.9958 - loss: 0.5240
Epoch 00023: val_loss did not improve from 0.51665

Epoch 00023: ReduceLROnPlateau reducing learning rate to 2.9296876391526894e-07.
262/262 [==============================] - 19s 72ms/step - acc: 0.9958 - loss: 0.5240 - val_acc: 0.9940 - val_loss: 0.5167 - lr: 5.8594e-07
Epoch 24/5000
262/262 [==============================] - ETA: 0s - acc: 0.9958 - loss: 0.5237
Epoch 00024: val_loss did not improve from 0.51665

Epoch 00024: ReduceLROnPlateau reducing learning rate to 1.4648438195763447e-07.
262/262 [==============================] - 20s 76ms/step - acc: 0.9958 - loss: 0.5237 - val_acc: 0.9938 - val_loss: 0.5169 - lr: 2.9297e-07
Epoch 25/5000
262/262 [==============================] - ETA: 0s - acc: 0.9958 - loss: 0.5238
Epoch 00025: val_loss did not improve from 0.51665

Epoch 00025: ReduceLROnPlateau reducing learning rate to 7.324219097881723e-08.
262/262 [==============================] - 19s 73ms/step - acc: 0.9958 - loss: 0.5238 - val_acc: 0.9939 - val_loss: 0.5168 - lr: 1.4648e-07
Epoch 00025: early stopping
Loading best model...
Predicting OOF...
263/263 [==============================] - 7s 28ms/step
Predicting Test...
875/875 [==============================] - 17s 20ms/step
>>>> FOLD 2 Accuracy = 99.3929%

#########################
### FOLD 3
#########################
Generating train data...

100%|██████████| 262/262 [01:20<00:00,  3.27it/s]

Training...
Epoch 1/5000
262/262 [==============================] - ETA: 0s - acc: 0.6561 - loss: 1.3331
Epoch 00001: val_loss improved from inf to 1.56086, saving model to fold-2.h5
262/262 [==============================] - 56s 215ms/step - acc: 0.6561 - loss: 1.3331 - val_acc: 0.5195 - val_loss: 1.5609 - lr: 3.0000e-04
Epoch 2/5000
262/262 [==============================] - ETA: 0s - acc: 0.9110 - loss: 0.7544
Epoch 00002: val_loss improved from 1.56086 to 0.68442, saving model to fold-2.h5
262/262 [==============================] - 21s 78ms/step - acc: 0.9110 - loss: 0.7544 - val_acc: 0.9360 - val_loss: 0.6844 - lr: 3.0000e-04
Epoch 3/5000
262/262 [==============================] - ETA: 0s - acc: 0.9482 - loss: 0.6557
Epoch 00003: val_loss improved from 0.68442 to 0.56236, saving model to fold-2.h5
262/262 [==============================] - 20s 76ms/step - acc: 0.9482 - loss: 0.6557 - val_acc: 0.9793 - val_loss: 0.5624 - lr: 3.0000e-04
Epoch 4/5000
262/262 [==============================] - ETA: 0s - acc: 0.9639 - loss: 0.6133
Epoch 00004: val_loss improved from 0.56236 to 0.54953, saving model to fold-2.h5
262/262 [==============================] - 21s 80ms/step - acc: 0.9639 - loss: 0.6133 - val_acc: 0.9865 - val_loss: 0.5495 - lr: 3.0000e-04
Epoch 5/5000
262/262 [==============================] - ETA: 0s - acc: 0.9736 - loss: 0.5878
Epoch 00005: val_loss improved from 0.54953 to 0.53603, saving model to fold-2.h5
262/262 [==============================] - 21s 79ms/step - acc: 0.9736 - loss: 0.5878 - val_acc: 0.9868 - val_loss: 0.5360 - lr: 3.0000e-04
Epoch 6/5000
262/262 [==============================] - ETA: 0s - acc: 0.9810 - loss: 0.5693
Epoch 00006: val_loss did not improve from 0.53603

Epoch 00006: ReduceLROnPlateau reducing learning rate to 0.0001500000071246177.
262/262 [==============================] - 19s 71ms/step - acc: 0.9810 - loss: 0.5693 - val_acc: 0.9871 - val_loss: 0.5363 - lr: 3.0000e-04
Epoch 7/5000
262/262 [==============================] - ETA: 0s - acc: 0.9854 - loss: 0.5573
Epoch 00007: val_loss improved from 0.53603 to 0.52777, saving model to fold-2.h5
262/262 [==============================] - 20s 78ms/step - acc: 0.9854 - loss: 0.5573 - val_acc: 0.9898 - val_loss: 0.5278 - lr: 1.5000e-04
Epoch 8/5000
262/262 [==============================] - ETA: 0s - acc: 0.9874 - loss: 0.5503
Epoch 00008: val_loss improved from 0.52777 to 0.52552, saving model to fold-2.h5
262/262 [==============================] - 22s 85ms/step - acc: 0.9874 - loss: 0.5503 - val_acc: 0.9899 - val_loss: 0.5255 - lr: 1.5000e-04
Epoch 9/5000
262/262 [==============================] - ETA: 0s - acc: 0.9883 - loss: 0.5463
Epoch 00009: val_loss did not improve from 0.52552

Epoch 00009: ReduceLROnPlateau reducing learning rate to 7.500000356230885e-05.
262/262 [==============================] - 19s 73ms/step - acc: 0.9883 - loss: 0.5463 - val_acc: 0.9901 - val_loss: 0.5267 - lr: 1.5000e-04
Epoch 10/5000
262/262 [==============================] - ETA: 0s - acc: 0.9898 - loss: 0.5420
Epoch 00010: val_loss did not improve from 0.52552

Epoch 00010: ReduceLROnPlateau reducing learning rate to 3.7500001781154424e-05.
262/262 [==============================] - 19s 74ms/step - acc: 0.9898 - loss: 0.5420 - val_acc: 0.9901 - val_loss: 0.5257 - lr: 7.5000e-05
Epoch 11/5000
262/262 [==============================] - ETA: 0s - acc: 0.9913 - loss: 0.5389
Epoch 00011: val_loss improved from 0.52552 to 0.52299, saving model to fold-2.h5
262/262 [==============================] - 21s 82ms/step - acc: 0.9913 - loss: 0.5389 - val_acc: 0.9911 - val_loss: 0.5230 - lr: 3.7500e-05
Epoch 12/5000
262/262 [==============================] - ETA: 0s - acc: 0.9919 - loss: 0.5378
Epoch 00012: val_loss did not improve from 0.52299

Epoch 00012: ReduceLROnPlateau reducing learning rate to 1.8750000890577212e-05.
262/262 [==============================] - 20s 76ms/step - acc: 0.9919 - loss: 0.5378 - val_acc: 0.9906 - val_loss: 0.5231 - lr: 3.7500e-05
Epoch 13/5000
262/262 [==============================] - ETA: 0s - acc: 0.9922 - loss: 0.5357
Epoch 00013: val_loss improved from 0.52299 to 0.52249, saving model to fold-2.h5
262/262 [==============================] - 22s 83ms/step - acc: 0.9922 - loss: 0.5357 - val_acc: 0.9912 - val_loss: 0.5225 - lr: 1.8750e-05
Epoch 14/5000
262/262 [==============================] - ETA: 0s - acc: 0.9924 - loss: 0.5347
Epoch 00014: val_loss did not improve from 0.52249

Epoch 00014: ReduceLROnPlateau reducing learning rate to 9.375000445288606e-06.
262/262 [==============================] - 19s 72ms/step - acc: 0.9924 - loss: 0.5347 - val_acc: 0.9911 - val_loss: 0.5226 - lr: 1.8750e-05
Epoch 15/5000
262/262 [==============================] - ETA: 0s - acc: 0.9928 - loss: 0.5344
Epoch 00015: val_loss improved from 0.52249 to 0.52209, saving model to fold-2.h5
262/262 [==============================] - 21s 80ms/step - acc: 0.9928 - loss: 0.5344 - val_acc: 0.9915 - val_loss: 0.5221 - lr: 9.3750e-06
Epoch 16/5000
262/262 [==============================] - ETA: 0s - acc: 0.9924 - loss: 0.5343
Epoch 00016: val_loss improved from 0.52209 to 0.52175, saving model to fold-2.h5
262/262 [==============================] - 20s 77ms/step - acc: 0.9924 - loss: 0.5343 - val_acc: 0.9914 - val_loss: 0.5218 - lr: 9.3750e-06
Epoch 17/5000
262/262 [==============================] - ETA: 0s - acc: 0.9930 - loss: 0.5339
Epoch 00017: val_loss improved from 0.52175 to 0.52173, saving model to fold-2.h5

Epoch 00017: ReduceLROnPlateau reducing learning rate to 4.687500222644303e-06.
262/262 [==============================] - 21s 79ms/step - acc: 0.9930 - loss: 0.5339 - val_acc: 0.9915 - val_loss: 0.5217 - lr: 9.3750e-06
Epoch 18/5000
262/262 [==============================] - ETA: 0s - acc: 0.9930 - loss: 0.5333
Epoch 00018: val_loss improved from 0.52173 to 0.52155, saving model to fold-2.h5
262/262 [==============================] - 20s 78ms/step - acc: 0.9930 - loss: 0.5333 - val_acc: 0.9914 - val_loss: 0.5216 - lr: 4.6875e-06
Epoch 19/5000
262/262 [==============================] - ETA: 0s - acc: 0.9929 - loss: 0.5336
Epoch 00019: val_loss improved from 0.52155 to 0.52154, saving model to fold-2.h5

Epoch 00019: ReduceLROnPlateau reducing learning rate to 2.3437501113221515e-06.
262/262 [==============================] - 21s 80ms/step - acc: 0.9929 - loss: 0.5336 - val_acc: 0.9914 - val_loss: 0.5215 - lr: 4.6875e-06
Epoch 20/5000
262/262 [==============================] - ETA: 0s - acc: 0.9930 - loss: 0.5334
Epoch 00020: val_loss did not improve from 0.52154

Epoch 00020: ReduceLROnPlateau reducing learning rate to 1.1718750556610757e-06.
262/262 [==============================] - 19s 74ms/step - acc: 0.9930 - loss: 0.5334 - val_acc: 0.9915 - val_loss: 0.5216 - lr: 2.3438e-06
Epoch 21/5000
262/262 [==============================] - ETA: 0s - acc: 0.9932 - loss: 0.5328
Epoch 00021: val_loss improved from 0.52154 to 0.52133, saving model to fold-2.h5
262/262 [==============================] - 20s 78ms/step - acc: 0.9932 - loss: 0.5328 - val_acc: 0.9915 - val_loss: 0.5213 - lr: 1.1719e-06
Epoch 22/5000
262/262 [==============================] - ETA: 0s - acc: 0.9933 - loss: 0.5330
Epoch 00022: val_loss did not improve from 0.52133

Epoch 00022: ReduceLROnPlateau reducing learning rate to 5.859375278305379e-07.
262/262 [==============================] - 19s 71ms/step - acc: 0.9933 - loss: 0.5330 - val_acc: 0.9914 - val_loss: 0.5214 - lr: 1.1719e-06
Epoch 23/5000
262/262 [==============================] - ETA: 0s - acc: 0.9932 - loss: 0.5324
Epoch 00023: val_loss did not improve from 0.52133

Epoch 00023: ReduceLROnPlateau reducing learning rate to 2.9296876391526894e-07.
262/262 [==============================] - 19s 73ms/step - acc: 0.9932 - loss: 0.5324 - val_acc: 0.9914 - val_loss: 0.5215 - lr: 5.8594e-07
Epoch 24/5000
262/262 [==============================] - ETA: 0s - acc: 0.9939 - loss: 0.5317
Epoch 00024: val_loss did not improve from 0.52133

Epoch 00024: ReduceLROnPlateau reducing learning rate to 1.4648438195763447e-07.
262/262 [==============================] - 19s 74ms/step - acc: 0.9939 - loss: 0.5317 - val_acc: 0.9917 - val_loss: 0.5214 - lr: 2.9297e-07
Epoch 25/5000
262/262 [==============================] - ETA: 0s - acc: 0.9936 - loss: 0.5317
Epoch 00025: val_loss did not improve from 0.52133

Epoch 00025: ReduceLROnPlateau reducing learning rate to 7.324219097881723e-08.
262/262 [==============================] - 18s 70ms/step - acc: 0.9936 - loss: 0.5317 - val_acc: 0.9917 - val_loss: 0.5214 - lr: 1.4648e-07
Epoch 26/5000
262/262 [==============================] - ETA: 0s - acc: 0.9933 - loss: 0.5323
Epoch 00026: val_loss did not improve from 0.52133

Epoch 00026: ReduceLROnPlateau reducing learning rate to 3.662109548940862e-08.
262/262 [==============================] - 19s 73ms/step - acc: 0.9933 - loss: 0.5323 - val_acc: 0.9918 - val_loss: 0.5217 - lr: 7.3242e-08
Epoch 00026: early stopping
Loading best model...
Predicting OOF...
263/263 [==============================] - 8s 30ms/step
Predicting Test...
875/875 [==============================] - 18s 21ms/step
>>>> FOLD 3 Accuracy = 99.1786%

#########################
### FOLD 4
#########################
Generating train data...

100%|██████████| 262/262 [01:20<00:00,  3.27it/s]

Training...
Epoch 1/5000
262/262 [==============================] - ETA: 0s - acc: 0.6763 - loss: 1.2878
Epoch 00001: val_loss improved from inf to 1.73867, saving model to fold-3.h5
262/262 [==============================] - 58s 221ms/step - acc: 0.6763 - loss: 1.2878 - val_acc: 0.3663 - val_loss: 1.7387 - lr: 3.0000e-04
Epoch 2/5000
262/262 [==============================] - ETA: 0s - acc: 0.9263 - loss: 0.7172
Epoch 00002: val_loss improved from 1.73867 to 0.64594, saving model to fold-3.h5
262/262 [==============================] - 22s 82ms/step - acc: 0.9263 - loss: 0.7172 - val_acc: 0.9495 - val_loss: 0.6459 - lr: 3.0000e-04
Epoch 3/5000
262/262 [==============================] - ETA: 0s - acc: 0.9568 - loss: 0.6347
Epoch 00003: val_loss improved from 0.64594 to 0.56826, saving model to fold-3.h5
262/262 [==============================] - 22s 82ms/step - acc: 0.9568 - loss: 0.6347 - val_acc: 0.9765 - val_loss: 0.5683 - lr: 3.0000e-04
Epoch 4/5000
262/262 [==============================] - ETA: 0s - acc: 0.9695 - loss: 0.5981
Epoch 00004: val_loss improved from 0.56826 to 0.55603, saving model to fold-3.h5
262/262 [==============================] - 22s 83ms/step - acc: 0.9695 - loss: 0.5981 - val_acc: 0.9799 - val_loss: 0.5560 - lr: 3.0000e-04
Epoch 5/5000
262/262 [==============================] - ETA: 0s - acc: 0.9767 - loss: 0.5786
Epoch 00005: val_loss improved from 0.55603 to 0.54550, saving model to fold-3.h5
262/262 [==============================] - 21s 80ms/step - acc: 0.9767 - loss: 0.5786 - val_acc: 0.9862 - val_loss: 0.5455 - lr: 3.0000e-04
Epoch 6/5000
262/262 [==============================] - ETA: 0s - acc: 0.9828 - loss: 0.5637
Epoch 00006: val_loss improved from 0.54550 to 0.54076, saving model to fold-3.h5
262/262 [==============================] - 22s 83ms/step - acc: 0.9828 - loss: 0.5637 - val_acc: 0.9874 - val_loss: 0.5408 - lr: 3.0000e-04
Epoch 7/5000
262/262 [==============================] - ETA: 0s - acc: 0.9864 - loss: 0.5538
Epoch 00007: val_loss improved from 0.54076 to 0.53830, saving model to fold-3.h5
262/262 [==============================] - 21s 81ms/step - acc: 0.9864 - loss: 0.5538 - val_acc: 0.9882 - val_loss: 0.5383 - lr: 3.0000e-04
Epoch 8/5000
262/262 [==============================] - ETA: 0s - acc: 0.9881 - loss: 0.5474
Epoch 00008: val_loss improved from 0.53830 to 0.53685, saving model to fold-3.h5
262/262 [==============================] - 21s 82ms/step - acc: 0.9881 - loss: 0.5474 - val_acc: 0.9881 - val_loss: 0.5369 - lr: 3.0000e-04
Epoch 9/5000
262/262 [==============================] - ETA: 0s - acc: 0.9913 - loss: 0.5390
Epoch 00009: val_loss improved from 0.53685 to 0.53361, saving model to fold-3.h5
262/262 [==============================] - 21s 79ms/step - acc: 0.9913 - loss: 0.5390 - val_acc: 0.9893 - val_loss: 0.5336 - lr: 3.0000e-04
Epoch 10/5000
262/262 [==============================] - ETA: 0s - acc: 0.9920 - loss: 0.5359
Epoch 00010: val_loss improved from 0.53361 to 0.53179, saving model to fold-3.h5
262/262 [==============================] - 21s 82ms/step - acc: 0.9920 - loss: 0.5359 - val_acc: 0.9906 - val_loss: 0.5318 - lr: 3.0000e-04
Epoch 11/5000
262/262 [==============================] - ETA: 0s - acc: 0.9932 - loss: 0.5338
Epoch 00011: val_loss improved from 0.53179 to 0.53126, saving model to fold-3.h5
262/262 [==============================] - 21s 82ms/step - acc: 0.9932 - loss: 0.5338 - val_acc: 0.9894 - val_loss: 0.5313 - lr: 3.0000e-04
Epoch 12/5000
262/262 [==============================] - ETA: 0s - acc: 0.9936 - loss: 0.5310
Epoch 00012: val_loss did not improve from 0.53126

Epoch 00012: ReduceLROnPlateau reducing learning rate to 0.0001500000071246177.
262/262 [==============================] - 19s 71ms/step - acc: 0.9936 - loss: 0.5310 - val_acc: 0.9893 - val_loss: 0.5346 - lr: 3.0000e-04
Epoch 13/5000
262/262 [==============================] - ETA: 0s - acc: 0.9956 - loss: 0.5253
Epoch 00013: val_loss improved from 0.53126 to 0.52344, saving model to fold-3.h5
262/262 [==============================] - 21s 81ms/step - acc: 0.9956 - loss: 0.5253 - val_acc: 0.9912 - val_loss: 0.5234 - lr: 1.5000e-04
Epoch 14/5000
262/262 [==============================] - ETA: 0s - acc: 0.9965 - loss: 0.5222
Epoch 00014: val_loss improved from 0.52344 to 0.52137, saving model to fold-3.h5
262/262 [==============================] - 21s 81ms/step - acc: 0.9965 - loss: 0.5222 - val_acc: 0.9920 - val_loss: 0.5214 - lr: 1.5000e-04
Epoch 15/5000
262/262 [==============================] - ETA: 0s - acc: 0.9966 - loss: 0.5212
Epoch 00015: val_loss did not improve from 0.52137

Epoch 00015: ReduceLROnPlateau reducing learning rate to 7.500000356230885e-05.
262/262 [==============================] - 19s 73ms/step - acc: 0.9966 - loss: 0.5212 - val_acc: 0.9919 - val_loss: 0.5236 - lr: 1.5000e-04
Epoch 16/5000
262/262 [==============================] - ETA: 0s - acc: 0.9972 - loss: 0.5192
Epoch 00016: val_loss improved from 0.52137 to 0.52078, saving model to fold-3.h5
262/262 [==============================] - 22s 82ms/step - acc: 0.9972 - loss: 0.5192 - val_acc: 0.9924 - val_loss: 0.5208 - lr: 7.5000e-05
Epoch 17/5000
262/262 [==============================] - ETA: 0s - acc: 0.9973 - loss: 0.5189
Epoch 00017: val_loss did not improve from 0.52078

Epoch 00017: ReduceLROnPlateau reducing learning rate to 3.7500001781154424e-05.
262/262 [==============================] - 20s 75ms/step - acc: 0.9973 - loss: 0.5189 - val_acc: 0.9919 - val_loss: 0.5215 - lr: 7.5000e-05
Epoch 18/5000
262/262 [==============================] - ETA: 0s - acc: 0.9977 - loss: 0.5179
Epoch 00018: val_loss did not improve from 0.52078

Epoch 00018: ReduceLROnPlateau reducing learning rate to 1.8750000890577212e-05.
262/262 [==============================] - 19s 73ms/step - acc: 0.9977 - loss: 0.5179 - val_acc: 0.9923 - val_loss: 0.5209 - lr: 3.7500e-05
Epoch 19/5000
262/262 [==============================] - ETA: 0s - acc: 0.9977 - loss: 0.5170
Epoch 00019: val_loss improved from 0.52078 to 0.51985, saving model to fold-3.h5
262/262 [==============================] - 21s 81ms/step - acc: 0.9977 - loss: 0.5170 - val_acc: 0.9929 - val_loss: 0.5199 - lr: 1.8750e-05
Epoch 20/5000
262/262 [==============================] - ETA: 0s - acc: 0.9982 - loss: 0.5162
Epoch 00020: val_loss improved from 0.51985 to 0.51946, saving model to fold-3.h5
262/262 [==============================] - 20s 78ms/step - acc: 0.9982 - loss: 0.5162 - val_acc: 0.9932 - val_loss: 0.5195 - lr: 1.8750e-05
Epoch 21/5000
262/262 [==============================] - ETA: 0s - acc: 0.9982 - loss: 0.5161
Epoch 00021: val_loss improved from 0.51946 to 0.51925, saving model to fold-3.h5
262/262 [==============================] - 21s 80ms/step - acc: 0.9982 - loss: 0.5161 - val_acc: 0.9929 - val_loss: 0.5192 - lr: 1.8750e-05
Epoch 22/5000
262/262 [==============================] - ETA: 0s - acc: 0.9981 - loss: 0.5161
Epoch 00022: val_loss did not improve from 0.51925

Epoch 00022: ReduceLROnPlateau reducing learning rate to 9.375000445288606e-06.
262/262 [==============================] - 19s 73ms/step - acc: 0.9981 - loss: 0.5161 - val_acc: 0.9929 - val_loss: 0.5198 - lr: 1.8750e-05
Epoch 23/5000
262/262 [==============================] - ETA: 0s - acc: 0.9980 - loss: 0.5163
Epoch 00023: val_loss did not improve from 0.51925

Epoch 00023: ReduceLROnPlateau reducing learning rate to 4.687500222644303e-06.
262/262 [==============================] - 20s 75ms/step - acc: 0.9980 - loss: 0.5163 - val_acc: 0.9929 - val_loss: 0.5195 - lr: 9.3750e-06
Epoch 24/5000
262/262 [==============================] - ETA: 0s - acc: 0.9984 - loss: 0.5153
Epoch 00024: val_loss did not improve from 0.51925

Epoch 00024: ReduceLROnPlateau reducing learning rate to 2.3437501113221515e-06.
262/262 [==============================] - 20s 75ms/step - acc: 0.9984 - loss: 0.5153 - val_acc: 0.9932 - val_loss: 0.5193 - lr: 4.6875e-06
Epoch 25/5000
262/262 [==============================] - ETA: 0s - acc: 0.9983 - loss: 0.5157
Epoch 00025: val_loss improved from 0.51925 to 0.51911, saving model to fold-3.h5
262/262 [==============================] - 22s 83ms/step - acc: 0.9983 - loss: 0.5157 - val_acc: 0.9933 - val_loss: 0.5191 - lr: 2.3438e-06
Epoch 26/5000
262/262 [==============================] - ETA: 0s - acc: 0.9982 - loss: 0.5158
Epoch 00026: val_loss did not improve from 0.51911

Epoch 00026: ReduceLROnPlateau reducing learning rate to 1.1718750556610757e-06.
262/262 [==============================] - 19s 71ms/step - acc: 0.9982 - loss: 0.5158 - val_acc: 0.9929 - val_loss: 0.5192 - lr: 2.3438e-06
Epoch 27/5000
262/262 [==============================] - ETA: 0s - acc: 0.9984 - loss: 0.5152
Epoch 00027: val_loss did not improve from 0.51911

Epoch 00027: ReduceLROnPlateau reducing learning rate to 5.859375278305379e-07.
262/262 [==============================] - 18s 70ms/step - acc: 0.9984 - loss: 0.5152 - val_acc: 0.9931 - val_loss: 0.5191 - lr: 1.1719e-06
Epoch 28/5000
262/262 [==============================] - ETA: 0s - acc: 0.9982 - loss: 0.5153
Epoch 00028: val_loss did not improve from 0.51911

Epoch 00028: ReduceLROnPlateau reducing learning rate to 2.9296876391526894e-07.
262/262 [==============================] - 19s 73ms/step - acc: 0.9982 - loss: 0.5153 - val_acc: 0.9932 - val_loss: 0.5192 - lr: 5.8594e-07
Epoch 29/5000
262/262 [==============================] - ETA: 0s - acc: 0.9982 - loss: 0.5154
Epoch 00029: val_loss did not improve from 0.51911

Epoch 00029: ReduceLROnPlateau reducing learning rate to 1.4648438195763447e-07.
262/262 [==============================] - 19s 74ms/step - acc: 0.9982 - loss: 0.5154 - val_acc: 0.9930 - val_loss: 0.5193 - lr: 2.9297e-07
Epoch 30/5000
262/262 [==============================] - ETA: 0s - acc: 0.9983 - loss: 0.5151
Epoch 00030: val_loss did not improve from 0.51911

Epoch 00030: ReduceLROnPlateau reducing learning rate to 7.324219097881723e-08.
262/262 [==============================] - 19s 74ms/step - acc: 0.9983 - loss: 0.5151 - val_acc: 0.9931 - val_loss: 0.5192 - lr: 1.4648e-07
Epoch 00030: early stopping
Loading best model...
Predicting OOF...
263/263 [==============================] - 8s 30ms/step
Predicting Test...
875/875 [==============================] - 20s 22ms/step
>>>> FOLD 4 Accuracy = 99.3095%

#########################
### FOLD 5
#########################
Generating train data...

100%|██████████| 262/262 [01:21<00:00,  3.22it/s]

Training...
Epoch 1/5000
262/262 [==============================] - ETA: 0s - acc: 0.6603 - loss: 1.3253
Epoch 00001: val_loss improved from inf to 1.71421, saving model to fold-4.h5
262/262 [==============================] - 58s 219ms/step - acc: 0.6603 - loss: 1.3253 - val_acc: 0.4273 - val_loss: 1.7142 - lr: 3.0000e-04
Epoch 2/5000
262/262 [==============================] - ETA: 0s - acc: 0.9180 - loss: 0.7379
Epoch 00002: val_loss improved from 1.71421 to 0.65983, saving model to fold-4.h5
262/262 [==============================] - 21s 81ms/step - acc: 0.9180 - loss: 0.7379 - val_acc: 0.9470 - val_loss: 0.6598 - lr: 3.0000e-04
Epoch 3/5000
262/262 [==============================] - ETA: 0s - acc: 0.9524 - loss: 0.6455
Epoch 00003: val_loss improved from 0.65983 to 0.57376, saving model to fold-4.h5
262/262 [==============================] - 22s 83ms/step - acc: 0.9524 - loss: 0.6455 - val_acc: 0.9757 - val_loss: 0.5738 - lr: 3.0000e-04
Epoch 4/5000
262/262 [==============================] - ETA: 0s - acc: 0.9669 - loss: 0.6057
Epoch 00004: val_loss improved from 0.57376 to 0.55333, saving model to fold-4.h5
262/262 [==============================] - 22s 83ms/step - acc: 0.9669 - loss: 0.6057 - val_acc: 0.9806 - val_loss: 0.5533 - lr: 3.0000e-04
Epoch 5/5000
262/262 [==============================] - ETA: 0s - acc: 0.9760 - loss: 0.5829
Epoch 00005: val_loss improved from 0.55333 to 0.53942, saving model to fold-4.h5
262/262 [==============================] - 21s 81ms/step - acc: 0.9760 - loss: 0.5829 - val_acc: 0.9875 - val_loss: 0.5394 - lr: 3.0000e-04
Epoch 6/5000
262/262 [==============================] - ETA: 0s - acc: 0.9811 - loss: 0.5673
Epoch 00006: val_loss did not improve from 0.53942

Epoch 00006: ReduceLROnPlateau reducing learning rate to 0.0001500000071246177.
262/262 [==============================] - 20s 75ms/step - acc: 0.9811 - loss: 0.5673 - val_acc: 0.9858 - val_loss: 0.5474 - lr: 3.0000e-04
Epoch 7/5000
262/262 [==============================] - ETA: 0s - acc: 0.9858 - loss: 0.5546
Epoch 00007: val_loss improved from 0.53942 to 0.53022, saving model to fold-4.h5
262/262 [==============================] - 22s 83ms/step - acc: 0.9858 - loss: 0.5546 - val_acc: 0.9892 - val_loss: 0.5302 - lr: 1.5000e-04
Epoch 8/5000
262/262 [==============================] - ETA: 0s - acc: 0.9874 - loss: 0.5486
Epoch 00008: val_loss improved from 0.53022 to 0.53018, saving model to fold-4.h5

Epoch 00008: ReduceLROnPlateau reducing learning rate to 7.500000356230885e-05.
262/262 [==============================] - 22s 82ms/step - acc: 0.9874 - loss: 0.5486 - val_acc: 0.9901 - val_loss: 0.5302 - lr: 1.5000e-04
Epoch 9/5000
262/262 [==============================] - ETA: 0s - acc: 0.9892 - loss: 0.5446
Epoch 00009: val_loss improved from 0.53018 to 0.52780, saving model to fold-4.h5
262/262 [==============================] - 21s 82ms/step - acc: 0.9892 - loss: 0.5446 - val_acc: 0.9905 - val_loss: 0.5278 - lr: 7.5000e-05
Epoch 10/5000
262/262 [==============================] - ETA: 0s - acc: 0.9903 - loss: 0.5413
Epoch 00010: val_loss improved from 0.52780 to 0.52694, saving model to fold-4.h5
262/262 [==============================] - 22s 83ms/step - acc: 0.9903 - loss: 0.5413 - val_acc: 0.9900 - val_loss: 0.5269 - lr: 7.5000e-05
Epoch 11/5000
262/262 [==============================] - ETA: 0s - acc: 0.9906 - loss: 0.5399
Epoch 00011: val_loss improved from 0.52694 to 0.52451, saving model to fold-4.h5
262/262 [==============================] - 21s 81ms/step - acc: 0.9906 - loss: 0.5399 - val_acc: 0.9919 - val_loss: 0.5245 - lr: 7.5000e-05
Epoch 12/5000
262/262 [==============================] - ETA: 0s - acc: 0.9911 - loss: 0.5378
Epoch 00012: val_loss improved from 0.52451 to 0.52446, saving model to fold-4.h5

Epoch 00012: ReduceLROnPlateau reducing learning rate to 3.7500001781154424e-05.
262/262 [==============================] - 21s 81ms/step - acc: 0.9911 - loss: 0.5378 - val_acc: 0.9915 - val_loss: 0.5245 - lr: 7.5000e-05
Epoch 13/5000
262/262 [==============================] - ETA: 0s - acc: 0.9926 - loss: 0.5349
Epoch 00013: val_loss improved from 0.52446 to 0.52383, saving model to fold-4.h5
262/262 [==============================] - 22s 83ms/step - acc: 0.9926 - loss: 0.5349 - val_acc: 0.9914 - val_loss: 0.5238 - lr: 3.7500e-05
Epoch 14/5000
262/262 [==============================] - ETA: 0s - acc: 0.9925 - loss: 0.5337
Epoch 00014: val_loss improved from 0.52383 to 0.52332, saving model to fold-4.h5
262/262 [==============================] - 21s 79ms/step - acc: 0.9925 - loss: 0.5337 - val_acc: 0.9914 - val_loss: 0.5233 - lr: 3.7500e-05
Epoch 15/5000
262/262 [==============================] - ETA: 0s - acc: 0.9929 - loss: 0.5329
Epoch 00015: val_loss improved from 0.52332 to 0.52295, saving model to fold-4.h5
262/262 [==============================] - 21s 79ms/step - acc: 0.9929 - loss: 0.5329 - val_acc: 0.9919 - val_loss: 0.5229 - lr: 3.7500e-05
Epoch 16/5000
262/262 [==============================] - ETA: 0s - acc: 0.9936 - loss: 0.5318
Epoch 00016: val_loss did not improve from 0.52295

Epoch 00016: ReduceLROnPlateau reducing learning rate to 1.8750000890577212e-05.
262/262 [==============================] - 20s 76ms/step - acc: 0.9936 - loss: 0.5318 - val_acc: 0.9920 - val_loss: 0.5236 - lr: 3.7500e-05
Epoch 17/5000
262/262 [==============================] - ETA: 0s - acc: 0.9940 - loss: 0.5301
Epoch 00017: val_loss improved from 0.52295 to 0.52280, saving model to fold-4.h5
262/262 [==============================] - 21s 80ms/step - acc: 0.9940 - loss: 0.5301 - val_acc: 0.9918 - val_loss: 0.5228 - lr: 1.8750e-05
Epoch 18/5000
262/262 [==============================] - ETA: 0s - acc: 0.9945 - loss: 0.5297
Epoch 00018: val_loss improved from 0.52280 to 0.52209, saving model to fold-4.h5
262/262 [==============================] - 21s 80ms/step - acc: 0.9945 - loss: 0.5297 - val_acc: 0.9925 - val_loss: 0.5221 - lr: 1.8750e-05
Epoch 19/5000
262/262 [==============================] - ETA: 0s - acc: 0.9945 - loss: 0.5289
Epoch 00019: val_loss did not improve from 0.52209

Epoch 00019: ReduceLROnPlateau reducing learning rate to 9.375000445288606e-06.
262/262 [==============================] - 19s 74ms/step - acc: 0.9945 - loss: 0.5289 - val_acc: 0.9926 - val_loss: 0.5223 - lr: 1.8750e-05
Epoch 20/5000
262/262 [==============================] - ETA: 0s - acc: 0.9949 - loss: 0.5280
Epoch 00020: val_loss did not improve from 0.52209

Epoch 00020: ReduceLROnPlateau reducing learning rate to 4.687500222644303e-06.
262/262 [==============================] - 18s 70ms/step - acc: 0.9949 - loss: 0.5280 - val_acc: 0.9925 - val_loss: 0.5221 - lr: 9.3750e-06
Epoch 21/5000
262/262 [==============================] - ETA: 0s - acc: 0.9949 - loss: 0.5275
Epoch 00021: val_loss improved from 0.52209 to 0.52193, saving model to fold-4.h5
262/262 [==============================] - 21s 81ms/step - acc: 0.9949 - loss: 0.5275 - val_acc: 0.9925 - val_loss: 0.5219 - lr: 4.6875e-06
Epoch 22/5000
262/262 [==============================] - ETA: 0s - acc: 0.9947 - loss: 0.5281
Epoch 00022: val_loss did not improve from 0.52193

Epoch 00022: ReduceLROnPlateau reducing learning rate to 2.3437501113221515e-06.
262/262 [==============================] - 20s 75ms/step - acc: 0.9947 - loss: 0.5281 - val_acc: 0.9923 - val_loss: 0.5221 - lr: 4.6875e-06
Epoch 23/5000
262/262 [==============================] - ETA: 0s - acc: 0.9946 - loss: 0.5278
Epoch 00023: val_loss improved from 0.52193 to 0.52183, saving model to fold-4.h5

Epoch 00023: ReduceLROnPlateau reducing learning rate to 1.1718750556610757e-06.
262/262 [==============================] - 22s 83ms/step - acc: 0.9946 - loss: 0.5278 - val_acc: 0.9925 - val_loss: 0.5218 - lr: 2.3438e-06
Epoch 24/5000
262/262 [==============================] - ETA: 0s - acc: 0.9948 - loss: 0.5273
Epoch 00024: val_loss improved from 0.52183 to 0.52180, saving model to fold-4.h5
262/262 [==============================] - 22s 83ms/step - acc: 0.9948 - loss: 0.5273 - val_acc: 0.9921 - val_loss: 0.5218 - lr: 1.1719e-06
Epoch 25/5000
262/262 [==============================] - ETA: 0s - acc: 0.9950 - loss: 0.5271
Epoch 00025: val_loss did not improve from 0.52180

Epoch 00025: ReduceLROnPlateau reducing learning rate to 5.859375278305379e-07.
262/262 [==============================] - 20s 75ms/step - acc: 0.9950 - loss: 0.5271 - val_acc: 0.9924 - val_loss: 0.5219 - lr: 1.1719e-06
Epoch 26/5000
262/262 [==============================] - ETA: 0s - acc: 0.9951 - loss: 0.5271
Epoch 00026: val_loss did not improve from 0.52180

Epoch 00026: ReduceLROnPlateau reducing learning rate to 2.9296876391526894e-07.
262/262 [==============================] - 19s 73ms/step - acc: 0.9951 - loss: 0.5271 - val_acc: 0.9920 - val_loss: 0.5220 - lr: 5.8594e-07
Epoch 27/5000
262/262 [==============================] - ETA: 0s - acc: 0.9950 - loss: 0.5270
Epoch 00027: val_loss did not improve from 0.52180

Epoch 00027: ReduceLROnPlateau reducing learning rate to 1.4648438195763447e-07.
262/262 [==============================] - 19s 74ms/step - acc: 0.9950 - loss: 0.5270 - val_acc: 0.9925 - val_loss: 0.5219 - lr: 2.9297e-07
Epoch 28/5000
262/262 [==============================] - ETA: 0s - acc: 0.9951 - loss: 0.5267
Epoch 00028: val_loss improved from 0.52180 to 0.52177, saving model to fold-4.h5

Epoch 00028: ReduceLROnPlateau reducing learning rate to 7.324219097881723e-08.
262/262 [==============================] - 23s 87ms/step - acc: 0.9951 - loss: 0.5267 - val_acc: 0.9921 - val_loss: 0.5218 - lr: 1.4648e-07
Epoch 29/5000
262/262 [==============================] - ETA: 0s - acc: 0.9951 - loss: 0.5272
Epoch 00029: val_loss did not improve from 0.52177

Epoch 00029: ReduceLROnPlateau reducing learning rate to 3.662109548940862e-08.
262/262 [==============================] - 20s 77ms/step - acc: 0.9951 - loss: 0.5272 - val_acc: 0.9926 - val_loss: 0.5218 - lr: 7.3242e-08
Epoch 30/5000
262/262 [==============================] - ETA: 0s - acc: 0.9945 - loss: 0.5279
Epoch 00030: val_loss did not improve from 0.52177

Epoch 00030: ReduceLROnPlateau reducing learning rate to 1.831054774470431e-08.
262/262 [==============================] - 20s 75ms/step - acc: 0.9945 - loss: 0.5279 - val_acc: 0.9926 - val_loss: 0.5219 - lr: 3.6621e-08
Epoch 31/5000
262/262 [==============================] - ETA: 0s - acc: 0.9951 - loss: 0.5273
Epoch 00031: val_loss improved from 0.52177 to 0.52169, saving model to fold-4.h5
262/262 [==============================] - 23s 86ms/step - acc: 0.9951 - loss: 0.5273 - val_acc: 0.9925 - val_loss: 0.5217 - lr: 1.8311e-08
Epoch 32/5000
262/262 [==============================] - ETA: 0s - acc: 0.9952 - loss: 0.5275
Epoch 00032: val_loss did not improve from 0.52169

Epoch 00032: ReduceLROnPlateau reducing learning rate to 9.155273872352154e-09.
262/262 [==============================] - 22s 83ms/step - acc: 0.9952 - loss: 0.5275 - val_acc: 0.9923 - val_loss: 0.5219 - lr: 1.8311e-08
Epoch 33/5000
262/262 [==============================] - ETA: 0s - acc: 0.9955 - loss: 0.5264
Epoch 00033: val_loss did not improve from 0.52169

Epoch 00033: ReduceLROnPlateau reducing learning rate to 4.577636936176077e-09.
262/262 [==============================] - 23s 86ms/step - acc: 0.9955 - loss: 0.5264 - val_acc: 0.9924 - val_loss: 0.5219 - lr: 9.1553e-09
Epoch 34/5000
262/262 [==============================] - ETA: 0s - acc: 0.9955 - loss: 0.5270
Epoch 00034: val_loss did not improve from 0.52169

Epoch 00034: ReduceLROnPlateau reducing learning rate to 2.2888184680880386e-09.
262/262 [==============================] - 23s 86ms/step - acc: 0.9955 - loss: 0.5270 - val_acc: 0.9921 - val_loss: 0.5218 - lr: 4.5776e-09
Epoch 35/5000
262/262 [==============================] - ETA: 0s - acc: 0.9948 - loss: 0.5272
Epoch 00035: val_loss did not improve from 0.52169

Epoch 00035: ReduceLROnPlateau reducing learning rate to 1.1444092340440193e-09.
262/262 [==============================] - 22s 85ms/step - acc: 0.9948 - loss: 0.5272 - val_acc: 0.9927 - val_loss: 0.5219 - lr: 2.2888e-09
Epoch 36/5000
262/262 [==============================] - ETA: 0s - acc: 0.9956 - loss: 0.5264
Epoch 00036: val_loss did not improve from 0.52169

Epoch 00036: ReduceLROnPlateau reducing learning rate to 5.722046170220096e-10.
262/262 [==============================] - 22s 85ms/step - acc: 0.9956 - loss: 0.5264 - val_acc: 0.9924 - val_loss: 0.5218 - lr: 1.1444e-09
Epoch 00036: early stopping
Loading best model...
Predicting OOF...
263/263 [==============================] - 9s 35ms/step
Predicting Test...
875/875 [==============================] - 24s 27ms/step
>>>> FOLD 5 Accuracy = 99.2381%

CPU times: user 36min 58s, sys: 5min 3s, total: 42min 1s
Wall time: 1h 15min 19s

# Submitting predictions

On this section, we'll just use `argmax` for getting the predictions from an array `[0.1 0.01 0.3 ... 0.85]` to an integer `0 .. 9` and then generate the CSV file we'll submit.

In [13]:
# Getting predictions output on the demanded format
final_predictions = pd.Series(np.argmax(preds, axis=1), name="Label")

# Generating dataframe on the demanded format
submission = pd.concat([pd.Series(range(1,28001),name = "ImageId"),final_predictions], axis=1)

# Saving file
submission.to_csv("submission.csv",index=False)

# Printing few samples
submission.head()

   ImageId  Label
0        1      2
1        2      0
2        3      9
3        4      0
4        5      3