In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
dataset = pd.read_csv('/kaggle/input/spaceship-titanic/train.csv')

In [3]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8693 entries, 0 to 8692
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   PassengerId   8693 non-null   object
 1   HomePlanet    8492 non-null   object
 2   CryoSleep     8476 non-null   object
 3   Cabin         8494 non-null   object
 4   Destination   8511 non-null   object
 5   Age           8514 non-null   float64
 6   VIP           8490 non-null   object
 7   RoomService   8512 non-null   float64
 8   FoodCourt     8510 non-null   float64
 9   ShoppingMall  8485 non-null   float64
 10  Spa           8510 non-null   float64
 11  VRDeck        8505 non-null   float64
 12  Name          8493 non-null   object
 13  Transported   8693 non-null   bool
dtypes: bool(1), float64(6), object(7)
memory usage: 891.5+ KB

In [4]:
dataset.describe()

,Age,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck
count,8514.000000,8512.000000,8510.000000,8485.000000,8510.000000,8505.000000
mean,28.827930,224.687617,458.077203,173.729169,311.138778,304.854791
std,14.489021,666.717663,1611.489240,604.696458,1136.705535,1145.717189
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,19.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,27.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,38.000000,47.000000,76.000000,27.000000,59.000000,46.000000
max,79.000000,14327.000000,29813.000000,23492.000000,22408.000000,24133.000000

In [5]:
dataset.head(5)

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported
0,0001_01,Europa,False,B/0/P,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,Maham Ofracculy,False
1,0002_01,Earth,False,F/0/S,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,Juanna Vines,True
2,0003_01,Europa,False,A/0/S,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,49.0,Altark Susent,False
3,0003_02,Europa,False,A/0/S,TRAPPIST-1e,33.0,False,0.0,1283.0,371.0,3329.0,193.0,Solam Susent,False
4,0004_01,Earth,False,F/1/S,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,2.0,Willy Santantines,True

In [6]:
dataset.isnull().sum()

PassengerId       0
HomePlanet      201
CryoSleep       217
Cabin           199
Destination     182
Age             179
VIP             203
RoomService     181
FoodCourt       183
ShoppingMall    208
Spa             183
VRDeck          188
Name            200
Transported       0
dtype: int64

ohh damn ,itne sare

In [7]:
dataset['HomePlanet']=dataset.HomePlanet.fillna(dataset.HomePlanet.mode()[0])

In [8]:
dataset.isnull().sum()

PassengerId       0
HomePlanet        0
CryoSleep       217
Cabin           199
Destination     182
Age             179
VIP             203
RoomService     181
FoodCourt       183
ShoppingMall    208
Spa             183
VRDeck          188
Name            200
Transported       0
dtype: int64

In [9]:


from sklearn.preprocessing import LabelEncoder
l1=LabelEncoder()
dataset['CryoSleep']=l1.fit_transform(dataset['CryoSleep'])
dataset['Cabin']=l1.fit_transform(dataset['Cabin'])
dataset['VIP']=l1.fit_transform(dataset['VIP'])

In [10]:
dataset.isnull().sum()

PassengerId       0
HomePlanet        0
CryoSleep         0
Cabin             0
Destination     182
Age             179
VIP               0
RoomService     181
FoodCourt       183
ShoppingMall    208
Spa             183
VRDeck          188
Name            200
Transported       0
dtype: int64

In [11]:
dataset['Destination'].max

<bound method NDFrame._add_numeric_operations.<locals>.max of 0         TRAPPIST-1e
1         TRAPPIST-1e
2         TRAPPIST-1e
3         TRAPPIST-1e
4         TRAPPIST-1e
            ...
8688      55 Cancri e
8689    PSO J318.5-22
8690      TRAPPIST-1e
8691      55 Cancri e
8692      TRAPPIST-1e
Name: Destination, Length: 8693, dtype: object>

In [12]:
# print(dataset['CryoSleep'].mode())
# print(dataset['CryoSleep'].mean())
# print(dataset['CryoSleep'].median())
dataset['CryoSleep'].fillna(value=dataset['CryoSleep'].mean(),inplace=True)
dataset['Destination'].fillna(value='TRAPPIST-1e',inplace=True)
dataset['Age'].fillna(value=dataset['Age'].mean(),inplace=True)
dataset['RoomService'].fillna(value=dataset['RoomService'].mean(),inplace=True)
dataset['FoodCourt'].fillna(value=dataset['FoodCourt'].mean(),inplace=True)
dataset['ShoppingMall'].fillna(value=dataset['ShoppingMall'].mean(),inplace=True)
dataset['Spa'].fillna(value=dataset['Spa'].mean(),inplace=True)
dataset['VRDeck'].fillna(value=dataset['VRDeck'].mean(),inplace=True)

In [13]:
dataset.isnull().sum()

PassengerId       0
HomePlanet        0
CryoSleep         0
Cabin             0
Destination       0
Age               0
VIP               0
RoomService       0
FoodCourt         0
ShoppingMall      0
Spa               0
VRDeck            0
Name            200
Transported       0
dtype: int64

finalllyyy;
Now will drop some columns

In [14]:
dataset.drop(columns=['PassengerId','Cabin','Name'],axis=1,inplace=True)

In [15]:
dataset.head(10)

,HomePlanet,CryoSleep,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Transported
0,Europa,0,TRAPPIST-1e,39.0,0,0.0,0.0,0.0,0.0,0.000000,False
1,Earth,0,TRAPPIST-1e,24.0,0,109.0,9.0,25.0,549.0,44.000000,True
2,Europa,0,TRAPPIST-1e,58.0,1,43.0,3576.0,0.0,6715.0,49.000000,False
3,Europa,0,TRAPPIST-1e,33.0,0,0.0,1283.0,371.0,3329.0,193.000000,False
4,Earth,0,TRAPPIST-1e,16.0,0,303.0,70.0,151.0,565.0,2.000000,True
5,Earth,0,PSO J318.5-22,44.0,0,0.0,483.0,0.0,291.0,0.000000,True
6,Earth,0,TRAPPIST-1e,26.0,0,42.0,1539.0,3.0,0.0,0.000000,True
7,Earth,1,TRAPPIST-1e,28.0,0,0.0,0.0,0.0,0.0,304.854791,True
8,Earth,0,TRAPPIST-1e,35.0,0,0.0,785.0,17.0,216.0,0.000000,True
9,Europa,1,55 Cancri e,14.0,0,0.0,0.0,0.0,0.0,0.000000,True

In [16]:
x = dataset.iloc[: ,:-2].values
y = dataset.iloc[: ,-1].values

In [17]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [18]:
# x.drop(columns=[3],axis=1,inplace=True)
x = np.delete(x, 3, axis=1)

In [19]:
x[0, :]

array([1.0, 0.0, 0.0, 'TRAPPIST-1e', 39.0, 0, 0.0, 0.0, 0.0, 0.0],
      dtype=object)

In [20]:
x.view()

array([[1.0, 0.0, 0.0, ..., 0.0, 0.0, 0.0],
       [1.0, 0.0, 0.0, ..., 9.0, 25.0, 549.0],
       [1.0, 0.0, 0.0, ..., 3576.0, 0.0, 6715.0],
       ...,
       [1.0, 0.0, 0.0, ..., 0.0, 1872.0, 1.0],
       [1.0, 0.0, 0.0, ..., 1049.0, 0.0, 353.0],
       [1.0, 0.0, 0.0, ..., 4688.0, 0.0, 0.0]], dtype=object)

In [21]:
x = pd.DataFrame(x)

In [22]:
x.head(5)

     0    1    2            3     4  5      6       7      8       9
0  1.0  0.0  0.0  TRAPPIST-1e  39.0  0    0.0     0.0    0.0     0.0
1  1.0  0.0  0.0  TRAPPIST-1e  24.0  0  109.0     9.0   25.0   549.0
2  1.0  0.0  0.0  TRAPPIST-1e  58.0  1   43.0  3576.0    0.0  6715.0
3  1.0  0.0  0.0  TRAPPIST-1e  33.0  0    0.0  1283.0  371.0  3329.0
4  1.0  0.0  0.0  TRAPPIST-1e  16.0  0  303.0    70.0  151.0   565.0

In [23]:
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [3])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [24]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [25]:
x[0:3,:]

array([[0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 39.0, 0, 0.0, 0.0, 0.0, 0.0],
       [0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 24.0, 0, 109.0, 9.0, 25.0, 549.0],
       [0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 58.0, 1, 43.0, 3576.0, 0.0, 6715.0]],
      dtype=object)

In [26]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 1)

In [27]:
from sklearn.svm import SVR
regressor = SVR(kernel = 'rbf')

In [28]:
regressor.fit(X_train, y_train)
y_pred = regressor.predict(X_test)

In [29]:
from sklearn.metrics import mean_squared_error, r2_score

In [30]:
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

In [31]:
mse

0.19692152834623505

In [32]:
r2

0.21158155235348797