In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/titanic/train.csv
/kaggle/input/titanic/test.csv
/kaggle/input/titanic/gender_submission.csv

# Load The Data

In [2]:
#Read Training Data
train_data=pd.read_csv('../input/titanic/train.csv')
#view the first 5 row
train_data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [3]:
#view the Last 5 row from Training data
train_data.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [4]:
#Read the Testting Data
test_data = pd.read_csv('../input/titanic/test.csv')
#view the first 5 row from the test Data
test_data.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [5]:
#View the last 5 row from the test data
test_data.tail()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
413,1305,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

# the rate of women who survived

In [6]:
#print the rate of women who survived 
women = train_data.loc[train_data.Sex=='female']["Survived"]
rate_women = sum(women)/len(women)
print('The Rate of Women who Survived is : ',rate_women , '%')

The Rate of Women who Survived is :  0.7420382165605095 %

# the rate of Men who survived

In [7]:
#print the rate of Men who survived
Men = train_data.loc[train_data.Sex=='male']["Survived"]
rate_men = sum(Men)/len(Men)
print('The Rate of Men who Survived is :' , rate_men , '%')

The Rate of Men who Survived is : 0.18890814558058924 %

# Fit The Model

In [8]:
from sklearn.ensemble import RandomForestClassifier
# y is training data target
y=train_data["Survived"]
features = ["Pclass", "Sex", "SibSp", "Parch"]
# X is training data features
X = pd.get_dummies(train_data[features])
X_test = pd.get_dummies(test_data[features])

In [9]:
#N_estimators is the numer of trees
#Max_depth is the deepth of Requared
R_F_C = RandomForestClassifier(n_estimators=100 , max_depth=5 , random_state=1)

#fitting the model
R_F_C.fit(X,y)

RandomForestClassifier(max_depth=5, random_state=1)

# Predictions

In [10]:
predictions = R_F_C.predict(X_test)

# print PassengerId and prediction Survived or not

In [11]:
output = pd.DataFrame({'PassengerId':test_data.PassengerId , 'Survived':predictions})

In [12]:
print(output)

     PassengerId  Survived
0            892         0
1            893         1
2            894         0
3            895         0
4            896         1
..           ...       ...
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]

# print PassengerId , sex male or female and prediction Survived or not

In [13]:
output2 = pd.DataFrame({'PassengerId':test_data.PassengerId , 'Sex':test_data.Sex , 'Survived':predictions})

In [14]:
output2

     PassengerId     Sex  Survived
0            892    male         0
1            893  female         1
2            894    male         0
3            895    male         0
4            896  female         1
..           ...     ...       ...
413         1305    male         0
414         1306  female         1
415         1307    male         0
416         1308    male         0
417         1309    male         0

[418 rows x 3 columns]

In [15]:
print(output2)

     PassengerId     Sex  Survived
0            892    male         0
1            893  female         1
2            894    male         0
3            895    male         0
4            896  female         1
..           ...     ...       ...
413         1305    male         0
414         1306  female         1
415         1307    male         0
416         1308    male         0
417         1309    male         0

[418 rows x 3 columns]

In [16]:
output.to_csv('my_submission.csv' , index=False)
print("Your submission was successfully saved!")

Your submission was successfully saved!