#  Predicting survival of passengers using Decision Tree

### Importing all the necessary libraries

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
from pandas import DataFrame

### Reading the given datasets

In [2]:
titanic_train = pd.read_csv('../input/titanic/train.csv') 
titanic_test = pd.read_csv('../input/titanic/test.csv')
test_ids = titanic_test['PassengerId']

In [3]:
titanic_train.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

### Filling all the NaN values

In [4]:
titanic_train = titanic_train.drop(['Name','Ticket','Fare','Cabin'],axis='columns')
cols = ['SibSp','Parch','Age']
for col in cols: 
    titanic_train[col].fillna(titanic_train[col].median(),inplace=True)
    
titanic_train.Embarked.fillna('U',inplace=True)
titanic_train.head()

   PassengerId  Survived  Pclass     Sex   Age  SibSp  Parch Embarked
0            1         0       3    male  22.0      1      0        S
1            2         1       1  female  38.0      1      0        C
2            3         1       3  female  26.0      0      0        S
3            4         1       1  female  35.0      1      0        S
4            5         0       3    male  35.0      0      0        S

In [5]:
titanic_test = titanic_test.drop(['Name','Ticket','Fare','Cabin'],axis='columns')
cols = ['SibSp','Parch','Age']
for col in cols: 
    titanic_test[col].fillna(titanic_test[col].median(),inplace=True)
    
titanic_test.Embarked.fillna('U',inplace=True)
titanic_test.head()

   PassengerId  Pclass     Sex   Age  SibSp  Parch Embarked
0          892       3    male  34.5      0      0        Q
1          893       3  female  47.0      1      0        S
2          894       2    male  62.0      0      0        Q
3          895       3    male  27.0      0      0        S
4          896       3  female  22.0      1      1        S

### Using LabelEncoder to convert strings into numbers

In [6]:
from sklearn.preprocessing import LabelEncoder

In [7]:
le_sex = LabelEncoder()
le_embarked = LabelEncoder()

In [8]:
titanic_train['Sex']= le_sex.fit_transform(titanic_train['Sex'])
titanic_train['Embarked']= le_embarked.fit_transform(titanic_train['Embarked'])

In [9]:
titanic_train.head()

   PassengerId  Survived  Pclass  Sex   Age  SibSp  Parch  Embarked
0            1         0       3    1  22.0      1      0         2
1            2         1       1    0  38.0      1      0         0
2            3         1       3    0  26.0      0      0         2
3            4         1       1    0  35.0      1      0         2
4            5         0       3    1  35.0      0      0         2

In [10]:
titanic_test['Sex']= le_sex.fit_transform(titanic_test['Sex'])
titanic_test['Embarked']= le_embarked.fit_transform(titanic_test['Embarked'])

In [11]:
y_train = titanic_train['Survived']
x_train = titanic_train.drop('Survived',axis='columns')
x_train

     PassengerId  Pclass  Sex   Age  SibSp  Parch  Embarked
0              1       3    1  22.0      1      0         2
1              2       1    0  38.0      1      0         0
2              3       3    0  26.0      0      0         2
3              4       1    0  35.0      1      0         2
4              5       3    1  35.0      0      0         2
..           ...     ...  ...   ...    ...    ...       ...
886          887       2    1  27.0      0      0         2
887          888       1    0  19.0      0      0         2
888          889       3    0  28.0      1      2         2
889          890       1    1  26.0      0      0         0
890          891       3    1  32.0      0      0         1

[891 rows x 7 columns]

### Predicting the survival using Decision Tree

In [12]:
from sklearn import tree

In [13]:
model = tree.DecisionTreeClassifier(criterion='entropy',random_state=0)

In [14]:
model.fit(x_train,y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [15]:
submission_pred = model.predict(titanic_test)

### Converting results into csv file

In [16]:
df = DataFrame(test_ids,columns=['PassengerId'])
df['Survived'] = submission_pred
df.info

<bound method DataFrame.info of      PassengerId  Survived
0            892         0
1            893         0
2            894         0
3            895         0
4            896         0
..           ...       ...
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]>

In [17]:
df.to_csv('submission.csv',index=False)