# Import Libaries

In [1]:
import numpy as np
import pandas as pd

# Loading Training dataset

In [2]:
train_data=pd.read_csv("/kaggle/input/spaceship-titanic/train.csv")
train_data

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported
0,0001_01,Europa,False,B/0/P,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,Maham Ofracculy,False
1,0002_01,Earth,False,F/0/S,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,Juanna Vines,True
2,0003_01,Europa,False,A/0/S,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,49.0,Altark Susent,False
3,0003_02,Europa,False,A/0/S,TRAPPIST-1e,33.0,False,0.0,1283.0,371.0,3329.0,193.0,Solam Susent,False
4,0004_01,Earth,False,F/1/S,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,2.0,Willy Santantines,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8688,9276_01,Europa,False,A/98/P,55 Cancri e,41.0,True,0.0,6819.0,0.0,1643.0,74.0,Gravior Noxnuther,False
8689,9278_01,Earth,True,G/1499/S,PSO J318.5-22,18.0,False,0.0,0.0,0.0,0.0,0.0,Kurta Mondalley,False
8690,9279_01,Earth,False,G/1500/S,TRAPPIST-1e,26.0,False,0.0,0.0,1872.0,1.0,0.0,Fayey Connon,True
8691,9280_01,Europa,False,E/608/S,55 Cancri e,32.0,False,0.0,1049.0,0.0,353.0,3235.0,Celeon Hontichre,False
8692,9280_02,Europa,False,E/608/S,TRAPPIST-1e,44.0,False,126.0,4688.0,0.0,0.0,12.0,Propsh Hontichre,True

# Slicing Training dataset

In [3]:
x_data=train_data.iloc[:,:-1]
x_data

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name
0,0001_01,Europa,False,B/0/P,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,Maham Ofracculy
1,0002_01,Earth,False,F/0/S,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,Juanna Vines
2,0003_01,Europa,False,A/0/S,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,49.0,Altark Susent
3,0003_02,Europa,False,A/0/S,TRAPPIST-1e,33.0,False,0.0,1283.0,371.0,3329.0,193.0,Solam Susent
4,0004_01,Earth,False,F/1/S,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,2.0,Willy Santantines
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8688,9276_01,Europa,False,A/98/P,55 Cancri e,41.0,True,0.0,6819.0,0.0,1643.0,74.0,Gravior Noxnuther
8689,9278_01,Earth,True,G/1499/S,PSO J318.5-22,18.0,False,0.0,0.0,0.0,0.0,0.0,Kurta Mondalley
8690,9279_01,Earth,False,G/1500/S,TRAPPIST-1e,26.0,False,0.0,0.0,1872.0,1.0,0.0,Fayey Connon
8691,9280_01,Europa,False,E/608/S,55 Cancri e,32.0,False,0.0,1049.0,0.0,353.0,3235.0,Celeon Hontichre
8692,9280_02,Europa,False,E/608/S,TRAPPIST-1e,44.0,False,126.0,4688.0,0.0,0.0,12.0,Propsh Hontichre

# Converting string data inti numeric data

In [4]:
from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()

In [5]:
for col in train_data.columns:
    if train_data[col].dtype == object:
        train_data[col] = train_data[col].astype(str)
        d1=train_data[col].unique()
        d2=d1[-2]
        
        train_data[col]=train_data[col].fillna(d2)
        train_data[col]=lb.fit_transform(train_data[col])
    elif train_data[col].dtype == float or train_data[col].dtype == int:
        m1=train_data[col].mean()
        m1=round(m1)
        train_data[col]=train_data[col].fillna(m1)
        
print(train_data)

      PassengerId  HomePlanet  CryoSleep  Cabin  Destination   Age  VIP  \
0               0           1          0    149            2  39.0    0
1               1           0          0   2184            2  24.0    0
2               2           1          0      1            2  58.0    1
3               3           1          0      1            2  33.0    0
4               4           0          0   2186            2  16.0    0
...           ...         ...        ...    ...          ...   ...  ...
8688         8688           1          0    146            0  41.0    1
8689         8689           0          1   5280            1  18.0    0
8690         8690           0          0   5285            2  26.0    0
8691         8691           1          0   2131            0  32.0    0
8692         8692           1          0   2131            2  44.0    0

      RoomService  FoodCourt  ShoppingMall     Spa  VRDeck  Name  Transported
0             0.0        0.0           0.0     0.0     0.0  5252        False
1           109.0        9.0          25.0   549.0    44.0  4502         True
2            43.0     3576.0           0.0  6715.0    49.0   457        False
3             0.0     1283.0         371.0  3329.0   193.0  7149        False
4           303.0       70.0         151.0   565.0     2.0  8319         True
...           ...        ...           ...     ...     ...   ...          ...
8688          0.0     6819.0           0.0  1643.0    74.0  3524        False
8689          0.0        0.0           0.0     0.0     0.0  4780        False
8690          0.0        0.0        1872.0     1.0     0.0  3002         True
8691          0.0     1049.0           0.0   353.0  3235.0  1596        False
8692        126.0     4688.0           0.0     0.0    12.0  6380         True

[8693 rows x 14 columns]

In [6]:
del train_data["Transported"]

In [7]:
train_data

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name
0,0,1,0,149,2,39.0,0,0.0,0.0,0.0,0.0,0.0,5252
1,1,0,0,2184,2,24.0,0,109.0,9.0,25.0,549.0,44.0,4502
2,2,1,0,1,2,58.0,1,43.0,3576.0,0.0,6715.0,49.0,457
3,3,1,0,1,2,33.0,0,0.0,1283.0,371.0,3329.0,193.0,7149
4,4,0,0,2186,2,16.0,0,303.0,70.0,151.0,565.0,2.0,8319
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8688,8688,1,0,146,0,41.0,1,0.0,6819.0,0.0,1643.0,74.0,3524
8689,8689,0,1,5280,1,18.0,0,0.0,0.0,0.0,0.0,0.0,4780
8690,8690,0,0,5285,2,26.0,0,0.0,0.0,1872.0,1.0,0.0,3002
8691,8691,1,0,2131,0,32.0,0,0.0,1049.0,0.0,353.0,3235.0,1596
8692,8692,1,0,2131,2,44.0,0,126.0,4688.0,0.0,0.0,12.0,6380

# Loading Test data

In [8]:
test_data=pd.read_csv("/kaggle/input/spaceship-titanic/test.csv")
test_data

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name
0,0013_01,Earth,True,G/3/S,TRAPPIST-1e,27.0,False,0.0,0.0,0.0,0.0,0.0,Nelly Carsoning
1,0018_01,Earth,False,F/4/S,TRAPPIST-1e,19.0,False,0.0,9.0,0.0,2823.0,0.0,Lerome Peckers
2,0019_01,Europa,True,C/0/S,55 Cancri e,31.0,False,0.0,0.0,0.0,0.0,0.0,Sabih Unhearfus
3,0021_01,Europa,False,C/1/S,TRAPPIST-1e,38.0,False,0.0,6652.0,0.0,181.0,585.0,Meratz Caltilter
4,0023_01,Earth,False,F/5/S,TRAPPIST-1e,20.0,False,10.0,0.0,635.0,0.0,0.0,Brence Harperez
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4272,9266_02,Earth,True,G/1496/S,TRAPPIST-1e,34.0,False,0.0,0.0,0.0,0.0,0.0,Jeron Peter
4273,9269_01,Earth,False,NaN,TRAPPIST-1e,42.0,False,0.0,847.0,17.0,10.0,144.0,Matty Scheron
4274,9271_01,Mars,True,D/296/P,55 Cancri e,NaN,False,0.0,0.0,0.0,0.0,0.0,Jayrin Pore
4275,9273_01,Europa,False,D/297/P,NaN,NaN,False,0.0,2680.0,0.0,0.0,523.0,Kitakan Conale
4276,9277_01,Earth,True,G/1498/S,PSO J318.5-22,43.0,False,0.0,0.0,0.0,0.0,0.0,Lilace Leonzaley

In [9]:
for col in test_data.columns:
    if test_data[col].dtype == object:
        test_data[col] = test_data[col].astype(str)
        d1=test_data[col].unique()
        d2=d1[-2]
        
        test_data[col]=test_data[col].fillna(d2)
        test_data[col]=lb.fit_transform(test_data[col])
    elif test_data[col].dtype == float or test_data[col].dtype == int:
        m1=test_data[col].mean()
        m1=round(m1)
        test_data[col]=test_data[col].fillna(m1)
        
print(test_data)

      PassengerId  HomePlanet  CryoSleep  Cabin  Destination   Age  VIP  \
0               0           0          1   2784            2  27.0    0
1               1           0          0   1867            2  19.0    0
2               2           1          1    257            0  31.0    0
3               3           1          0    259            2  38.0    0
4               4           0          0   1940            2  20.0    0
...           ...         ...        ...    ...          ...   ...  ...
4272         4272           0          1   2679            2  34.0    0
4273         4273           0          0   3265            2  42.0    0
4274         4274           2          1    602            0  29.0    0
4275         4275           1          0    603            3  29.0    0
4276         4276           0          1   2680            1  43.0    0

      RoomService  FoodCourt  ShoppingMall     Spa  VRDeck  Name
0             0.0        0.0           0.0     0.0     0.0  2912
1             0.0        9.0           0.0  2823.0     0.0  2406
2             0.0        0.0           0.0     0.0     0.0  3376
3             0.0     6652.0           0.0   181.0   585.0  2711
4            10.0        0.0         635.0     0.0     0.0   668
...           ...        ...           ...     ...     ...   ...
4272          0.0        0.0           0.0     0.0     0.0  2105
4273          0.0      847.0          17.0    10.0   144.0  2654
4274          0.0        0.0           0.0     0.0     0.0  2085
4275          0.0     2680.0           0.0     0.0   523.0  2327
4276          0.0        0.0           0.0     0.0     0.0  2439

[4277 rows x 13 columns]

In [10]:
test_data

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name
0,0,0,1,2784,2,27.0,0,0.0,0.0,0.0,0.0,0.0,2912
1,1,0,0,1867,2,19.0,0,0.0,9.0,0.0,2823.0,0.0,2406
2,2,1,1,257,0,31.0,0,0.0,0.0,0.0,0.0,0.0,3376
3,3,1,0,259,2,38.0,0,0.0,6652.0,0.0,181.0,585.0,2711
4,4,0,0,1940,2,20.0,0,10.0,0.0,635.0,0.0,0.0,668
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4272,4272,0,1,2679,2,34.0,0,0.0,0.0,0.0,0.0,0.0,2105
4273,4273,0,0,3265,2,42.0,0,0.0,847.0,17.0,10.0,144.0,2654
4274,4274,2,1,602,0,29.0,0,0.0,0.0,0.0,0.0,0.0,2085
4275,4275,1,0,603,3,29.0,0,0.0,2680.0,0.0,0.0,523.0,2327
4276,4276,0,1,2680,1,43.0,0,0.0,0.0,0.0,0.0,0.0,2439

In [11]:
train_data.info()
test_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8693 entries, 0 to 8692
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   PassengerId   8693 non-null   int64
 1   HomePlanet    8693 non-null   int64
 2   CryoSleep     8693 non-null   int64
 3   Cabin         8693 non-null   int64
 4   Destination   8693 non-null   int64
 5   Age           8693 non-null   float64
 6   VIP           8693 non-null   int64
 7   RoomService   8693 non-null   float64
 8   FoodCourt     8693 non-null   float64
 9   ShoppingMall  8693 non-null   float64
 10  Spa           8693 non-null   float64
 11  VRDeck        8693 non-null   float64
 12  Name          8693 non-null   int64
dtypes: float64(6), int64(7)
memory usage: 883.0 KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4277 entries, 0 to 4276
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   PassengerId   4277 non-null   int64
 1   HomePlanet    4277 non-null   int64
 2   CryoSleep     4277 non-null   int64
 3   Cabin         4277 non-null   int64
 4   Destination   4277 non-null   int64
 5   Age           4277 non-null   float64
 6   VIP           4277 non-null   int64
 7   RoomService   4277 non-null   float64
 8   FoodCourt     4277 non-null   float64
 9   ShoppingMall  4277 non-null   float64
 10  Spa           4277 non-null   float64
 11  VRDeck        4277 non-null   float64
 12  Name          4277 non-null   int64
dtypes: float64(6), int64(7)
memory usage: 434.5 KB

# Loading Training dataset

In [12]:
train_data1=pd.read_csv("/kaggle/input/spaceship-titanic/train.csv")
train_data1

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported
0,0001_01,Europa,False,B/0/P,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,Maham Ofracculy,False
1,0002_01,Earth,False,F/0/S,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,Juanna Vines,True
2,0003_01,Europa,False,A/0/S,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,49.0,Altark Susent,False
3,0003_02,Europa,False,A/0/S,TRAPPIST-1e,33.0,False,0.0,1283.0,371.0,3329.0,193.0,Solam Susent,False
4,0004_01,Earth,False,F/1/S,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,2.0,Willy Santantines,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8688,9276_01,Europa,False,A/98/P,55 Cancri e,41.0,True,0.0,6819.0,0.0,1643.0,74.0,Gravior Noxnuther,False
8689,9278_01,Earth,True,G/1499/S,PSO J318.5-22,18.0,False,0.0,0.0,0.0,0.0,0.0,Kurta Mondalley,False
8690,9279_01,Earth,False,G/1500/S,TRAPPIST-1e,26.0,False,0.0,0.0,1872.0,1.0,0.0,Fayey Connon,True
8691,9280_01,Europa,False,E/608/S,55 Cancri e,32.0,False,0.0,1049.0,0.0,353.0,3235.0,Celeon Hontichre,False
8692,9280_02,Europa,False,E/608/S,TRAPPIST-1e,44.0,False,126.0,4688.0,0.0,0.0,12.0,Propsh Hontichre,True

# Data Preprocessing

In [13]:
from sklearn.preprocessing import LabelEncoder
lb1=LabelEncoder()
train_data1["Transported"]=lb1.fit_transform(train_data1["Transported"])

In [14]:
train_data1["Transported"]

0       0
1       1
2       0
3       0
4       1
       ..
8688    0
8689    0
8690    1
8691    0
8692    1
Name: Transported, Length: 8693, dtype: int64

# Slicing  Training Dataset

In [15]:
x=train_data.iloc[:,:].values
y=train_data1.iloc[:,-1].values
y

array([0, 1, 0, ..., 1, 0, 1])

In [16]:
test_std=test_data.iloc[:,:].values

# Using Standard Scaler

In [17]:
from sklearn.preprocessing import StandardScaler
std=StandardScaler()
x=std.fit_transform(x)
test_std=std.fit_transform(test_std)

In [18]:
test_std.shape

(4277, 13)

In [19]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=11)

# Using Logistic regression

In [20]:
from sklearn.linear_model import LogisticRegression 
log=LogisticRegression()
log.fit(x_train,y_train)

y_pred=log.predict(x_test)
y_pred

from sklearn.metrics import accuracy_score
ac=accuracy_score(y_test,y_pred)*100
ac

78.83841288096608

# Using Support Vector Machine(SVM)

In [21]:
from sklearn.svm import SVC
svc1=SVC(kernel='linear',random_state=11)
svc1.fit(x_train,y_train)

y_pred1=svc1.predict(x_test)
y_pred1

from sklearn.metrics import accuracy_score
ac1=accuracy_score(y_test,y_pred1)*100
print(ac1)

80.27602070155262

In [22]:
from sklearn.svm import SVC
svc2=SVC(kernel='linear',random_state=11)
svc2.fit(x,y)

final_pred=svc2.predict(test_std)
final_pred

array([1, 0, 1, ..., 1, 1, 1])

In [23]:
final=[]
for x in final_pred:
    if x==0:
        final.append(False)
    else:
        final.append(True)

In [24]:
final1=pd.read_csv(r"/kaggle/input/spaceship-titanic/test.csv")
final1.insert(1,"Transported",final)
final2=final1.iloc[:,[0,1]]
final2

     PassengerId  Transported
0        0013_01         True
1        0018_01        False
2        0019_01         True
3        0021_01         True
4        0023_01         True
...          ...          ...
4272     9266_02         True
4273     9269_01         True
4274     9271_01         True
4275     9273_01         True
4276     9277_01         True

[4277 rows x 2 columns]

In [25]:
import os
final2.to_csv(r'sample_submission.csv',index=False)


from IPython.display import FileLink
FileLink(r'sample_submission.csv')

/kaggle/working/sample_submission.csv