# Design Patterns - Complete guide

![](https://bgasparotto.com/wp-content/uploads/2016/11/design-patterns-logo-2.png)


Design patterns play a crucial role in **software development**, including **data science projects**. They are **reusable solutions to commonly occurring problems** and provide a structured approach to designing and implementing software systems. While design patterns are traditionally associated with object-oriented programming, their principles can be applied to data science projects as well.

Here are some reasons why using design patterns in data science projects is important:

* **Structured Approach**: Data science projects involve various components, such as data extraction, preprocessing, modeling, evaluation, and deployment. Design patterns offer a structured approach to tackle these different stages, ensuring that each component is designed and implemented consistently and efficiently.

* **Reusability**: Design patterns promote code reusability, which is crucial in data science. By encapsulating common functionalities into reusable patterns, you can save time and effort by leveraging existing solutions. This also enhances collaboration among team members as they can easily understand and work with well-known design patterns.

* **Maintainability**: Data science projects often involve complex data pipelines and models. Design patterns provide clear and modular architectures that make the codebase more maintainable. When changes or updates are required, it is easier to locate and modify specific components without impacting the entire system.

* **Scalability**: As data science projects grow in complexity and volume, scalability becomes a critical consideration. Design patterns, such as the Factory pattern or the Strategy pattern, enable the system to adapt to changing requirements and handle larger datasets without significant code modifications.

* **Separation of Concerns**: Data science projects involve multiple concerns, such as data access, feature engineering, model training, and visualization. Design patterns, like the Model-View-Controller (MVC) pattern or the Pipeline pattern, promote separation of concerns, allowing you to focus on each aspect independently. This separation enhances code organization and improves maintainability.

* **Best Practices**: Design patterns embody well-established best practices and design principles. By using design patterns, you leverage the collective experience of software engineers and data scientists who have encountered similar problems in the past. This helps you avoid common pitfalls and adopt proven solutions.

* **Code Understandability**: Design patterns provide a common language and structure that facilitates code understandability among team members. When working on collaborative data science projects, using design patterns can help everyone involved to better comprehend the system architecture and design choices.


In this tutorial, we will explore the **Gang of Four (GoF)** design patterns, **a collection of proven solutions to common software design problems**. The figure below shows how these patterns are organized and applied to the class and objects.

![](https://www.gofpatterns.com/images/gofPatterns_sitemap.jpg)

*source: https://www.gofpatterns.com/images/gofPatterns_sitemap.jpg

Throughout this tutorial, we will cover all three categories of **GoF design patterns**: creational patterns, structural patterns, and behavioral patterns. You will learn about each pattern's purpose, how it addresses specific design challenges, and its implementation details. By the end of this tutorial, you will have a solid understanding of the GoF design patterns and how to apply them effectively in your own software projects. 

**So let's dive in and unlock the power of these design patterns to enhance your software design skills!**


## Who visited this notebook liked the notebooks below:

* **Code quality - Clearly explained**
[link](https://www.kaggle.com/code/leodaniel/code-quality-clearly-explained)

* **SQLAlchemy - Quick Guide**
[link](https://www.kaggle.com/code/leodaniel/sqlalchemy-quick-guide)

* **SQL Quick Guide** 
[link](https://www.kaggle.com/code/leodaniel/sql-quick-guide/notebook)

* **ROC Curve - Simply explained**
[link](https://www.kaggle.com/code/leodaniel/roc-curve-simply-explained)

* **Machine Learning 101 - From zero to hero!** 
[link](https://www.kaggle.com/code/leodaniel/machine-learning-101-from-zero-to-hero)

* **Statistics 101 - A simple approach**
[link](https://www.kaggle.com/code/leodaniel/statistics-101-a-simple-approach)

* **k-NN regression clearly explained**
[link](https://www.kaggle.com/code/leodaniel/k-nn-regression-clearly-explained)

* **K-Means clearly explained**
[link](https://www.kaggle.com/code/leodaniel/k-means-clearly-explained)

* **Hypothesis Test - Clear Explained**
[link](https://www.kaggle.com/code/leodaniel/hypothesis-test-clear-explained)

* **My heart will go on...**
[link](https://www.kaggle.com/code/leodaniel/my-heart-will-go-on)


## Please upvote me if you like, ok? (this is really really important to me)

In [1]:
import numpy as np
import pandas as pd
import pandas as pd
import os
from abc import ABC, abstractmethod
from IPython.display import display
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from copy import deepcopy

/opt/conda/lib/python3.10/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.5
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"

In [2]:
titanic_data = pd.read_csv('/kaggle/input/titanic/train.csv')
print(titanic_data.shape)
titanic_data.head()

(891, 12)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [3]:
titanic_data.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [4]:
titanic_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

# 01. Creational - Factory Method

## 1. Problem:
In software development, you often encounter situations where you need to create objects without specifying their concrete classes. This can arise when you want to decouple the client code from the specific object creation logic or when you need to support multiple object variations or families. The problem is that the client code becomes tightly coupled to the concrete classes, making it difficult to extend or change the object creation process.

## 2. Solution:
The Factory Method design pattern provides a solution by defining an interface or abstract class for creating objects, but delegates the actual object creation to subclasses. Instead of the client code directly instantiating the objects, it relies on the factory method defined in the interface or abstract class. Each subclass can implement the factory method to create the desired objects, encapsulating the object creation logic and allowing for flexibility and extensibility.

## 3. Why it works:
The Factory Method design pattern works because it adheres to the "open-closed principle" - the client code is open for extension (by adding new subclasses) but closed for modification (as it doesn't need to change when new objects are introduced). It allows the client code to depend on abstractions rather than concrete classes, promoting loose coupling and flexibility in object creation.

## Advantages:

* Flexibility: The Factory Method pattern allows for the addition of new object types or variations without modifying the existing client code. New subclasses can be created to handle specific object creation scenarios, providing flexibility in extending the application.
* Encapsulation: The object creation logic is encapsulated within the factory method, making it easier to manage and modify. It separates the responsibility of object creation from the client code, resulting in cleaner and more maintainable code.
* Dependency Inversion: By depending on abstractions rather than concrete classes, the Factory Method pattern supports the principle of dependency inversion. This enables loose coupling and facilitates testing, as dependencies can be easily mocked or replaced.

## Disadvantages:

* Complexity: Implementing the Factory Method pattern introduces additional complexity to the codebase. It requires defining and managing interfaces or abstract classes, as well as creating and maintaining subclasses for each object variation.
* Increased number of classes: The Factory Method pattern may lead to an increased number of classes in the codebase, especially if there are multiple object variations. This can make the codebase larger and potentially harder to understand.


Remember that the advantages and disadvantages may vary depending on the specific context and requirements of your project. It's important to evaluate whether the Factory Method pattern is appropriate for your use case before applying it.

## Python example:

In [5]:
class FeaturePreprocessor(ABC):
    """
    Abstract class for feature preprocessing strategies.
    """

    @abstractmethod
    def preprocess(self, data):
        """
        Abstract method to preprocess the data.
        """
        pass

class AgePreprocessor(FeaturePreprocessor):
    """
    Concrete class for preprocessing the 'Age' feature.
    """

    def preprocess(self, data):
        """
        Preprocesses the 'Age' feature by filling missing values with the median age.
        """
        data['Age'] = data['Age'].fillna(data['Age'].median())
        return data

class FarePreprocessor(FeaturePreprocessor):
    """
    Concrete class for preprocessing the 'Fare' feature.
    """

    def preprocess(self, data):
        """
        Preprocesses the 'Fare' feature by filling missing values with the median fare.
        """
        data['Fare'] = data['Fare'].fillna(data['Fare'].median())
        return data

class PreprocessingFactory:
    """
    Factory class for creating feature preprocessing strategies.
    """

    @staticmethod
    def create_preprocessor(feature_name):
        """
        Factory method to create the appropriate feature preprocessor based on the feature name.
        """
        if feature_name == 'Age':
            return AgePreprocessor()
        elif feature_name == 'Fare':
            return FarePreprocessor()
        else:
            raise ValueError(f"Unsupported feature: {feature_name}")

## UML Diagram

[![](https://mermaid.ink/img/pako:eNqlUssKAjEM_JWSk6L-wOJF0L0JgteChDa7LmzbJW0Pov673YfrA0HEXJpOJtMJ6RmU0wQZqBq9X1dYMhppRYoOETlhiEw7poadIu8di3NPaGMmmrEy0Rhw2teu0vbJp_7lZbEQq_IF_MLOkd_ozybftH4yOIyJ_K_Eo72yZY4qOD69yihO49GheXpnUvQTHywauuvCHAyxwUqnxXQKEsKRDEnIUqqpwFgHCdK2VIzB7U9WQRY40hxikzzSsErICqz9iG50lWyNIHXX7fAD2uN6A9j1stI?type=png)](https://mermaid.live/edit#pako:eNqlUssKAjEM_JWSk6L-wOJF0L0JgteChDa7LmzbJW0Pov673YfrA0HEXJpOJtMJ6RmU0wQZqBq9X1dYMhppRYoOETlhiEw7poadIu8di3NPaGMmmrEy0Rhw2teu0vbJp_7lZbEQq_IF_MLOkd_ozybftH4yOIyJ_K_Eo72yZY4qOD69yihO49GheXpnUvQTHywauuvCHAyxwUqnxXQKEsKRDEnIUqqpwFgHCdK2VIzB7U9WQRY40hxikzzSsErICqz9iG50lWyNIHXX7fAD2uN6A9j1stI)

## Usage example

In [6]:
# Select the feature to preprocess
feature_name = 'Age'

# Create the appropriate preprocessor using the factory method
preprocessor = PreprocessingFactory.create_preprocessor(feature_name)

# Preprocess the selected feature
preprocessed_data = preprocessor.preprocess(titanic_data)

# Display the preprocessed data
preprocessed_data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [7]:
preprocessed_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          891 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In this code example, we have an abstract class **FeaturePreprocessor** that defines the common interface for feature preprocessing strategies. Concrete classes **AgePreprocessor** and **FarePreprocessor** implement specific preprocessing logic for the 'Age' and 'Fare' features, respectively.

The **PreprocessingFactory** class acts as the factory and provides a factory method create_preprocessor that takes a feature name as input and returns the appropriate preprocessor object based on that feature. It raises a **ValueError** if an unsupported feature name is provided.

In the usage example, we load the Titanic dataset, select the 'Age' feature to preprocess, create the appropriate preprocessor using the factory method, and apply the preprocessing to the dataset.

# 02. Creational - Abstract Factory

## 01. Problem:
In software development, you often encounter situations where you need to create families of related objects that share a common theme or have dependencies among them. However, you want to ensure that the created objects are compatible and follow a consistent implementation across the family. The problem is that directly instantiating these objects in client code can result in tight coupling and difficulty in managing object creation and variations.

## 02. Solution:
The Abstract Factory design pattern provides a solution by introducing an abstract factory interface or class that defines methods for creating families of related objects. Each concrete subclass of the abstract factory represents a specific variant or family of objects. The client code interacts with the abstract factory and uses it to create instances of the related objects. This decouples the client code from the concrete implementations and allows for the creation of compatible and consistent object families.

## 03. Why it works:
The Abstract Factory design pattern works because it promotes the principle of dependency inversion and abstraction. The client code depends on the abstract factory interface or class, which allows it to work with any concrete factory subclass without being tightly coupled to specific object types. By using the abstract factory, the client code can create and use objects from a specific family without needing to know the details of their creation or the specific classes involved.

## 04. Advantages:

* **Encapsulation of Object Creation**: The Abstract Factory pattern encapsulates the creation logic within the factory classes, making it easier to manage and modify. It centralizes the object creation process and abstracts it away from the client code, leading to cleaner and more maintainable code.
* **Consistency and Compatibility**: The Abstract Factory pattern ensures that the created objects are compatible and follow a consistent implementation across the entire family. It enforces the creation of related objects that work together seamlessly, promoting proper design and avoiding incompatible object combinations.
* **Flexibility and Extensibility**: The Abstract Factory pattern allows for easy introduction of new families of objects by adding new concrete factory subclasses. This makes it simple to extend the application to support additional object variations or families without modifying the existing client code.

## 05. Disadvantages:

* **Complexity**: Implementing the Abstract Factory pattern can introduce additional complexity to the codebase. It requires defining and managing the abstract factory interface or class, as well as creating and maintaining multiple concrete factory subclasses for each object family. This increased complexity can make the code harder to understand and maintain.
* **Overhead**: The Abstract Factory pattern introduces an additional layer of abstraction, which may result in a performance overhead compared to directly instantiating objects. However, this overhead is generally negligible and often outweighed by the benefits of decoupling and maintainability.

## Python example

In [8]:
class FeatureEngineeringStrategy(ABC):
    """
    Abstract class for feature engineering strategies.
    """

    @abstractmethod
    def engineer_feature(self, data):
        """
        Abstract method to engineer the feature.
        """
        pass

class CategoricalFeatureStrategy(FeatureEngineeringStrategy):
    """
    Concrete class for feature engineering strategy for categorical features.
    """

    def engineer_feature(self, data):
        """
        Engineer categorical features by one-hot encoding the 'Embarked' feature.
        """
        data = pd.get_dummies(data, columns=['Embarked'])
        return data

class NumericFeatureStrategy(FeatureEngineeringStrategy):
    """
    Concrete class for feature engineering strategy for numeric features.
    """

    def engineer_feature(self, data):
        """
        Engineer numeric features by filling missing values with the median.
        """
        data = data.fillna(data.median())
        return data

class FeatureEngineeringFactory:
    """
    Abstract factory class for creating feature engineering strategies.
    """

    @staticmethod
    def create_feature_strategy(feature_type):
        """
        Factory method to create the appropriate feature engineering strategy based on the feature type.
        """
        if feature_type == 'Categorical':
            return CategoricalFeatureStrategy()
        elif feature_type == 'Numeric':
            return NumericFeatureStrategy()
        else:
            raise ValueError(f"Unsupported feature type: {feature_type}")

## UML Diagram

[![](https://mermaid.ink/img/pako:eNqdUrsOwjAM_JXIEwj4gYqNxwZL10jIStwSqU1R6gwV8O-kTYoQLyG8xLmc72zFZ1CNJshAVdi2a4Olw1paEWJAxJaQvaONLY0lcsaWOTtkKjtxjrw-ZoIS4VDEgolGxmlkXKWNyRex5WWxEKs-b5xRWCXq-P5b_d7XAVUvtY8Dffb4Y6Ao-d72b7nXKbeouHFPisoFHo16hzbZTkaAuxONBjCH0GKNRoevHlQk8JFqkpCFVFOBvmIJ0vZU9NzknVWQsfM0B38KzVJaDsgKrNo7utEmtHYHabju0k71x_UGf5vTJA?type=png)](https://mermaid.live/edit#pako:eNqdUrsOwjAM_JXIEwj4gYqNxwZL10jIStwSqU1R6gwV8O-kTYoQLyG8xLmc72zFZ1CNJshAVdi2a4Olw1paEWJAxJaQvaONLY0lcsaWOTtkKjtxjrw-ZoIS4VDEgolGxmlkXKWNyRex5WWxEKs-b5xRWCXq-P5b_d7XAVUvtY8Dffb4Y6Ao-d72b7nXKbeouHFPisoFHo16hzbZTkaAuxONBjCH0GKNRoevHlQk8JFqkpCFVFOBvmIJ0vZU9NzknVWQsfM0B38KzVJaDsgKrNo7utEmtHYHabju0k71x_UGf5vTJA)

## Usage example

In [9]:
# Select the feature type to engineer
feature_type = 'Categorical'

# Create the appropriate feature engineering strategy using the factory method
feature_strategy = FeatureEngineeringFactory.create_feature_strategy(feature_type)

# Engineer the selected feature type
engineered_data = feature_strategy.engineer_feature(titanic_data)

# Display the engineered data
engineered_data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked_C,Embarked_Q,Embarked_S
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,0,0,1
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,1,0,0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,0,0,1
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,0,0,1
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,0,0,1

In [10]:
engineered_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          891 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked_C   891 non-null    uint8
 12  Embarked_Q   891 non-null    uint8
 13  Embarked_S   891 non-null    uint8
dtypes: float64(2), int64(5), object(4), uint8(3)
memory usage: 79.3+ KB

In this code example, we have an abstract class **FeatureEngineeringStrategy** that defines the common interface for feature engineering strategies. Concrete classes **CategoricalFeatureStrategy** and **NumericFeatureStrategy** implement specific feature engineering logic for categorical and numeric features, respectively.

The **FeatureEngineeringFactory** class acts as the abstract factory and provides a factory method create_feature_strategy that takes a feature type as input and returns the appropriate feature engineering strategy object based on that type. It raises a **ValueError** if an unsupported feature type is provided.

In the usage example, we load the Titanic dataset, select the '**Categorical**' feature type to engineer, create the appropriate feature engineering strategy using the factory method, and apply the engineering to the dataset.

# 03. Creational - Builder

## 01. Problem:
In software development, you often encounter situations where you need to construct complex objects step by step or with varying configurations. The problem is that the traditional approach of directly constructing objects using multiple constructor parameters or setters can become cumbersome, especially when dealing with objects with numerous optional parameters or complex initialization logic.

## 02. Solution:
The Builder design pattern provides a solution by separating the construction of an object from its representation. It involves creating a separate builder class that handles the step-by-step construction of the object. The builder class provides methods for setting the different properties of the object and a method for retrieving the final constructed object. The client code interacts with the builder class to specify the desired configurations and create the complex object.

## 03. Why it works:
The Builder design pattern works by simplifying the object construction process and providing a clear and readable API for constructing complex objects. By separating the construction logic into a builder class, it allows for a more fluent and intuitive way of configuring and creating objects. It also provides a consistent and controlled way of creating objects with various configurations, without the need for a large number of constructors or complex initialization code.

## 04. Advantages:

* **Flexible Object Construction**: The Builder pattern allows for flexible construction of complex objects by providing a step-by-step approach to configure and create objects. It enables the creation of objects with different configurations while maintaining a clear and readable code structure.
* **Encapsulation of Construction Logic**: The construction logic is encapsulated within the builder class, making it easier to manage and modify. The client code interacts with the builder's methods to set the desired properties, while the construction process is hidden from the client code.
* **Readability and Maintainability**: The Builder pattern improves the readability and maintainability of code by providing a more intuitive and descriptive way of constructing objects. It abstracts away the complexity of object creation, making the client code more focused on the desired configurations.

## 05. Disadvantages:

* **Increased Code Complexity**: Implementing the Builder pattern introduces an additional layer of abstraction, which can increase code complexity. It requires defining the builder class and its associated methods, which may add extra code overhead compared to direct object instantiation.
* **Overhead in Small Objects**: The Builder pattern may introduce unnecessary overhead for simple objects that do not have many optional parameters or complex initialization logic. In such cases, the simplicity and readability of direct object instantiation may be more appropriate.

## Python example

In [11]:
class DataPreprocessor:
    """
    Class representing the data preprocessing pipeline.
    """

    def __init__(self):
        self.steps = []

    def add_step(self, step):
        """
        Adds a preprocessing step to the pipeline.
        """
        self.steps.append(step)

    def preprocess_data(self, data):
        """
        Applies the preprocessing steps to the data in sequential order.
        """
        for step in self.steps:
            data = step.execute(data)
        return data

class PreprocessingStep(ABC):
    """
    Abstract class representing a preprocessing step.
    """

    @abstractmethod
    def execute(self, data):
        """
        Abstract method to execute the preprocessing step.
        """
        pass

class FillMissingValuesStep(PreprocessingStep):
    """
    Concrete class representing a preprocessing step to fill missing values.
    """

    def execute(self, data):
        """
        Fills missing values in selected columns with appropriate strategies.
        """
        data['Age'] = data['Age'].fillna(data['Age'].median())
        data['Fare'] = data['Fare'].fillna(data['Fare'].median())
        return data

class FeatureEngineeringStep(PreprocessingStep):
    """
    Concrete class representing a preprocessing step for feature engineering.
    """

    def execute(self, data):
        """
        Performs feature engineering operations on the data.
        """
        # Example: Creating a new feature 'FamilySize'
        data['FamilySize'] = data['SibSp'] + data['Parch'] + 1
        return data

## UML Diagram

[![](https://mermaid.ink/img/pako:eNqNUsFqwzAM_RWjU7s1h17D2KndrVAo7GQowlYzg2MHW4aNrv8-O8myjYRtOsjPT9J7AvsKymuCGpTFGHcGm4CtdCJHz4gdMh4DdcEritEHcR2qJe4Fan2OTN2qpPX3SjfNnHWWWJU0NtykG8BMW8JWgqiqx4zuMvoqGtecssXn5LDbrPxzOXollZgWreejD-9VJZ6MtQfTk89oE8XB9LcJQk6B9q4xjigs7rmo-v9dR5FFo79VYAMthRaNzq_cd0vgF2pJQp2hpgsmyxKkK62Y2J_enIKaQ6INpC5r0fgvoL6gjRO714Z9mEjqr4fxO5Xj9gGooslM?type=png)](https://mermaid.live/edit#pako:eNqNUsFqwzAM_RWjU7s1h17D2KndrVAo7GQowlYzg2MHW4aNrv8-O8myjYRtOsjPT9J7AvsKymuCGpTFGHcGm4CtdCJHz4gdMh4DdcEritEHcR2qJe4Fan2OTN2qpPX3SjfNnHWWWJU0NtykG8BMW8JWgqiqx4zuMvoqGtecssXn5LDbrPxzOXollZgWreejD-9VJZ6MtQfTk89oE8XB9LcJQk6B9q4xjigs7rmo-v9dR5FFo79VYAMthRaNzq_cd0vgF2pJQp2hpgsmyxKkK62Y2J_enIKaQ6INpC5r0fgvoL6gjRO714Z9mEjqr4fxO5Xj9gGooslM)

## Usage example

In [12]:
 # Create the data preprocessing pipeline using the builder
preprocessor = DataPreprocessor()
preprocessor.add_step(FillMissingValuesStep())
preprocessor.add_step(FeatureEngineeringStep())

# Preprocess the data using the pipeline
preprocessed_data = preprocessor.preprocess_data(titanic_data)

# Display the preprocessed data
preprocessed_data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,FamilySize
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,2
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,2
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,2
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,1

In [13]:
preprocessed_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          891 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
 12  FamilySize   891 non-null    int64
dtypes: float64(2), int64(6), object(5)
memory usage: 90.6+ KB

In this code example, we have a **DataPreprocessor** class representing the data preprocessing pipeline. It has a list of preprocessing steps and a method preprocess_data to execute the steps sequentially on the input data.

The **PreprocessingStep** class is an abstract class representing a preprocessing step, and concrete classes **FillMissingValuesStep** and **FeatureEngineeringStep** implement specific preprocessing logic.

The usage example demonstrates the creation of the data preprocessing pipeline using the builder approach. We create an instance of **DataPreprocessor**, add the desired preprocessing steps using add_step, and then apply the preprocessing pipeline to the Titanic dataset.

# 04. Creational - Prototype

## 01. Problem:
In software development, you often encounter situations where you need to create new objects by copying existing objects. However, creating objects from scratch can be expensive in terms of resources and time, especially when the initialization process is complex or involves costly operations. The problem is that directly creating objects using constructors or factories can lead to inefficient object creation and reduced performance.

## 02. Solution:
The Prototype design pattern provides a solution by introducing a prototype object that serves as a blueprint for creating new objects. Instead of creating objects from scratch, you create a clone of the prototype object and modify it as necessary. The clone operation can be shallow or deep, depending on the complexity of the object and its internal references. This approach allows you to efficiently create new objects by copying existing ones, reducing the overhead of object creation.

## 03. Why it works:
The Prototype design pattern works by leveraging object cloning to create new objects. By using a prototype object as a blueprint, you eliminate the need for costly initialization or construction operations. Instead, you simply clone the prototype and modify the clone if required. This approach allows for efficient object creation and customization while maintaining a consistent and optimized object creation process.

## 04. Advantages:

* **Reduced Object Creation Cost**: The Prototype pattern reduces the cost of creating new objects by avoiding expensive initialization or construction operations. It leverages object cloning, which is often more efficient and faster than creating objects from scratch.
* **Customizable Object Creation**: With the Prototype pattern, you can easily customize and modify the cloned objects as needed. You can modify specific attributes or relationships of the cloned objects to tailor them to your requirements without the need for complex configuration or instantiation steps.
* **Flexibility and Extensibility**: The Prototype pattern provides flexibility and extensibility in object creation. You can introduce new prototypes or subclasses to create variations of objects, and the cloning process can be adjusted to support different cloning strategies, such as shallow or deep cloning.
Disadvantages:

* **Cloning Overhead**: The Prototype pattern introduces the overhead of cloning objects, which may be negligible for simple objects but can become noticeable for complex or large objects. Deep cloning, in particular, can have performance implications if the object contains deep nested structures or references.
* **Complexity in Managing Prototypes**: Managing and maintaining the prototypes can become complex, especially when dealing with multiple prototype objects or complex inheritance hierarchies. Ensuring proper initialization and updating of prototypes can require additional effort and careful management.

## Python example

In [14]:
class DataPreprocessingConfig:
    """
    Class representing the data preprocessing configuration.
    """

    def __init__(self):
        self.fill_missing_values = True
        self.feature_scaling = False
        self.feature_selection = False

    def configure(self, fill_missing_values=True, feature_scaling=False, feature_selection=False):
        """
        Configures the data preprocessing settings.
        """
        self.fill_missing_values = fill_missing_values
        self.feature_scaling = feature_scaling
        self.feature_selection = feature_selection

    def clone(self):
        """
        Creates a clone of the configuration object.
        """
        return deepcopy(self)

class DataPreprocessor:
    """
    Class representing the data preprocessor.
    """

    def __init__(self, config):
        self.config = config

    def preprocess_data(self, data):
        """
        Applies the data preprocessing steps based on the configuration.
        """
        if self.config.fill_missing_values:
            # Perform fill missing values preprocessing
            data = self.fill_missing_values(data)

        if self.config.feature_scaling:
            # Perform feature scaling preprocessing
            data = self.feature_scaling(data)

        if self.config.feature_selection:
            # Perform feature selection preprocessing
            data = self.feature_selection(data)

        return data

    def fill_missing_values(self, data):
        """
        Fills missing values in selected columns with appropriate strategies.
        """
        # Example: Filling missing values in 'Age' column with median
        data['Age'] = data['Age'].fillna(data['Age'].median())
        return data

    def feature_scaling(self, data):
        """
        Applies feature scaling to selected numeric columns.
        """
        # Example: Applying Min-Max scaling to 'Fare' column
        data['Fare'] = (data['Fare'] - data['Fare'].min()) / (data['Fare'].max() - data['Fare'].min())
        return data

    def feature_selection(self, data):
        """
        Applies feature selection based on selected criteria.
        """
        # Example: Removing 'Cabin' column
        data = data.drop('Cabin', axis=1)
        return data

## UML Diagram

[![](https://mermaid.ink/img/pako:eNp9kj1rxDAMhv-K0ZSjydA1Q5dex0LhVkMQtpwa_BH8UTiO_Pc6bhoSelcNtvzqRTy2fAPhJUEPwmCMZ41jQMsdK1EVdsaEH4Gm4AXFqN346p3SI7v9mJZ4YqJqOVCjtDGD1dU5fKHJFFumCFMpDlGgKfpOIEMiae9Oh27GO2pWaebuMY4PR45pqwyyGJtl2bXu2B28O6Yj7j-GX_y9ZQP-g8rhmQPrupc1e_C03EELloJFLctg6gU5pE-yxKEvqSSF2SQO3M3Fijn5y9UJ6FPI1EKeCg2to4ReoYmb-iZ18mETqR7f1x-wbPM3HuiwAQ?type=png)](https://mermaid.live/edit#pako:eNp9kj1rxDAMhv-K0ZSjydA1Q5dex0LhVkMQtpwa_BH8UTiO_Pc6bhoSelcNtvzqRTy2fAPhJUEPwmCMZ41jQMsdK1EVdsaEH4Gm4AXFqN346p3SI7v9mJZ4YqJqOVCjtDGD1dU5fKHJFFumCFMpDlGgKfpOIEMiae9Oh27GO2pWaebuMY4PR45pqwyyGJtl2bXu2B28O6Yj7j-GX_y9ZQP-g8rhmQPrupc1e_C03EELloJFLctg6gU5pE-yxKEvqSSF2SQO3M3Fijn5y9UJ6FPI1EKeCg2to4ReoYmb-iZ18mETqR7f1x-wbPM3HuiwAQ)

## Usage example

In [15]:
# Create the base data preprocessing configuration
base_config = DataPreprocessingConfig()

# Configure the base configuration
base_config.configure(fill_missing_values=True, feature_scaling=True, feature_selection=False)

# Create the base preprocessor using the base configuration
base_preprocessor = DataPreprocessor(base_config)

# Preprocess the data using the base preprocessor
base_preprocessed_data = base_preprocessor.preprocess_data(titanic_data)

# Create a new configuration by cloning the base configuration and modifying it
new_config = base_config.clone()
new_config.configure(fill_missing_values=False, feature_selection=True)

# Create a new preprocessor using the new configuration
new_preprocessor = DataPreprocessor(new_config)

# Preprocess the data using the new preprocessor
new_preprocessed_data = new_preprocessor.preprocess_data(titanic_data)

# Display the preprocessed data
print("Base Preprocessed Data:")
base_preprocessed_data.head()

Base Preprocessed Data:

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,FamilySize
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,0.014151,NaN,S,2
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,0.139136,C85,C,2
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,0.015469,NaN,S,1
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,0.103644,C123,S,2
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,0.015713,NaN,S,1

In [16]:
print("New Preprocessed Data:")
new_preprocessed_data.head()

New Preprocessed Data:

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,FamilySize
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,0.014151,S,2
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,0.139136,C,2
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,0.015469,S,1
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,0.103644,S,2
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,0.015713,S,1

In this code example, we have a **DataPreprocessingConfig** class representing the data preprocessing configuration. It contains attributes for different preprocessing settings and methods to configure and clone the configuration object.

The **DataPreprocessor** class represents the data preprocessor, which takes a configuration object during initialization. The preprocess_data method applies the data preprocessing steps based on the configuration settings.

In the usage example, we create a base configuration and a base preprocessor. We preprocess the data using the base preprocessor. Then, we clone the base configuration, modify it, and create a new preprocessor with the new configuration. We preprocess the data again using the new preprocessor.

# 05. Creational - Singleton

## 01. Problem:
In software development, you often encounter situations where you need to ensure that a class has only one instance throughout the program. This can be necessary for resource management, coordination, or to maintain a central point of access for shared functionality. The problem is that multiple instances of the class can be created, leading to unnecessary resource allocation or inconsistent behavior.

## 02. Solution:
The Singleton design pattern provides a solution by ensuring that a class has only one instance and providing global access to that instance. It involves defining a class with a private constructor and a static method that controls the creation and access to the instance. The first time the static method is called, it creates the instance and returns it. On subsequent calls, it simply returns the existing instance.

## 03. Why it works:
The Singleton design pattern works by enforcing the creation of a single instance of the class and providing a global point of access to that instance. By restricting the constructor to be private, it prevents external code from directly creating multiple instances. The static method ensures that only one instance is created and returned, regardless of how many times it is called.

## 04. Advantages:

* **Single Instance**: The Singleton pattern ensures that there is only one instance of the class throughout the program, eliminating the possibility of multiple instances being created and providing a global point of access to that instance.
* **Global Access:** The Singleton pattern provides a globally accessible point to access the instance, making it convenient to use and reducing the need for passing references to the instance across different parts of the code.
Resource Management: The Singleton pattern can be useful for managing resources that should be shared across the program, such as database connections, file handles, or hardware devices.


## 05. Disadvantages:

* **Global State:** The Singleton pattern introduces global state, which can make it harder to track dependencies and understand the flow of data within the program. This can increase the complexity of debugging and testing.
* **Reduced Flexibility**: The Singleton pattern limits the extensibility and flexibility of the class, as it allows only one instance to exist. This can make it difficult to substitute the singleton object with a different implementation or mock it for testing purposes.
* **Testing Challenges**: Testing code that relies on the Singleton pattern can be challenging, as the global state introduced by the singleton instance can lead to dependencies and interference between test cases.

## Python example

In [17]:
class DataPreprocessingConfig:
    """
    Class representing the data preprocessing configuration.
    """

    def __init__(self):
        self.fill_missing_values = True
        self.feature_scaling = True
        self.feature_selection = False

class DataPreprocessingManager:
    """
    Singleton class for managing the data preprocessing configuration.
    """

    _instance = None

    @staticmethod
    def get_instance():
        """
        Static method to get the singleton instance.
        """
        if not DataPreprocessingManager._instance:
            DataPreprocessingManager._instance = DataPreprocessingConfig()
        return DataPreprocessingManager._instance

    def preprocess_data(self, data):
        """
        Applies the data preprocessing steps based on the configuration.
        """
        config = self.get_instance()
        if config.fill_missing_values:
            # Perform fill missing values preprocessing
            data = self.fill_missing_values(data)

        if config.feature_scaling:
            # Perform feature scaling preprocessing
            data = self.feature_scaling(data)

        if config.feature_selection:
            # Perform feature selection preprocessing
            data = self.feature_selection(data)

        return data

    def fill_missing_values(self, data):
        """
        Fills missing values in selected columns with appropriate strategies.
        """
        # Example: Filling missing values in 'Age' column with median
        data['Age'] = data['Age'].fillna(data['Age'].median())
        return data

    def feature_scaling(self, data):
        """
        Applies feature scaling to selected numeric columns.
        """
        # Example: Applying Min-Max scaling to 'Fare' column
        data['Fare'] = (data['Fare'] - data['Fare'].min()) / (data['Fare'].max() - data['Fare'].min())
        return data

    def feature_selection(self, data):
        """
        Applies feature selection based on selected criteria.
        """
        # Example: Removing 'Cabin' column
        data = data.drop('Cabin', axis=1)
        return data

## Usage example

[![](https://mermaid.ink/img/pako:eNqFUk1rwzAM_StGp5Y1h11z2GXdsTDo1WCErXgGRw7-GIyS_z4nzUIKbaeDLb_3bPQkX0AHQ9CC9pjS0aGN2EsWNWZEHDHjZ6QhBk0pObbvgTtnxeUqmqIRnfNe9W7m1Tf6QumGJswlkkoafVXcpciTzi7wlRwlPy3ihIyW4raKF2EpK8cpI2va7bfMsN5Vpj61m5b9PwbuiG5tPBH8mdlKVksPzUh4lSCa5m3JHrReMhygp9ijM3Vwcwsk5C_qSUJbU0MdFp8lSB6rFEsO5x_W0OZY6ABlqFXRMmpoO_RpRT-MyyGuIM3H0_JDpm38BdkAuJk?type=png)](https://mermaid.live/edit#pako:eNqFUk1rwzAM_StGp5Y1h11z2GXdsTDo1WCErXgGRw7-GIyS_z4nzUIKbaeDLb_3bPQkX0AHQ9CC9pjS0aGN2EsWNWZEHDHjZ6QhBk0pObbvgTtnxeUqmqIRnfNe9W7m1Tf6QumGJswlkkoafVXcpciTzi7wlRwlPy3ihIyW4raKF2EpK8cpI2va7bfMsN5Vpj61m5b9PwbuiG5tPBH8mdlKVksPzUh4lSCa5m3JHrReMhygp9ijM3Vwcwsk5C_qSUJbU0MdFp8lSB6rFEsO5x_W0OZY6ABlqFXRMmpoO_RpRT-MyyGuIM3H0_JDpm38BdkAuJk)

In [18]:
# Get the singleton instance of DataPreprocessingConfig
config = DataPreprocessingManager.get_instance()

# Modify the configuration as needed
config.fill_missing_values = False
config.feature_selection = True

# Preprocess the data using the singleton instance
preprocessed_data = DataPreprocessingManager().preprocess_data(titanic_data)

# Display the preprocessed data
preprocessed_data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,FamilySize
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,0.014151,S,2
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,0.139136,C,2
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,0.015469,S,1
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,0.103644,S,2
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,0.015713,S,1

In [19]:
config2 = DataPreprocessingManager.get_instance()

In [20]:
# Test if it is the same instance
config == config2

True

In [21]:
preprocessed_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          891 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Embarked     889 non-null    object
 11  FamilySize   891 non-null    int64
dtypes: float64(2), int64(6), object(4)
memory usage: 83.7+ KB

In this code example, we have a **DataPreprocessingConfig** class representing the data preprocessing configuration. It contains attributes for different preprocessing settings.

The **DataPreprocessingManager** class serves as the Singleton class for managing the configuration. It has a static method **get_instance()** that returns the singleton instance of the **DataPreprocessingConfig**. The instance is created if it doesn't exist. The preprocess_data method in DataPreprocessingManager applies the data preprocessing steps based on the configuration settings.

In the usage example, we access the singleton instance of DataPreprocessingConfig using **DataPreprocessingManager.get_instance()**. We modify the configuration as needed and preprocess the data using the singleton instance.

# 06. Structural - Adapter

## 01. Problem:
In software development, you often encounter situations where you need to integrate or use existing classes or components that have incompatible interfaces or communication protocols. The problem is that direct communication or interaction with these incompatible classes is not possible, resulting in the inability to reuse or integrate them seamlessly.

## 02. Solution:
The Adapter design pattern provides a solution by acting as a bridge between the incompatible interfaces or protocols. It involves creating an adapter class that wraps around the incompatible class and provides a compatible interface that other components can interact with. The adapter class translates requests or calls from the compatible interface into the corresponding calls or operations of the underlying incompatible class.

## 03. Why it works:
The Adapter design pattern works by introducing an intermediary adapter class that acts as a layer of translation or compatibility. It allows components that require a specific interface or protocol to communicate with the incompatible class without needing to modify the existing codebase or the incompatible class itself. The adapter class encapsulates the translation logic, providing a seamless integration point for the incompatible components.

## 04. Advantages:

* **Improved Reusability**: The Adapter pattern allows for the reuse of existing incompatible classes or components by providing a compatible interface. It enables integration with other components or systems without the need for significant modifications to the existing codebase.
* **Seamless Integration**: The Adapter pattern provides a seamless integration point between the incompatible components. It acts as a bridge, translating and adapting requests and responses between the components, ensuring smooth communication.
* **Encapsulation of Compatibility Logic**: The adapter class encapsulates the logic required to translate or adapt the incompatible interface or protocol. This encapsulation helps maintain clean and modular code, as the translation logic is isolated within the adapter.

## 05. Disadvantages:

* **Increased Complexity**: Implementing the Adapter pattern can introduce additional complexity, as it requires creating and managing the adapter class and its interactions with the incompatible class. This added complexity can make the code harder to understand and maintain.
* **Performance Overhead**: The Adapter pattern may introduce a performance overhead due to the translation or adaptation process. The additional layer of abstraction and the need to map between different interfaces or protocols can impact the overall performance of the system.

## Python example

In [22]:
class CustomEvaluationFramework:
    """
    Custom evaluation framework that requires a specific interface for model evaluation.
    """

    def evaluate_model(self, model, X, y):
        """
        Evaluates the model using the custom evaluation metrics.
        """
        # Custom evaluation logic
        y_pred = model.predict(X)
        accuracy = accuracy_score(y, y_pred)
        return accuracy

class ScikitLearnModelAdapter:
    """
    Adapter class to adapt a scikit-learn model to the custom evaluation framework.
    """

    def __init__(self, model):
        self.model = model

    def predict(self, X):
        """
        Calls the predict method of the adapted scikit-learn model.
        """
        return self.model.predict(X)

## UML Diagram

[![](https://mermaid.ink/img/pako:eNp1kMsKAjEMRX-lZKU4_sDgRnysdOXGRUFCG7XYx9BJFRnm3-08EBXMoklvDrdNGlBBE5SgLNb12uAlopNe5OgVsUo1B7e5o03IJvht7tMjxJtoBqyLmaABoJPLdnbSn4U4FuI5HbBW-k_bgzI3wzvC6Pcdu9RYMcVv0yqSNoonx1-P_59azOf_vKWHAhxFh0bngfuXJPCVHEkoc6npjMmyBOnbjGLicHh6BSXHRAWkSucBxxVBeUZbv9WNNhziW6T-uh8326X2BXiTeg8?type=png)](https://mermaid.live/edit#pako:eNp1kMsKAjEMRX-lZKU4_sDgRnysdOXGRUFCG7XYx9BJFRnm3-08EBXMoklvDrdNGlBBE5SgLNb12uAlopNe5OgVsUo1B7e5o03IJvht7tMjxJtoBqyLmaABoJPLdnbSn4U4FuI5HbBW-k_bgzI3wzvC6Pcdu9RYMcVv0yqSNoonx1-P_59azOf_vKWHAhxFh0bngfuXJPCVHEkoc6npjMmyBOnbjGLicHh6BSXHRAWkSucBxxVBeUZbv9WNNhziW6T-uh8326X2BXiTeg8)

## Usage example

In [23]:
# Prepare the dataset for modeling
X = titanic_data[['Pclass', 'Age', 'Fare']]
y = titanic_data['Survived']

# Create a scikit-learn model
sklearn_model = RandomForestClassifier()

# Train the scikit-learn model
sklearn_model.fit(X, y)

# Create the adapter to adapt the scikit-learn model to the custom evaluation framework
adapter = ScikitLearnModelAdapter(sklearn_model)

# Create an instance of the custom evaluation framework
evaluation_framework = CustomEvaluationFramework()

# Evaluate the adapted model using the custom evaluation framework
accuracy = evaluation_framework.evaluate_model(adapter, X, y)

# Display the evaluation result
print("Accuracy:", accuracy)

Accuracy: 0.9461279461279462

In this code example, we have a **CustomEvaluationFramework** class representing a custom evaluation framework that requires a specific interface for model evaluation. It has a method **evaluate_model** that performs evaluation using custom evaluation metrics.

The **ScikitLearnModelAdapter** class acts as an adapter class to adapt a s**cikit-learn model** to the custom evaluation framework. It wraps the scikit-learn model and provides a compatible interface by implementing a predict method.

In the usage example, we load the Titanic dataset, create a scikit-learn model (Random Forest Classifier), and train it using the dataset. We then create an instance of the adapter class, passing the scikit-learn model as an argument. We also create an instance of the custom evaluation framework. Finally, we evaluate the adapted model using the custom evaluation framework and display the evaluation result.

# 07. Structural - Bridge

## 01. Problem:
In software development, you often encounter situations where you need to decouple an abstraction from its implementation. The problem is that a traditional approach with a single class hierarchy for both the abstraction and its implementation can result in a large number of class combinations and a tight coupling between the abstraction and implementation, making the codebase complex and hard to maintain.

## 02. Solution:
The Bridge design pattern provides a solution by separating the abstraction from its implementation using two separate class hierarchies. It involves creating an abstraction class that defines the high-level interface, and an implementation class that provides the concrete implementation details. The abstraction class contains a reference to the implementation class, allowing the abstraction to delegate specific implementation tasks to the implementation class.

## 03. Why it works:
The Bridge design pattern works by decoupling the abstraction from its implementation, allowing them to vary independently. By encapsulating each hierarchy within its own class, the Bridge pattern promotes loose coupling and flexibility. The abstraction can select and use different implementations at runtime without modifying its code, and new abstractions and implementations can be added independently without affecting each other.

## 04. Advantages:

* **Decoupling of Abstraction and Implementation**: The Bridge pattern separates the abstraction and implementation, reducing the tight coupling between them. This separation promotes modularity, flexibility, and maintainability, as changes in one hierarchy do not affect the other.
* **Runtime Selection of Implementations**: The Bridge pattern allows for the dynamic selection of different implementations for the abstraction at runtime. This provides the flexibility to switch implementations without modifying the abstraction's code, making it easier to adapt to changing requirements.
* **Extensibility**: The Bridge pattern allows for the independent extension of the abstraction and implementation hierarchies. New abstractions or implementations can be added without affecting existing classes, providing a scalable and modular design.

## 05. Disadvantages:

* **Increased Complexity**: Implementing the Bridge pattern introduces additional complexity, as it requires defining and managing two separate class hierarchies. This can make the codebase more intricate and harder to understand, especially for smaller or simpler projects.
* **Overhead of Abstraction and Implementation Interaction**: The Bridge pattern introduces an additional layer of interaction between the abstraction and implementation classes, which can incur some performance overhead. This overhead may be negligible in most cases, but it should be considered in performance-critical scenarios.

## Python example

In [24]:
class DataPreprocessor(ABC):
    """
    Abstraction class representing the data preprocessing.
    """

    def __init__(self, implementation):
        self.implementation = implementation

    @abstractmethod
    def preprocess_data(self, data):
        """
        Abstract method to preprocess the data.
        """
        pass

class FillMissingValues(DataPreprocessor):
    """
    Concrete implementation class for filling missing values in the data.
    """

    def preprocess_data(self, data):
        """
        Fills missing values in selected columns with appropriate strategies.
        """
        return self.implementation.fill_missing_values(data)

class FeatureScaling(DataPreprocessor):
    """
    Concrete implementation class for performing feature scaling on the data.
    """

    def preprocess_data(self, data):
        """
        Applies feature scaling to selected numeric columns.
        """
        return self.implementation.feature_scaling(data)

class TitanicDataPreprocessor:
    """
    Implementation class providing specific data preprocessing strategies for the Titanic dataset.
    """

    def fill_missing_values(self, data):
        """
        Fills missing values in selected columns with appropriate strategies.
        """
        # Example: Filling missing values in 'Age' column with median
        data['Age'] = data['Age'].fillna(data['Age'].median())
        return data

    def feature_scaling(self, data):
        """
        Applies feature scaling to selected numeric columns.
        """
        # Example: Applying Min-Max scaling to 'Fare' column
        data['Fare'] = (data['Fare'] - data['Fare'].min()) / (data['Fare'].max() - data['Fare'].min())
        return data

## UML Diagram

[![](https://mermaid.ink/img/pako:eNqdkk1rwzAMhv-K0Wmj7WHX0GO3W2HQsZMgCFtpDf4I_hiMLv99TpyFjdKyTQdbll5eP8g-g_SKoQFpKMadpmMgi06UmCpiR4meA_fBS47RB3Gu3TFWol86rSrCu3G5r4IBXU0uHLYfm4140sbsdYzaHV_JZI43xUwpBz5IMkX_ZVwBL4z-Tjgb_bjkvy4vOpHT8vbYusLc2grdvk3U3y1nUeVpYwX63WwRHhCELzOr2RUcdLAGy8GSVuXxJziEdGLLCE1JFXeUTUJANxQp5eQP705Ck0LmNeS-0PD8XaDpyMSl-qh08mEp8nTcz79s3IZPgTPSgA?type=png)](https://mermaid.live/edit#pako:eNqdkk1rwzAMhv-K0Wmj7WHX0GO3W2HQsZMgCFtpDf4I_hiMLv99TpyFjdKyTQdbll5eP8g-g_SKoQFpKMadpmMgi06UmCpiR4meA_fBS47RB3Gu3TFWol86rSrCu3G5r4IBXU0uHLYfm4140sbsdYzaHV_JZI43xUwpBz5IMkX_ZVwBL4z-Tjgb_bjkvy4vOpHT8vbYusLc2grdvk3U3y1nUeVpYwX63WwRHhCELzOr2RUcdLAGy8GSVuXxJziEdGLLCE1JFXeUTUJANxQp5eQP705Ck0LmNeS-0PD8XaDpyMSl-qh08mEp8nTcz79s3IZPgTPSgA)

## Usage example

In [25]:

# Create the data preprocessing instances with specific implementations
fill_missing_values_preprocessor = FillMissingValues(TitanicDataPreprocessor())
feature_scaling_preprocessor = FeatureScaling(TitanicDataPreprocessor())

# Preprocess the data using the different strategies
data_filled_missing = fill_missing_values_preprocessor.preprocess_data(titanic_data)
data_feature_scaled = feature_scaling_preprocessor.preprocess_data(titanic_data)

# Display the preprocessed data
print("Data with filled missing values:")
data_filled_missing.head()

Data with filled missing values:

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,FamilySize
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,0.014151,NaN,S,2
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,0.139136,C85,C,2
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,0.015469,NaN,S,1
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,0.103644,C123,S,2
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,0.015713,NaN,S,1

In [26]:
data_filled_missing.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          891 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
 12  FamilySize   891 non-null    int64
dtypes: float64(2), int64(6), object(5)
memory usage: 90.6+ KB

In [27]:

print("Data with feature scaling:")
data_feature_scaled.head()

Data with feature scaling:

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,FamilySize
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,0.014151,NaN,S,2
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,0.139136,C85,C,2
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,0.015469,NaN,S,1
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,0.103644,C123,S,2
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,0.015713,NaN,S,1

In [28]:
data_feature_scaled.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          891 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
 12  FamilySize   891 non-null    int64
dtypes: float64(2), int64(6), object(5)
memory usage: 90.6+ KB

In this code example, we have an **DataPreprocessor** class representing the abstraction for data preprocessing. It contains a reference to an implementation class and an abstract method preprocess_data that needs to be implemented by concrete implementations.

The concrete implementation classes, **FillMissingValues** and FeatureScaling, extend the **DataPreprocessor** class and implement the preprocess_data method according to their specific strategies.

The **TitanicDataPreprocessor** class represents the implementation class providing specific data preprocessing strategies for the Titanic dataset.

In the usage example, we create instances of the **FillMissingValues** and **FeatureScaling** classes, passing an instance of the **TitanicDataPreprocessor** as the implementation. We then preprocess the data using the different strategies and display the preprocessed data.

# 08. Structural - Composite

## 01. Problem:
In software development, you often encounter situations where you need to work with hierarchical structures or collections of objects in a uniform way. The problem is that treating individual objects and groups of objects differently can lead to complex and inconsistent code. Additionally, the client code may need to perform operations on both individual objects and groups of objects without knowing their specific types.

## 02. Solution:
The Composite design pattern provides a solution by treating individual objects and groups of objects uniformly. It involves creating a common interface for both individual objects and groups of objects, allowing clients to interact with them in a consistent way. The individual objects and groups of objects are structured as a tree-like hierarchy, where both share a common base class or interface.

## 03. Why it works:
The Composite design pattern works by representing individual objects and groups of objects in a unified manner through a common interface or base class. This abstraction allows clients to treat objects uniformly without needing to know their specific types. The hierarchical structure of objects enables recursive operations, where operations can be applied to both individual objects and groups of objects seamlessly.

## 04. Advantages:

* **Transparent Structure**: The Composite pattern provides a transparent structure for working with hierarchies of objects. Clients can treat individual objects and groups of objects uniformly, abstracting away the details of the object hierarchy.
* **Flexibility and Scalability**: The Composite pattern allows for the addition of new types of objects without impacting the existing code. New individual objects and groups of objects can be easily added to the hierarchy, providing flexibility and scalability.
* **Simplified Client Code**: Clients can work with the objects in a consistent and unified manner, without needing to handle different object types separately. This simplifies client code and promotes a more intuitive and clean design.

## 05. Disadvantages:

* **Complexity**: Implementing the Composite pattern can introduce additional complexity, especially when dealing with complex object hierarchies or operations. The recursive nature of the pattern may require careful handling to avoid performance issues or unintended behaviors.
* **Limited Type-Specific Operations**: Treating objects uniformly through a common interface may restrict the usage of type-specific operations. Clients may need to perform type checks or casts to access specific features or behaviors of individual objects.
* **Maintenance Overhead**: Managing the relationships and hierarchy between objects can require additional effort and maintenance. Ensuring consistency and integrity within the object hierarchy may become more challenging as the complexity of the structure increases.

## Python example

In [29]:
import pandas as pd

class PassengerComponent:
    """
    Abstract base class representing the component in the composite structure.
    """

    def get_passenger_count(self):
        """
        Abstract method to get the passenger count.
        """
        pass

class Passenger(PassengerComponent):
    """
    Leaf node representing an individual passenger in the composite structure.
    """

    def __init__(self, name):
        self.name = name

    def get_passenger_count(self):
        """
        Returns the passenger count, which is always 1 for an individual passenger.
        """
        return 1

class PassengerGroup(PassengerComponent):
    """
    Composite node representing a group of passengers in the composite structure.
    """

    def __init__(self, name):
        self.name = name
        self.passengers = []

    def add_passenger(self, passenger):
        """
        Adds a passenger to the group.
        """
        self.passengers.append(passenger)

    def remove_passenger(self, passenger):
        """
        Removes a passenger from the group.
        """
        self.passengers.remove(passenger)

    def get_passenger_count(self):
        """
        Returns the passenger count, which is the sum of the passenger counts in the group.
        """
        count = 0
        for passenger in self.passengers:
            count += passenger.get_passenger_count()
        return count

## UML Diagram

[![](https://mermaid.ink/img/pako:eNqVUsFKAzEQ_ZUwp622Ra-LNxVPguA1EIbNdA1sJkt2IkjdfzfdtFtbBNsckpeXx8vLZLbQBEtQQ9PhMDw5bCN6zSqPiVFveSJuKT4G3wcmFrUt57txq1oS0x80pgmJpVoUwai5gD88Hr5XqyN_oewlhtQfTM_inaYyxrETYypGT4tr855ZT9de6o_WHv2rGZ1oIvnwSf_KriptCanhbr2-0aBy2TTcF_yrzLAET9Gjs_nLpxdpkA_ypKHO0NIGUycaNI9ZiknC-xc3UEtMtITUWxTaNwnUG-yGmX22TkKcSZq2r_ve2i3jD4XqyjQ?type=png)](https://mermaid.live/edit#pako:eNqVUsFKAzEQ_ZUwp622Ra-LNxVPguA1EIbNdA1sJkt2IkjdfzfdtFtbBNsckpeXx8vLZLbQBEtQQ9PhMDw5bCN6zSqPiVFveSJuKT4G3wcmFrUt57txq1oS0x80pgmJpVoUwai5gD88Hr5XqyN_oewlhtQfTM_inaYyxrETYypGT4tr855ZT9de6o_WHv2rGZ1oIvnwSf_KriptCanhbr2-0aBy2TTcF_yrzLAET9Gjs_nLpxdpkA_ypKHO0NIGUycaNI9ZiknC-xc3UEtMtITUWxTaNwnUG-yGmX22TkKcSZq2r_ve2i3jD4XqyjQ)

## Usage example

In [30]:

# Create individual passengers
passenger1 = Passenger("John")
passenger2 = Passenger("Jane")
passenger3 = Passenger("Alice")

# Create a group of passengers
group1 = PassengerGroup("Family 1")
group1.add_passenger(passenger1)
group1.add_passenger(passenger2)

# Create another group of passengers
group2 = PassengerGroup("Family 2")
group2.add_passenger(passenger3)

# Create the top-level group
top_group = PassengerGroup("Titanic Passengers")
top_group.add_passenger(group1)
top_group.add_passenger(group2)

# Get the total passenger count
total_passenger_count = top_group.get_passenger_count()

# Display the passenger count
print("Total Passenger Count:", total_passenger_count)

Total Passenger Count: 3

# 09. Structural - Decorator

## 01. Problem:
In software development, you often encounter situations where you need to add additional behavior or functionalities to an object dynamically without modifying its underlying structure or code. The problem is that traditional inheritance-based approaches can result in a rigid class hierarchy or introduce a high number of subclasses for each combination of functionalities, making the codebase complex and hard to maintain.

## 02. Solution:
The Decorator design pattern provides a solution by allowing you to add or modify the behavior of an object at runtime without affecting its structure. It involves creating decorator classes that wrap around the original object and provide additional functionalities by implementing the same interface as the original object. Multiple decorators can be stacked on top of each other, forming a chain of decorators.

## 03. Why it works:
The Decorator design pattern works by extending the functionality of an object dynamically. It works by creating decorator classes that implement the same interface as the original object and contain a reference to the original object. The decorators add new functionalities by delegating the calls to the original object and adding their own behavior before or after the delegation, effectively extending or modifying the behavior of the original object.

## 04. Advantages:

* **Flexible Extension**: The Decorator pattern allows for the dynamic addition of functionalities to an object without modifying its structure or code. Decorators can be easily added, removed, or combined, providing flexible extension capabilities.
* **Open-Closed Principle**: The Decorator pattern follows the Open-Closed Principle, as it allows for extending the behavior of an object without modifying its existing code. New decorators can be added without altering the existing classes or their interfaces.
* **Composability**: Decorators can be stacked on top of each other, forming a chain of decorators. This composability allows for fine-grained control over the added functionalities and enables the creation of complex combinations of behaviors.

## 05.Disadvantages:

* **Increased Complexity**: Implementing the Decorator pattern can introduce additional complexity, especially when dealing with a large number of decorators or complex interaction between decorators. The chain of decorators can become intricate, and the order of their execution may affect the final behavior.
* **Potential Performance Impact**: The use of decorators can introduce a slight performance overhead due to the added indirection and the potential for multiple method calls in the chain of decorators. However, this overhead is typically negligible unless used extensively in performance-critical sections.

## Python example:

In [31]:
class DataPreprocessor:
    """
    Component class representing the data preprocessing pipeline.
    """

    def preprocess(self, data):
        """
        Preprocesses the data.
        """
        raise NotImplementedError

class MissingValueFiller(DataPreprocessor):
    """
    Concrete decorator class for filling missing values in the data.
    """

    def __init__(self, component):
        self.component = component

    def preprocess(self, data):
        """
        Performs missing value filling on the data.
        """
        # Fill missing values in selected columns with appropriate strategies
        data = self.fill_missing_values(data)

        # Call the preprocess method of the component
        if self.component:
            data = self.component.preprocess(data)

        return data

    def fill_missing_values(self, data):
        """
        Fills missing values in selected columns with appropriate strategies.
        """
        # Example: Filling missing values in 'Age' column with median
        data['Age'] = data['Age'].fillna(data['Age'].median())
        return data

class FeatureScaler(DataPreprocessor):
    """
    Concrete decorator class for performing feature scaling on the data.
    """

    def __init__(self, component):
        self.component = component

    def preprocess(self, data):
        """
        Performs feature scaling on the data.
        """
        # Apply feature scaling to selected numeric columns
        data = self.feature_scaling(data)

        # Call the preprocess method of the component
        if self.component:
            data = self.component.preprocess(data)

        return data

    def feature_scaling(self, data):
        """
        Applies feature scaling to selected numeric columns.
        """
        # Example: Applying Min-Max scaling to 'Fare' column
        data['Fare'] = (data['Fare'] - data['Fare'].min()) / (data['Fare'].max() - data['Fare'].min())
        return data

## UML Diagram

[![](https://mermaid.ink/img/pako:eNqtUstqAzEM_BWjU0KTH1h6THMLBAI9GYywtanBj8WWCyXdf693HZaGhPYSXSxrRqMx8gV0NAQdaIc57yyeE3oZRI25InbIeEw0pKgp55jEpaFTvIhhQVamEtcNG2VoyV3z6_d2Kw42ZxvO7-gK7a1zlP5i7wm5JDppnIm_vd0L3bpTygbLSq109EMMFHj9v_mG9VVO-aavPqcBj1_YjNx4fJ6Hpqpyla02Hs6HDXhKHq2pO5wHS-AP8iShq6mhHotjCTKMlYqF4-kraOg4FdpAGaomXbcOXY8uL9U3YzmmpUjz9XD9LNMx_gAce7st?type=png)](https://mermaid.live/edit#pako:eNqtUstqAzEM_BWjU0KTH1h6THMLBAI9GYywtanBj8WWCyXdf693HZaGhPYSXSxrRqMx8gV0NAQdaIc57yyeE3oZRI25InbIeEw0pKgp55jEpaFTvIhhQVamEtcNG2VoyV3z6_d2Kw42ZxvO7-gK7a1zlP5i7wm5JDppnIm_vd0L3bpTygbLSq109EMMFHj9v_mG9VVO-aavPqcBj1_YjNx4fJ6Hpqpyla02Hs6HDXhKHq2pO5wHS-AP8iShq6mhHotjCTKMlYqF4-kraOg4FdpAGaomXbcOXY8uL9U3YzmmpUjz9XD9LNMx_gAce7st)

## Usage example

In [32]:
# Create the data preprocessing pipeline with decorators
preprocessor = MissingValueFiller(FeatureScaler(None))

# Preprocess the data using the pipeline
preprocessed_data = preprocessor.preprocess(titanic_data)

# Display the preprocessed data
preprocessed_data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,FamilySize
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,0.014151,NaN,S,2
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,0.139136,C85,C,2
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,0.015469,NaN,S,1
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,0.103644,C123,S,2
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,0.015713,NaN,S,1

In [33]:
preprocessed_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          891 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
 12  FamilySize   891 non-null    int64
dtypes: float64(2), int64(6), object(5)
memory usage: 90.6+ KB

In this code example, we have a **DataPreprocessor** class representing the component of the data preprocessing pipeline. It defines the common interface for the component and decorators.

The **MissingValueFiller** and **FeatureScaler** classes represent concrete decorator classes. They extend the **DataPreprocessor** class and add specific preprocessing functionalities. Each decorator calls the corresponding preprocessing method and then delegates the preprocessing to the next component in the pipeline.

In the usage example, we create an instance of the MissingValueFiller decorator, passing an instance of the FeatureScaler decorator as the component. This forms the preprocessing pipeline with the decorators stacked on top of each other. We then preprocess the Titanic dataset by calling the preprocess method on the top-level decorator, which triggers the preprocessing process recursively through the decorators. Finally, we display the preprocessed data.

# 10. Structural - Facade

## 01. Problem:
In software development, you often encounter situations where a complex subsystem or set of classes with various dependencies needs to be simplified and presented with a unified, simplified interface. The problem is that interacting directly with the individual components of the subsystem can be cumbersome, requiring deep knowledge of the system's internal structure and dependencies.

## 02. Solution:
The Facade design pattern provides a solution by introducing a simplified interface or facade that hides the complexities of the underlying subsystem. It involves creating a facade class that encapsulates the interactions with the subsystem's components and provides a single entry point for clients to access the subsystem's functionalities. The facade class coordinates the actions and interactions between the subsystem's components, shielding the clients from the details of the subsystem.

## 03. Why it works:
The Facade design pattern works by providing a high-level interface that hides the complexities of the subsystem. It encapsulates the interactions and dependencies between the subsystem's components, allowing clients to interact with the subsystem through a simplified, unified interface. By centralizing the interactions in the facade class, it becomes easier to understand, use, and maintain the subsystem, as clients can work with a consistent and simplified API.

## 04. Advantages:

* **Simplified Interface**: The Facade pattern provides a simplified and unified interface to a complex subsystem. Clients can interact with the subsystem through the facade class without needing to understand the internal structure or dependencies of the subsystem's components.
* **Decoupling**: The Facade pattern decouples the subsystem from its clients by introducing an intermediary facade class. Changes in the subsystem's internal structure or dependencies are isolated within the facade class, minimizing the impact on the client code.
* **Improved Readability and Maintainability**: The Facade pattern improves the readability and maintainability of the codebase by providing a clear, high-level API. It abstracts away the complexities of the subsystem, making the codebase more organized and easier to understand.

## 05. Disadvantages:

* **Limited Flexibility**: The Facade pattern may limit the flexibility or customization options available to clients. The simplified interface provided by the facade class may not expose all the functionalities or configurations of the subsystem's components.
* **Increased Indirection**: The introduction of the facade class adds an extra layer of indirection between clients and the subsystem. This can lead to a small performance overhead due to the additional method calls and abstraction.

## Python example

In [34]:
class DataPreprocessorFacade:
    """
    Facade class providing a simplified interface for data preprocessing tasks.
    """

    def __init__(self, data):
        self.data = data

    def preprocess_data(self):
        """
        Performs common data preprocessing tasks.
        """
        self.remove_duplicates()
        self.fill_missing_values()
        self.normalize_data()
        self.encode_categorical_features()

        # Additional preprocessing steps can be added here

    def remove_duplicates(self):
        """
        Removes duplicate rows from the dataset.
        """
        self.data.drop_duplicates(inplace=True)

    def fill_missing_values(self):
        """
        Fills missing values in selected columns with appropriate strategies.
        """
        # Example: Filling missing values in 'Age' column with median
        self.data['Age'] = self.data['Age'].fillna(self.data['Age'].median())

    def normalize_data(self):
        """
        Normalizes selected numeric columns in the dataset.
        """
        # Example: Normalizing 'Fare' column
        self.data['Fare'] = (self.data['Fare'] - self.data['Fare'].mean()) / self.data['Fare'].std()

    def encode_categorical_features(self):
        """
        Encodes categorical features in the dataset.
        """
        # Example: One-hot encoding 'Embarked' column
        encoded_embarked = pd.get_dummies(self.data['Embarked'], prefix='Embarked')
        self.data = pd.concat([self.data, encoded_embarked], axis=1)
        self.data.drop('Embarked', axis=1, inplace=True)

## UML Diagram

[![](https://mermaid.ink/img/pako:eNptUMtqAzEM_JVFp5TmC_ac9lYo9GoQwtZuBX4ssh1Iw_577U3YNqW6SJ4Zj9BcwSbHMIL1lPNJaFYKJg6tNmQ4UaF35UWT5ZyTvpIlx8P1pun1PCBKlIJ4cE389JtZ9p_YucMDqRzSmdHVxYulwvmRnsR7DJKzxBnP5OtfQUwayMsX_-PNsd-F3XZO2uw9Tkyl6o_JauJtgCMEblbiWg7bYQbKJwc2MLbR8UTVFwMmrk1KtaSPS7QwFq18hLq07XxPDsaJfN7RFycl6Q7y9ny7B97b-g2f-Xva?type=png)](https://mermaid.live/edit#pako:eNptUMtqAzEM_JVFp5TmC_ac9lYo9GoQwtZuBX4ssh1Iw_577U3YNqW6SJ4Zj9BcwSbHMIL1lPNJaFYKJg6tNmQ4UaF35UWT5ZyTvpIlx8P1pun1PCBKlIJ4cE389JtZ9p_YucMDqRzSmdHVxYulwvmRnsR7DJKzxBnP5OtfQUwayMsX_-PNsd-F3XZO2uw9Tkyl6o_JauJtgCMEblbiWg7bYQbKJwc2MLbR8UTVFwMmrk1KtaSPS7QwFq18hLq07XxPDsaJfN7RFycl6Q7y9ny7B97b-g2f-Xva)

## Usage example

In [35]:
# Create an instance of the DataPreprocessorFacade
preprocessor = DataPreprocessorFacade(titanic_data)

# Perform data preprocessing using the facade
preprocessor.preprocess_data()

# Display the preprocessed data
preprocessor.data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,FamilySize,Embarked_C,Embarked_Q,Embarked_S
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,-0.502163,NaN,2,0,0,1
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,0.786404,C85,2,1,0,0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,-0.488580,NaN,1,0,0,1
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,0.420494,C123,2,0,0,1
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,-0.486064,NaN,1,0,0,1

In [36]:
preprocessor.data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          891 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  FamilySize   891 non-null    int64
 12  Embarked_C   891 non-null    uint8
 13  Embarked_Q   891 non-null    uint8
 14  Embarked_S   891 non-null    uint8
dtypes: float64(2), int64(6), object(4), uint8(3)
memory usage: 93.1+ KB

In this code example, we have a **DataPreprocessorFacade** class representing the facade that provides a simplified interface for common data preprocessing tasks. It encapsulates the interactions with the dataset and coordinates the execution of the preprocessing steps.

The **DataPreprocessorFacade** class has methods such as **remove_duplicates**, **fill_missing_values**, **normalize_data**, and **encode_categorical_features** that perform specific preprocessing tasks on the dataset.

In the usage example, we create an instance of the **DataPreprocessorFacade** class, passing the Titanic dataset as the input. We then call the **preprocess_data** method on the facade to perform the common data preprocessing tasks. Finally, we display the preprocessed data.

# 11. Structural - Flyweight

## 01. Problem:
In software development, you often encounter situations where you need to efficiently represent a large number of objects with similar properties or intrinsic data. The problem is that representing each object individually can consume significant memory and resources, especially when many objects share common state or have overlapping characteristics.

## 02. Solution:
The Flyweight design pattern provides a solution by separating the intrinsic and extrinsic states of objects. It involves creating a flyweight object that represents the shared state among multiple objects. The extrinsic state, which is unique to each object, is stored externally. The flyweight object is shared among multiple objects, reducing memory consumption and improving performance.

## 03. Why it works:
The Flyweight design pattern works by promoting object sharing and reusing. By separating the intrinsic and extrinsic states, the flyweight object can be shared among multiple objects, effectively reducing the memory footprint. The extrinsic state is managed externally and passed to the flyweight objects when needed, enabling multiple objects to reuse the shared state efficiently.

## 04. Advantages:

* **Memory Efficiency**: The Flyweight pattern reduces memory consumption by sharing common state among multiple objects. This is especially useful when dealing with a large number of objects or when memory usage is a concern.
* **Performance Improvement**: By sharing common state, the Flyweight pattern can improve performance by reducing the need for object creation and memory allocation. It can also minimize the overhead associated with redundant state storage and manipulation.
* **Enhanced Scalability**: The Flyweight pattern promotes scalability by allowing the system to handle a large number of objects efficiently. It allows for dynamic addition or removal of flyweight objects without affecting the behavior of other objects.

## 05. Disadvantages:

* **Increased Complexity**: Implementing the Flyweight pattern can introduce additional complexity, as it requires distinguishing between intrinsic and extrinsic states and managing the interaction between them. This complexity can make the codebase harder to understand and maintain, especially for smaller or simpler projects.
* **State Sharing Limitation**: The Flyweight pattern is most effective when the objects have significant common state to share. If the objects have very distinct or unique states, the benefits of sharing may be limited, and the overhead of managing the flyweight objects may outweigh the advantages.

## Python example

In [37]:
class CategoryFlyweight:
    """
    Flyweight class representing a category.
    """

    def __init__(self, category):
        self.category = category
        
class CategoricalDataFlyweightFactory:
    """
    Flyweight factory class managing the flyweight objects.
    """

    def __init__(self):
        self.categories = {}

    def get_category(self, category):
        """
        Retrieves the flyweight object for the given category.
        If it doesn't exist, creates a new one.
        """
        if category not in self.categories:
            self.categories[category] = CategoryFlyweight(category)
        return self.categories[category]

class TitanicDataProcessor:
    """
    Data processor class utilizing the Flyweight pattern to optimize memory usage for categorical data.
    """

    def __init__(self):
        self.flyweight_factory = CategoricalDataFlyweightFactory()

    def process_data(self, data):
        """
        Processes the Titanic dataset by optimizing memory usage for categorical data.
        """
        processed_data = data.copy()

        # Convert categorical columns to flyweight objects
        categorical_columns = ['Pclass', 'Sex', 'Embarked']
        for column in categorical_columns:
            processed_data[column] = processed_data[column].apply(self.get_flyweight_category)

        return processed_data

    def get_flyweight_category(self, category):
        """
        Retrieves the flyweight object for the given category.
        """
        return self.flyweight_factory.get_category(category)

## UML Diagram

[![](https://mermaid.ink/img/pako:eNqNUk1rwzAM_StBp3ZrDruGscu63gaD7WgwwlFSQ2IXW2GELv99dpKGQpqmOvhD1nt6lnQGZXOCDFSF3u81lg5rYZJgvSd5R6bSuvZQtb-kyyMn5-E52nMipTaapdyoMW47vHbC3GDRCqs9Mk5kB1QcQAuc22tvSSwvSVay_WhGo1XM9OWsIu-teyTFaQiWeQBu4jITUFyEr0uZF-71L03XKjFgb37ApunbOvwOQcQLeBIw17YsWsBLANyFXgEXG_wADeygJlejzsM49t0SwEeqSUAWjjkV2FQsQJguhGLD9rs1CjJ2De2gOYWG0TjAkBVY-cn7kesgYnJSf_0c5z5u3T9pKARl?type=png)](https://mermaid.live/edit#pako:eNqNUk1rwzAM_StBp3ZrDruGscu63gaD7WgwwlFSQ2IXW2GELv99dpKGQpqmOvhD1nt6lnQGZXOCDFSF3u81lg5rYZJgvSd5R6bSuvZQtb-kyyMn5-E52nMipTaapdyoMW47vHbC3GDRCqs9Mk5kB1QcQAuc22tvSSwvSVay_WhGo1XM9OWsIu-teyTFaQiWeQBu4jITUFyEr0uZF-71L03XKjFgb37ApunbOvwOQcQLeBIw17YsWsBLANyFXgEXG_wADeygJlejzsM49t0SwEeqSUAWjjkV2FQsQJguhGLD9rs1CjJ2De2gOYWG0TjAkBVY-cn7kesgYnJSf_0c5z5u3T9pKARl)

## Usage example

In [38]:
# Create an instance of the TitanicDataProcessor
data_processor = TitanicDataProcessor()

# Process the data using the Flyweight pattern
processed_data = data_processor.process_data(titanic_data)

# Display the processed data
processed_data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,FamilySize
0,1,0,<__main__.CategoryFlyweight object at 0x7928f4...,"Braund, Mr. Owen Harris",<__main__.CategoryFlyweight object at 0x7928f4...,22.0,1,0,A/5 21171,-0.502163,NaN,<__main__.CategoryFlyweight object at 0x7928f4...,2
1,2,1,<__main__.CategoryFlyweight object at 0x7928f4...,"Cumings, Mrs. John Bradley (Florence Briggs Th...",<__main__.CategoryFlyweight object at 0x7928f4...,38.0,1,0,PC 17599,0.786404,C85,<__main__.CategoryFlyweight object at 0x7928f4...,2
2,3,1,<__main__.CategoryFlyweight object at 0x7928f4...,"Heikkinen, Miss. Laina",<__main__.CategoryFlyweight object at 0x7928f4...,26.0,0,0,STON/O2. 3101282,-0.488580,NaN,<__main__.CategoryFlyweight object at 0x7928f4...,1
3,4,1,<__main__.CategoryFlyweight object at 0x7928f4...,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",<__main__.CategoryFlyweight object at 0x7928f4...,35.0,1,0,113803,0.420494,C123,<__main__.CategoryFlyweight object at 0x7928f4...,2
4,5,0,<__main__.CategoryFlyweight object at 0x7928f4...,"Allen, Mr. William Henry",<__main__.CategoryFlyweight object at 0x7928f4...,35.0,0,0,373450,-0.486064,NaN,<__main__.CategoryFlyweight object at 0x7928f4...,1

In [39]:
processed_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 891 entries, 0 to 890
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    object
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          891 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     891 non-null    object
 12  FamilySize   891 non-null    int64
dtypes: float64(2), int64(5), object(6)
memory usage: 97.5+ KB

In this code example, we have a **CategoryFlyweight** class representing the flyweight object that represents a category. The **CategoricalDataFlyweightFactory** class serves as the flyweight factory, managing the creation and retrieval of flyweight objects.

The **TitanicDataProcessor** class utilizes the flyweight pattern to optimize memory usage for categorical data in the Titanic dataset. It maintains an instance of the **CategoricalDataFlyweightFactory** and processes the dataset by converting categorical columns to flyweight objects using the **get_flyweight_category** method.

In the usage example, we create an instance of the **TitanicDataProcessor** class. We then call the process_data method, passing the Titanic dataset as input, which optimizes the memory usage for categorical data using the flyweight pattern. Finally, we display the processed data.

# 12. Structural - Proxy

## 01. Problem:
In software development, you often encounter situations where you need to control access to an object or provide additional functionality without modifying its underlying implementation. The problem is that direct access to the object may not be appropriate or desired due to security concerns, resource limitations, or the need for additional operations before or after accessing the object.

## 02. Solution:
The Proxy design pattern provides a solution by introducing a proxy object that acts as a surrogate or placeholder for the real object. The proxy object controls access to the real object and can add extra behavior or perform additional operations before or after forwarding the request to the real object. The proxy object mimics the interface of the real object, allowing clients to interact with it in a transparent manner.

## 03. Why it works:
The Proxy design pattern works by introducing an intermediary object between the client and the real object. The proxy object provides a level of indirection, allowing it to control access to the real object and perform additional operations as necessary. Clients interact with the proxy object as if it were the real object, unaware of the underlying mechanisms and modifications made by the proxy.

## 04. Advantages:

* **Access Control**: The Proxy pattern enables fine-grained control over access to the real object. The proxy object can enforce access restrictions or authentication mechanisms, ensuring that clients adhere to defined rules and security requirements.
* **Resource Management**: Proxies can manage the creation and destruction of expensive or limited resources associated with the real object. This allows for efficient resource utilization and prevents unnecessary resource allocation.
* **Additional Functionality**: Proxies can add extra functionality or perform additional operations before or after accessing the real object. This can include caching, logging, lazy initialization, or access optimization, providing enhanced capabilities without modifying the real object.

## 05. Disadvantages:

* **Increased Complexity**: Introducing a proxy object can increase the overall complexity of the system. The proxy needs to replicate the interface of the real object, potentially leading to a larger codebase and more intricate design.
* **Performance Overhead**: The use of a proxy object can introduce a performance overhead due to the additional method calls and indirection. However, the impact is typically minimal unless the proxy is performing complex operations or if the system heavily relies on proxy instances.

## Python example

In [40]:
class TitanicDataset:
    """
    Real object class representing the Titanic dataset.
    """

    def __init__(self):
        self._data = None

    def load_data(self):
        """
        Loads the Titanic dataset from a source (e.g., CSV file).
        """
        if self._data is None:
            # Load the dataset from a source (e.g., CSV file)
            self._data = pd.read_csv('/kaggle/input/titanic/train.csv')

    def get_data(self):
        """
        Returns the Titanic dataset.
        """
        return self._data

class TitanicDatasetProxy:
    """
    Proxy class controlling access to the Titanic dataset and adding caching functionality.
    """

    def __init__(self):
        self._dataset = TitanicDataset()

    def get_data(self):
        """
        Returns the Titanic dataset, loading it if necessary and caching the result.
        """
        if self._dataset.get_data() is None:
            self._dataset.load_data()
        return self._dataset.get_data()

## UML Diagram

[![](https://mermaid.ink/img/pako:eNqFkU0LwjAMhv9KyUlxO3jdwdM8CoIeCyWscRa2VroMFNl_t6vDj7lhLk2fvOnbkDsUThNkUFTYNLnB0mMtrQgRiTgaRmuKHBkbYnF_1vpIhdKBvsFKKGWsYaUWy09aOdRR-o1L4i_aSTtvvPfueptwD6X_H5h1mvJwaboZFabl4lcYX5hRS1hLiD3PbGwBCdTkazQ6bCMOKoHPVJOELKSaTthWLEHaLkixZXe42QIy9i0l0F7CgDTsD7ITVs2LbrVh51-Q4nU3rL0_ugcjhKPV?type=png)](https://mermaid.live/edit#pako:eNqFkU0LwjAMhv9KyUlxO3jdwdM8CoIeCyWscRa2VroMFNl_t6vDj7lhLk2fvOnbkDsUThNkUFTYNLnB0mMtrQgRiTgaRmuKHBkbYnF_1vpIhdKBvsFKKGWsYaUWy09aOdRR-o1L4i_aSTtvvPfueptwD6X_H5h1mvJwaboZFabl4lcYX5hRS1hLiD3PbGwBCdTkazQ6bCMOKoHPVJOELKSaTthWLEHaLkixZXe42QIy9i0l0F7CgDTsD7ITVs2LbrVh51-Q4nU3rL0_ugcjhKPV)

## Usage example

In [41]:

# Create an instance of the TitanicDatasetProxy
dataset_proxy = TitanicDatasetProxy()

# Access the Titanic dataset through the proxy
data = dataset_proxy.get_data()

# Display the dataset
data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In this code example, we have a **TitanicDataset** class representing the real object that encapsulates the Titanic dataset. The class has methods to load and retrieve the dataset.

The **TitanicDatasetProxy** class serves as the proxy object that controls access to the real dataset. It maintains an instance of the **TitanicDataset** and adds caching functionality to avoid repeated loading of the dataset.

In the usage example, we create an instance of the **TitanicDatasetProxy** class. When we call the **get_data** method on the proxy, it checks if the dataset is already loaded. If not, it delegates the call to the real object to load the dataset and caches the result. Subsequent calls to get_data will return the cached dataset without performing the loading operation again.

# 13. Behavioral - Interpreter

## 01. Problem:
In software development, you often encounter scenarios where you need to interpret or evaluate structured textual expressions or rules. The problem is that implementing a grammar or rule set directly in code can be complex, inflexible, and difficult to maintain, especially when the grammar or rule set is large or subject to frequent changes.

## 02. Solution:
The Interpreter design pattern provides a solution by defining a language, grammar, or set of rules using a combination of classes and objects. It involves creating interpreter classes that represent the grammar rules or expressions and provide methods for their interpretation or evaluation. These interpreter classes work together to parse, evaluate, and execute the structured expressions.

## 03. Why it works:
The Interpreter design pattern works by separating the grammar or rule set from its implementation. It allows you to define the rules or expressions using a structured representation that can be easily modified or extended. The interpreter classes interpret or evaluate these expressions based on the defined grammar, allowing you to build complex behavior by combining simple interpreters.

## 04. Advantages:

* **Extensibility**: The Interpreter pattern enables easy extension of the grammar or rule set. New rules or expressions can be added by creating new interpreter classes without modifying the existing ones, providing flexibility and maintainability.
* **Separation of Concerns**: The pattern separates the grammar or rule set from its implementation, promoting a clear separation of concerns. The interpreter classes handle the interpretation or evaluation of the expressions, while the client code focuses on utilizing the interpreters to achieve the desired behavior.
* **Readability and Maintainability**: The Interpreter pattern can improve the readability and maintainability of code by providing a structured and modular approach to representing and executing expressions. The grammar rules are defined in a clear and concise manner, making the codebase easier to understand and modify.

## 05. Disadvantages:

* **Complexity**: Implementing the Interpreter pattern can introduce additional complexity, especially when dealing with large or complex grammars. Defining and coordinating multiple interpreter classes may require a good understanding of the grammar and careful design to ensure efficient parsing and interpretation.
* **Performance Overhead**: Depending on the complexity of the grammar and the size of the input expressions, the Interpreter pattern may introduce a performance overhead. The interpretation and evaluation process can involve multiple method calls and object interactions, which may impact the overall performance, especially for computationally intensive tasks.

## Python example

In [42]:

class AgeRuleInterpreter:
    """
    Interpreter class for evaluating age-based selection rules.
    """

    def evaluate(self, data, rule):
        """
        Evaluates the age-based selection rule on the dataset.
        """
        passengers = []
        for index, row in data.iterrows():
            if eval(rule):
                passengers.append(row['Name'])
        return passengers

## UML Diagram

[![](https://mermaid.ink/img/pako:eNo9T7sOwjAM_JXIE4h-QTYkGBhYYM1iNddSKUkr10FCVf-d9KHe4Mf5_Jqo7j3IUh14HG8dt8LRJVOwMuba4pUDHkkhg6BYM231BReDL4fMipNn5cpI0Z63-uwSVRQhkTtfNqxtjvSDCEe2hB4N56COXJqLlLP271-qyapkVJSHMhP7TWQbDuPB3n2nvRwk1vS5v7K4-Q_WbEkl?type=png)](https://mermaid.live/edit#pako:eNo9T7sOwjAM_JXIE4h-QTYkGBhYYM1iNddSKUkr10FCVf-d9KHe4Mf5_Jqo7j3IUh14HG8dt8LRJVOwMuba4pUDHkkhg6BYM231BReDL4fMipNn5cpI0Z63-uwSVRQhkTtfNqxtjvSDCEe2hB4N56COXJqLlLP271-qyapkVJSHMhP7TWQbDuPB3n2nvRwk1vS5v7K4-Q_WbEkl)

## Usage example

In [43]:
# Create an instance of the AgeRuleInterpreter
rule_interpreter = AgeRuleInterpreter()

# Define the selection rule
age_rule = "row['Age'] >= 18 and row['Age'] <= 20"

# Evaluate the rule on the dataset
selected_passengers = rule_interpreter.evaluate(titanic_data, age_rule)

# Display the selected passengers
print("Selected Passengers:")
for passenger in selected_passengers:
    print(f'- {passenger}')

Selected Passengers:
- Saundercock, Mr. William Henry
- Fortune, Mr. Charles Alexander
- Vander Planke, Miss. Augusta Maria
- Devaney, Miss. Margaret Delia
- Arnold-Franchi, Mrs. Josef (Josefine Franchi)
- Crease, Mr. Ernest James
- Andreasson, Mr. Paul Edvin
- Jussila, Miss. Katriina
- Coelho, Mr. Domingos Fernandeo
- Newsom, Miss. Helen Monypeny
- Burke, Mr. Jeremiah
- Andrew, Mr. Edgardo Samuel
- Nicholls, Mr. Joseph Charles
- Klasen, Mr. Klas Albin
- Carbines, Mr. William
- Andersen-Jensen, Miss. Carla Christine Nielsine
- Cohen, Mr. Gurshon "Gus"
- Mellors, Mr. William John
- Fahlstrom, Mr. Arne Jonas
- Pengelly, Mr. Frederick William
- Dorking, Mr. Edward Arthur
- Bishop, Mrs. Dickinson H (Helen Walton)
- Johnson, Mr. William Cahoone Jr
- Ryerson, Miss. Emily Borie
- Wiklund, Mr. Jakob Alfred
- Beavan, Mr. William Thomas
- Betros, Mr. Tannous
- Gustafsson, Mr. Karl Gideon
- Davies, Mr. Charles Henry
- Oreskovic, Miss. Marija
- Silven, Miss. Lyyli Karoliina
- Rosblom, Mr. Viktor Richard
- Phillips, Miss. Kate Florence ("Mrs Kate Louise Phillips Marshall")
- Hampe, Mr. Leon
- Penasco y Castellana, Mr. Victor de Satode
- Beane, Mrs. Edward (Ethel Clarke)
- Stoytcheff, Mr. Ilia
- Patchett, Mr. George
- Taussig, Miss. Ruth
- Nakid, Mr. Sahid
- Jensen, Mr. Hans Peder
- Cor, Mr. Liudevit
- Doling, Miss. Elsie
- Hegarty, Miss. Hanora "Nora"
- Lindqvist, Mr. Eino William
- Edvardsson, Mr. Gustaf Hjalmar
- Turja, Miss. Anna Sofia
- Olsvigen, Mr. Thor Anderson
- Dakic, Mr. Branko
- Fischer, Mr. Eberhard Thelander
- Astor, Mrs. John Jacob (Madeleine Talmadge Force)
- Barbara, Miss. Saiide
- Soholt, Mr. Peter Andreas Lauritz Andersen
- Oreskovic, Mr. Luka
- Marvin, Mr. Daniel Warner
- Bailey, Mr. Percy Andrew
- Barah, Mr. Hanna Assi
- Myhrman, Mr. Pehr Fabian Oliver Malkolm
- Sjoblom, Miss. Anna Sofia
- Pettersson, Miss. Ellen Natalia
- Allum, Mr. Owen George
- Alhomaki, Mr. Ilmari Rudolf
- Aks, Mrs. Sam (Leah Rosen)
- Gustafsson, Mr. Alfred Ossian
- Petroff, Mr. Nedelio
- Graham, Miss. Margaret Edith

In this code example, we have an **AgeRuleInterpreter** class representing the interpreter for evaluating age-based selection rules. The evaluate method takes a dataset and a rule as input and evaluates the rule on each row of the dataset. If the rule evaluates to True for a particular row, the corresponding passenger's name is added to the passengers list.

In the usage example, we create an instance of the **AgeRuleInterpreter** class. We define an age-based selection rule using a string expression, where the rule selects passengers whose age is between 18 and 20. We then call the evaluate method, passing the Titanic dataset and the defined rule, to evaluate the rule on the dataset. Finally, we display the names of the selected passengers.

# 14. Behavioral - Template Method

## 01. Problem:
In software development, you often encounter situations where you need to define the overall structure or algorithm of an operation, but allow certain steps or details to be implemented by subclasses or specific implementations. The problem is that directly implementing the entire algorithm in a single class can lead to code duplication, lack of flexibility, and difficulty in managing variations or customization.

## 02. Solution:
The Template Method design pattern provides a solution by defining the skeleton of an algorithm in a base class, while delegating the implementation of specific steps to subclasses. It involves creating an abstract base class that provides a template method defining the overall algorithm structure. The template method calls several abstract or hook methods that subclasses must implement to customize or extend the algorithm's behavior.

## 03. Why it works:
The Template Method design pattern works by separating the high-level algorithm from the specific implementations of its steps. The base class defines the common structure and controls the overall flow of the algorithm through the template method. Subclasses can provide their own implementations for the abstract or hook methods, allowing customization and extension while adhering to the algorithm's structure.

## 04. Advantages:

* **Code Reusability**: The Template Method pattern promotes code reuse by providing a common algorithm structure in the base class. Subclasses can focus on implementing specific steps without duplicating the entire algorithm.
* **Flexibility and Customization**: The pattern allows for flexibility and customization by letting subclasses override or extend specific steps of the algorithm. Subclasses can tailor the behavior to their specific needs without modifying the overall algorithm.
* **Encapsulation**: The Template Method pattern encapsulates the algorithm's structure in the base class, hiding the details of individual steps. This improves code organization, readability, and maintainability.

## 05. Disadvantages:

* **Limited Runtime Flexibility**: Once the algorithm's structure is defined in the base class, it may be challenging to modify or extend the structure dynamically at runtime. Changes to the algorithm's structure typically require modifications to the base class and its subclasses.
* **Potential Tight Coupling**: The Template Method pattern may lead to tight coupling between the base class and its subclasses. Subclasses need to adhere to the structure and contract defined by the base class, which can limit flexibility and make the codebase more coupled.

## Python example:

In [44]:
class FeatureEngineeringTemplate:
    """
    Abstract base class representing a template for feature engineering.
    """

    def __init__(self, data):
        self.data = data

    def execute_feature_engineering(self):
        """
        Template method defining the overall feature engineering algorithm.
        """
        self.load_data()
        self.clean_data()
        self.extract_features()
        self.transform_features()

    def load_data(self):
        """
        Abstract method to load the dataset.
        """
        raise NotImplementedError("Subclasses must implement load_data().")

    def clean_data(self):
        """
        Abstract method to clean the dataset.
        """
        raise NotImplementedError("Subclasses must implement clean_data().")

    def extract_features(self):
        """
        Abstract method to extract features from the dataset.
        """
        raise NotImplementedError("Subclasses must implement extract_features().")

    def transform_features(self):
        """
        Abstract method to transform features in the dataset.
        """
        raise NotImplementedError("Subclasses must implement transform_features().")

class FeatureEngineering1(FeatureEngineeringTemplate):
    """
    Concrete subclass implementing a specific feature engineering technique.
    """

    def load_data(self):
        """
        Implement the data loading step for this specific technique.
        """
        print("Loading data using Feature Engineering 1...")

    def clean_data(self):
        """
        Implement the data cleaning step for this specific technique.
        """
        print("Cleaning data using Feature Engineering 1...")

    def extract_features(self):
        """
        Implement the feature extraction step for this specific technique.
        """
        print("Extracting features using Feature Engineering 1...")

    def transform_features(self):
        """
        Implement the feature transformation step for this specific technique.
        """
        print("Transforming features using Feature Engineering 1...")

class FeatureEngineering2(FeatureEngineeringTemplate):
    """
    Concrete subclass implementing another feature engineering technique.
    """

    def load_data(self):
        """
        Implement the data loading step for this specific technique.
        """
        print("Loading data using Feature Engineering 2...")

    def clean_data(self):
        """
        Implement the data cleaning step for this specific technique.
        """
        print("Cleaning data using Feature Engineering 2...")

    def extract_features(self):
        """
        Implement the feature extraction step for this specific technique.
        """
        print("Extracting features using Feature Engineering 2...")

    def transform_features(self):
        """
        Implement the feature transformation step for this specific technique.
        """
        print("Transforming features using Feature Engineering 2...")

## UML Diagram

[![](https://mermaid.ink/img/pako:eNrNU7FOAzEM_ZWTp1a0Ax1PjJSNCcZIkZX4jkiJUyWOVNTev5O7lsKJqgMLeEny3vOTbTkHMNEStGA85vzosE8YFDc1JqR5IpSSaMu9Y6LkuH-lsPMo1BxOujHuGq0dO9F6YVFw-Z2hPZkipLuTk6Yvq8VM6CNaPabPYeMJ-QpOe0lo5NM3z9nKce5iCj_4QfHtBu_nnf2XsjZ_W9aNRXg4rtfX5vjbxI1iWEGgFNDZuptT3wrkjQIpaOvVUofFiwLFQ5VikfjyzgZaSYVWUHZ1AHTeZmg79PmCbq2TmC4gTc_n8ycYj-EDzW78JA?type=png)](https://mermaid.live/edit#pako:eNrNU7FOAzEM_ZWTp1a0Ax1PjJSNCcZIkZX4jkiJUyWOVNTev5O7lsKJqgMLeEny3vOTbTkHMNEStGA85vzosE8YFDc1JqR5IpSSaMu9Y6LkuH-lsPMo1BxOujHuGq0dO9F6YVFw-Z2hPZkipLuTk6Yvq8VM6CNaPabPYeMJ-QpOe0lo5NM3z9nKce5iCj_4QfHtBu_nnf2XsjZ_W9aNRXg4rtfX5vjbxI1iWEGgFNDZuptT3wrkjQIpaOvVUofFiwLFQ5VikfjyzgZaSYVWUHZ1AHTeZmg79PmCbq2TmC4gTc_n8ycYj-EDzW78JA)

## Usage example

In [45]:
# Create an instance of FeatureEngineering1 and execute feature engineering
feature_engineering1 = FeatureEngineering1(titanic_data)
feature_engineering1.execute_feature_engineering()

print("-" * 30)

# Create an instance of FeatureEngineering2 and execute feature engineering
feature_engineering2 = FeatureEngineering2(titanic_data)
feature_engineering2.execute_feature_engineering()

Loading data using Feature Engineering 1...
Cleaning data using Feature Engineering 1...
Extracting features using Feature Engineering 1...
Transforming features using Feature Engineering 1...
------------------------------
Loading data using Feature Engineering 2...
Cleaning data using Feature Engineering 2...
Extracting features using Feature Engineering 2...
Transforming features using Feature Engineering 2...

In this code example, we have an abstract base class **FeatureEngineeringTemplate** representing a template for feature engineering. The class defines a template method **execute_feature_engineering()** that serves as the overall algorithm for feature engineering. The template method calls several abstract methods **load_data()**, **clean_data()**, **extract_features()**, and **transform_features()**, which must be implemented by the subclasses.

The **FeatureEngineering1** and **FeatureEngineering2** classes are concrete subclasses that implement specific feature engineering techniques. They provide the necessary implementations for the abstract methods according to their respective techniques.

In the usage example, we create instances of **FeatureEngineering1** and **FeatureEngineering2** and pass the Titanic dataset as input. We then call the **execute_feature_engineering()** method on each instance, which triggers the execution of the feature engineering algorithm defined in the template class. The output demonstrates the execution of each step implemented by the subclasses.

# 15. Behavioral - Chain of Responsibility


## 01. Problem:
In software development, you often encounter scenarios where multiple objects or components need to handle a request or perform an operation sequentially. The problem is that the handling logic may vary, and the responsibility chain may change dynamically. Hard-coding the handling logic or creating tight coupling between objects can make the codebase inflexible and difficult to maintain.

## 02. Solution:
The Chain of Responsibility design pattern provides a solution by decoupling the sender of a request from its receivers. It involves creating a chain of handler objects, where each handler has the ability to handle the request or pass it to the next handler in the chain. The request traverses the chain until it is handled or reaches the end of the chain.

## 03. Why it works:
The Chain of Responsibility design pattern works by separating the sender of a request from its receivers and allowing multiple objects to have a chance to handle the request. Each handler in the chain can decide whether to handle the request or pass it to the next handler. This promotes loose coupling, flexibility, and scalability, as the chain can be modified at runtime, and new handlers can be added or removed without affecting the client code.

## 04. Advantages:

* **Flexibility and Extensibility**: The Chain of Responsibility pattern allows for flexible handling logic and easy extension of the responsibility chain. New handlers can be added or removed dynamically, and the handling sequence can be altered without modifying the client code.
* **Decoupling**: The pattern decouples the sender of a request from its receivers, reducing the dependencies and allowing for independent evolution of both the sender and the receivers.
* **Reusability**: Handlers in the chain can be reused in different chains or scenarios. They can be combined in various ways to handle different types of requests or operations.

## 05. Disadvantages:

* **Overhead and Performance Impact**: The Chain of Responsibility pattern can introduce an overhead due to the traversal of the chain and the potential for multiple objects to handle the request. This can impact performance, especially if the chain is long or if there are many potential handlers for each request.
* **Potential Unhandled Requests**: If the chain is not properly configured or if there is no appropriate handler for a request, it may remain unhandled, leading to unexpected behavior or errors. Proper care must be taken to ensure that all requests are handled appropriately.

## Python example:

In [46]:
class DataPreprocessor:
    """
    Abstract base class representing a data preprocessor in the chain.
    """

    def __init__(self, successor=None):
        self.successor = successor

    def preprocess(self, data):
        """
        Abstract method to perform data preprocessing.
        """
        raise NotImplementedError("Subclasses must implement preprocess().")

    def set_successor(self, successor):
        """
        Sets the successor in the chain.
        """
        self.successor = successor

class MissingValueImputer(DataPreprocessor):
    """
    Concrete subclass implementing missing value imputation.
    """

    def preprocess(self, data):
        """
        Preprocesses the data by imputing missing values.
        """
        print("Imputing missing values...")
        # Perform missing value imputation logic

        # If there is a successor, delegate preprocessing to the successor
        if self.successor:
            self.successor.preprocess(data)

class CategoricalEncoder(DataPreprocessor):
    """
    Concrete subclass implementing categorical variable encoding.
    """

    def preprocess(self, data):
        """
        Preprocesses the data by encoding categorical variables.
        """
        print("Encoding categorical variables...")
        # Perform categorical variable encoding logic

        # If there is a successor, delegate preprocessing to the successor
        if self.successor:
            self.successor.preprocess(data)

## UML Diagram

[![](https://mermaid.ink/img/pako:eNqVUctqwzAQ_BWzp5QmP2Bya3LoIVAI9CQQi7RxBXoY7epQEv97ZSeYNA6F7kXSzM5qpDmDSZagBeOReeewyxhUbGpNSLNDwY9MfU6GmFNuzld2rNdGaxedaL3iYq78yz3dz8KVrXN-cUyiZ9VCP6h47-LgmF3sPtEXeg99EXow8vymhylvKNSl7Az6fRzf_b8hi6_YXjabZ9b-al96UBHWECgHdLYGMTlSIF8USEFbt5ZOWLwoUHGorVgkHb-jgVZyoTWUvpqlW3TQntDzjO6tk5RnkKbj4Zb4uAw_5wOrKw?type=png)](https://mermaid.live/edit#pako:eNqVUctqwzAQ_BWzp5QmP2Bya3LoIVAI9CQQi7RxBXoY7epQEv97ZSeYNA6F7kXSzM5qpDmDSZagBeOReeewyxhUbGpNSLNDwY9MfU6GmFNuzld2rNdGaxedaL3iYq78yz3dz8KVrXN-cUyiZ9VCP6h47-LgmF3sPtEXeg99EXow8vymhylvKNSl7Az6fRzf_b8hi6_YXjabZ9b-al96UBHWECgHdLYGMTlSIF8USEFbt5ZOWLwoUHGorVgkHb-jgVZyoTWUvpqlW3TQntDzjO6tk5RnkKbj4Zb4uAw_5wOrKw)

## Usage example

In [47]:
# Create instances of the preprocessors
missing_value_imputer = MissingValueImputer()
categorical_encoder = CategoricalEncoder()

# Set up the chain of preprocessors
missing_value_imputer.set_successor(categorical_encoder)

# Preprocess the data using the chain
missing_value_imputer.preprocess(titanic_data)

# Display the preprocessed data
titanic_data.head()

Imputing missing values...
Encoding categorical variables...

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,FamilySize
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,-0.502163,NaN,S,2
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,0.786404,C85,C,2
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,-0.488580,NaN,S,1
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,0.420494,C123,S,2
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,-0.486064,NaN,S,1

In [48]:
titanic_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 891 entries, 0 to 890
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          891 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
 12  FamilySize   891 non-null    int64
dtypes: float64(2), int64(6), object(5)
memory usage: 97.5+ KB

In this code example, we have an abstract base class **DataPreprocessor** representing a data preprocessor in the chain. The class defines the preprocess method, which performs the data preprocessing logic. It also has a set_successor method to set the successor in the chain.

The **MissingValueImputer** and **CategoricalEncoder** classes are concrete subclasses that implement specific data preprocessing tasks. They provide the necessary implementations for the preprocess method, performing the respective preprocessing logic. After completing their task, they delegate the preprocessing to the successor if one is present.

In the usage example, we create instances of the preprocessors and set up the chain by calling set_successor to define the order of preprocessing tasks. We then call the preprocess method on the first preprocessor in the chain, which triggers the preprocessing process. The output demonstrates the execution of each preprocessor in the chain.

# 16. Behavioral - Command

## 01. Problem:
In software development, you often encounter scenarios where you need to decouple the sender of a request from its receiver, allowing you to parameterize clients with different requests and support undoable operations. The problem is that directly invoking operations on objects can tightly couple the sender and receiver, making it challenging to manage different requests or support undo operations.

## 02. Solution:
The Command design pattern provides a solution by encapsulating a request as an object, decoupling the sender from the receiver. It involves creating command objects that encapsulate a specific operation or request along with its parameters. The command objects provide an execute method that triggers the corresponding operation on the receiver object.

## 03. Why it works:
The Command design pattern works by abstracting the sender and receiver through the command object. The sender does not need to know the details of how the request is executed or who the receiver is. It only needs to hold and execute the command object. This loose coupling enables the sender to work with different command objects, allowing for easy parameterization and dynamic composition of requests.

## 04. Advantages:

* **Decoupling**: The Command pattern decouples the sender from the receiver, promoting a more flexible and maintainable codebase. The sender and receiver can evolve independently without affecting each other.
* **Undo/Redo Support**: Command objects can be designed to support undoable operations. By storing the necessary information and logic, the commands can be reversed or reapplied, providing undo and redo functionality.
* **Extensibility**: The pattern allows for easy extension by adding new commands without modifying the existing client code. This makes it straightforward to incorporate new operations or requests.

## 05. Disadvantages:

* **Increased Complexity**: The Command pattern can introduce additional complexity, especially when dealing with a large number of commands and command variations. Managing the command objects and their interactions may require careful design and coordination.
* **Overhead**: Using the Command pattern may introduce a slight performance overhead due to the additional layer of abstraction and the need to create and manage command objects. However, the impact is usually negligible unless the system heavily relies on command invocations.

## Python example:

In [49]:
class DataPreprocessingCommand:
    """
    Abstract base class representing a data preprocessing command.
    """

    def execute(self, data):
        """
        Abstract method to execute the data preprocessing command.
        """
        raise NotImplementedError("Subclasses must implement execute().")

    def undo(self, data):
        """
        Abstract method to undo the data preprocessing command.
        """
        raise NotImplementedError("Subclasses must implement undo().")

class MissingValueImputationCommand(DataPreprocessingCommand):
    """
    Concrete subclass implementing missing value imputation.
    """

    def __init__(self, column):
        self.column = column
        self.previous_values = None

    def execute(self, data):
        """
        Executes missing value imputation on the specified column.
        """
        print(f"Performing missing value imputation for column '{self.column}'...")
        self.previous_values = data[self.column].copy()
        # Perform missing value imputation logic

    def undo(self, data):
        """
        Reverts the missing value imputation for the specified column.
        """
        print(f"Reverting missing value imputation for column '{self.column}'...")
        data[self.column] = self.previous_values

## UML Diagram

[![](https://mermaid.ink/img/pako:eNqlkbFqAzEMhl_FaGpI7gWObE2HDoFCoJOhCFtJDbZ82FJoSe_d67uGcEPapVpkf_4t_ZYv4LIn6MFFrHUX8FQwWTYtZmJ2KPhSaCjZUa2BT485JWRvLj-qKdaGPsip0INv6tXyQNnnJR0tL6vvw1zzFaPScxpUUELmOy0643LUxEsyFDqHrPXtPF2v__Pz6zu3X133t0_LsIFEJWHwbZKzawvyToks9G3p6YgaxYLlsUlRJR8-2UEvRWkDOjRDdJ099EeM9UaffJBcbpDm7f76ZVMavwGyFZPX?type=png)](https://mermaid.live/edit#pako:eNqlkbFqAzEMhl_FaGpI7gWObE2HDoFCoJOhCFtJDbZ82FJoSe_d67uGcEPapVpkf_4t_ZYv4LIn6MFFrHUX8FQwWTYtZmJ2KPhSaCjZUa2BT485JWRvLj-qKdaGPsip0INv6tXyQNnnJR0tL6vvw1zzFaPScxpUUELmOy0643LUxEsyFDqHrPXtPF2v__Pz6zu3X133t0_LsIFEJWHwbZKzawvyToks9G3p6YgaxYLlsUlRJR8-2UEvRWkDOjRDdJ099EeM9UaffJBcbpDm7f76ZVMavwGyFZPX)

## Usage example

In [50]:
# Create commands for missing value imputation
age_imputation_command = MissingValueImputationCommand('Age')
fare_imputation_command = MissingValueImputationCommand('Fare')

# Preprocess the data using the commands
age_imputation_command.execute(titanic_data)
fare_imputation_command.execute(titanic_data)

# Display the preprocessed data
titanic_data.head()

Performing missing value imputation for column 'Age'...
Performing missing value imputation for column 'Fare'...

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,FamilySize
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,-0.502163,NaN,S,2
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,0.786404,C85,C,2
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,-0.488580,NaN,S,1
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,0.420494,C123,S,2
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,-0.486064,NaN,S,1

In [51]:
titanic_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 891 entries, 0 to 890
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          891 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
 12  FamilySize   891 non-null    int64
dtypes: float64(2), int64(6), object(5)
memory usage: 97.5+ KB

In [52]:
# Undo the imputation for 'Age' column
age_imputation_command.undo(titanic_data)

# Display the data after undoing the imputation for 'Age' column
titanic_data.head()

Reverting missing value imputation for column 'Age'...

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,FamilySize
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,-0.502163,NaN,S,2
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,0.786404,C85,C,2
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,-0.488580,NaN,S,1
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,0.420494,C123,S,2
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,-0.486064,NaN,S,1

In [53]:
titanic_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 891 entries, 0 to 890
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          891 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
 12  FamilySize   891 non-null    int64
dtypes: float64(2), int64(6), object(5)
memory usage: 97.5+ KB

In this code example, we have an abstract base class **DataPreprocessingCommand** representing a data preprocessing command. The class defines two abstract methods, execute and undo, which are responsible for executing the command and undoing its effects, respectively.

The **MissingValueImputationCommand** class is a concrete subclass that implements the missing value imputation operation as a command. It takes the name of the column to perform imputation on as input. The execute method performs the missing value imputation logic, while the undo method reverts the imputed values to their previous state.

In the usage example, we create instances of the **MissingValueImputationCommand** for the 'Age' and 'Fare' columns. We then call the execute method on each command to perform missing value imputation on the corresponding columns of the Titanic dataset. The preprocessed data is displayed.

Next, we demonstrate the undo functionality by calling the undo method on the **MissingValueImputationCommand** for the 'Age' column. This reverts the imputed values to their previous state, and the data after undoing the imputation is displayed.

# 17. Behavioral - Iterator

## 01. Problem:
In software development, you often need to traverse or iterate over elements in a collection or aggregate object without exposing its underlying structure. The problem is that different collection types may have different internal structures, and client code may need to be modified when iterating over each type of collection. Additionally, you may need to iterate over the elements of a collection in different ways without modifying the collection itself.

## 02. Solution:
The Iterator design pattern provides a solution by decoupling the traversal or iteration logic from the underlying collection or aggregate object. It involves defining an iterator object that encapsulates the iteration behavior and provides methods for accessing the elements of the collection. The iterator object keeps track of the current position within the collection and provides methods for moving to the next element.

## 03. Why it works:
The Iterator design pattern works by separating the iteration logic from the collection or aggregate object. The iterator provides a standardized interface for accessing elements, abstracting away the specific structure or implementation details of the collection. This allows client code to iterate over different collection types using a consistent interface without needing to modify the client code for each collection type.

## 04. Advantages:

* **Decoupling**: The Iterator pattern decouples the client code from the underlying collection structure, allowing the collection to evolve independently without affecting the client code.
* **Abstraction**: The pattern provides an abstraction layer that hides the internal details of the collection or aggregate object. This promotes code simplicity, maintainability, and code reuse.
* **Multiple Iteration Strategies**: The Iterator pattern allows for the definition of multiple iterator objects for the same collection, each with its own traversal strategy. This provides flexibility in iterating over the elements of a collection in different ways without modifying the collection itself.

## 05. Disadvantages:

* **Limited Navigation**: Iterators typically support sequential navigation, moving forward one element at a time. Random access or backward traversal may not be efficiently supported by all iterator implementations.
* **Performance Overhead**: The Iterator pattern may introduce a slight performance overhead due to the additional layer of abstraction and method calls involved in the iteration process. However, the impact is usually negligible unless the collection is very large or the iteration is performed frequently.

In [54]:
class TitanicDatasetIterator:
    """
    Iterator class for iterating over the Titanic dataset.
    """

    def __init__(self, dataset):
        self.dataset = dataset
        self.current_index = 0

    def __iter__(self):
        """
        Returns itself as an iterator.
        """
        return self

    def __next__(self):
        """
        Returns the next row in the dataset.
        """
        if self.current_index >= len(self.dataset):
            raise StopIteration

        row = self.dataset.iloc[self.current_index]
        self.current_index += 1
        return row

## UML Diagram

[![](https://mermaid.ink/img/pako:eNp1kLEOwkAIhl_lwqSx9gE6OOng4KTjJRdyh3pJS82VS2pq391rq1YHWYAPAvx0YGtHUIAtsWm2Hi8BK80q2UjUyQuyt1sUbEj2QgGlDqqbegZbKzcVv5GNIRCL8eyonQsrZYxPM4xZLH8pUysz7TVPwZ_1ef7YqHemGTKoKFToXVIynqZBrlSRhiKFjs4YS9GguU-tGKU-3tlCISFSBvGWBNBLOxRnLJsP3TmfNnwgjenh9bLB9U-aYmjC?type=png)](https://mermaid.live/edit#pako:eNp1kLEOwkAIhl_lwqSx9gE6OOng4KTjJRdyh3pJS82VS2pq391rq1YHWYAPAvx0YGtHUIAtsWm2Hi8BK80q2UjUyQuyt1sUbEj2QgGlDqqbegZbKzcVv5GNIRCL8eyonQsrZYxPM4xZLH8pUysz7TVPwZ_1ef7YqHemGTKoKFToXVIynqZBrlSRhiKFjs4YS9GguU-tGKU-3tlCISFSBvGWBNBLOxRnLJsP3TmfNnwgjenh9bLB9U-aYmjC)

## Usage example

In [55]:
# Create an instance of the TitanicDatasetIterator
iterator = TitanicDatasetIterator(titanic_data.head(5))

# Iterate over the dataset and perform operations on each row
for row in iterator:
    # Perform operations on the row, such as printing or data manipulation
    print(row['Name'])

    # Example operation: Calculate the average fare for female passengers
    if row['Sex'] == 'female':
        # Perform operation on the row
        # ...
        print(f"- {row['Sex']}")

    # Example operation: Check if the passenger survived
    if row['Survived'] == 1:
        # Perform operation on the row
        # ...
        print(f"- {row['Survived']}")

    # Example operation: Perform other data manipulation or analysis
    # ...

Braund, Mr. Owen Harris
Cumings, Mrs. John Bradley (Florence Briggs Thayer)
- female
- 1
Heikkinen, Miss. Laina
- female
- 1
Futrelle, Mrs. Jacques Heath (Lily May Peel)
- female
- 1
Allen, Mr. William Henry

# 18. Behavioral - Mediator

## 01. Problem:
In software development, you often encounter scenarios where a set of objects need to communicate and interact with each other, but direct coupling between these objects leads to complex dependencies and tight interconnections. The problem is that managing the communication and coordination among multiple objects becomes challenging, resulting in code that is difficult to understand, maintain, and extend.

## 02. Solution:
The Mediator design pattern provides a solution by introducing a mediator object that encapsulates the communication and coordination logic between a set of objects. Instead of direct communication, objects communicate through the mediator, which centralizes the interaction and reduces dependencies between the objects. The mediator promotes loose coupling and simplifies the communication flow.

## 03. Why it works:
The Mediator design pattern works by decoupling objects and centralizing their interaction through the mediator. Objects do not need to know about each other, but only about the mediator. They send requests or notifications to the mediator, which handles the communication, coordination, and routing between the objects. This reduces the complexity of managing direct object-to-object interactions and allows for more flexible and maintainable code.

## 04. Advantages:

* **Decoupling**: The Mediator pattern decouples objects by removing direct dependencies between them. Objects only need to know about the mediator, which simplifies their interactions and reduces coupling.
* **Centralized Control**: The pattern provides a centralized control point for communication and coordination. This makes it easier to manage the interactions between objects and enforce specific policies or rules.
* **Flexibility and Extensibility**: The mediator can be extended or replaced to introduce new behavior or to support different sets of objects. This makes it easier to modify or extend the system without impacting the existing objects.

## 05. Disadvantages:

* **Complexity**: The Mediator pattern introduces an additional layer of abstraction and can increase the complexity of the system. The mediator may become complex if there are many objects and complex communication flows involved.
* **Single Point of Failure**: As the mediator becomes the central communication point, it can become a single point of failure. If the mediator fails or becomes overwhelmed with responsibilities, it can impact the entire system.
* **Performance Overhead**: The use of a mediator can introduce a slight performance overhead due to the additional method calls and indirection involved in the communication process. However, the impact is usually negligible unless the system deals with a large number of objects and frequent interactions.

## Python example

In [56]:
class PreprocessingComponent:
    """
    Abstract base class representing a preprocessing component.
    """

    def __init__(self, mediator):
        self.mediator = mediator

    def preprocess(self, data):
        """
        Abstract method to perform preprocessing on the data.
        """
        raise NotImplementedError("Subclasses must implement preprocess().")

class MissingValueImputer(PreprocessingComponent):
    """
    Concrete subclass representing a missing value imputer.
    """

    def preprocess(self, data):
        """
        Preprocesses the data by imputing missing values.
        """
        print("Imputing missing values...")
        # Perform missing value imputation logic

        # Notify the mediator that preprocessing is complete
        self.mediator.notify(self, data)

class CategoricalEncoder(PreprocessingComponent):
    """
    Concrete subclass representing a categorical encoder.
    """

    def preprocess(self, data):
        """
        Preprocesses the data by encoding categorical variables.
        """
        print("Encoding categorical variables...")
        # Perform categorical variable encoding logic

        # Notify the mediator that preprocessing is complete
        self.mediator.notify(self, data)

class PreprocessingMediator:
    """
    Mediator class that coordinates the preprocessing components.
    """

    def __init__(self, components):
        self.components = components

    def preprocess_data(self, data):
        """
        Preprocesses the data by coordinating the preprocessing components.
        """
        for component in self.components:
            component.preprocess(data)

    def notify(self, component, data):
        """
        Receives notifications from preprocessing components.
        """
        if component == self.components[-1]:
            # All preprocessing components have completed
            self.post_process(data)

    def post_process(self, data):
        """
        Performs any necessary post-processing after all components have completed.
        """
        print("Post-processing data...")
        # Perform post-processing logic

## UML Diagram

[![](https://mermaid.ink/img/pako:eNqVkstqwzAQRX_FzKql8Q-Y0k2aRReBQqErQRiksSuwHkijRUj975UfcWNq01YbSVeaI93LXEA6RVCBbDHGZ41NQCNskcegFK-BfHCSYtS22TvjnSXLxWW804-yMKQ0sgvf2kPh57q7-1HvhL0FH_WAfMc20YvxiSncUv9A2CNT44KW2B5sb-O_gIW342RiaU1eHcd18kkh4xU_HlrHuj4vNe8in7Y-sxHx42dZrqX0e9HPYFZqZr-uLJ82cMLCDgwFg1rlHhmSEcAfZEhAlZeKakwtCxC2y1cxsXs7WwkVh0Q7SD7HQ1NXQVVjG2f1oHR-fRZp2B6nZuyn7gvGg91n?type=png)](https://mermaid.live/edit#pako:eNqVkstqwzAQRX_FzKql8Q-Y0k2aRReBQqErQRiksSuwHkijRUj975UfcWNq01YbSVeaI93LXEA6RVCBbDHGZ41NQCNskcegFK-BfHCSYtS22TvjnSXLxWW804-yMKQ0sgvf2kPh57q7-1HvhL0FH_WAfMc20YvxiSncUv9A2CNT44KW2B5sb-O_gIW342RiaU1eHcd18kkh4xU_HlrHuj4vNe8in7Y-sxHx42dZrqX0e9HPYFZqZr-uLJ82cMLCDgwFg1rlHhmSEcAfZEhAlZeKakwtCxC2y1cxsXs7WwkVh0Q7SD7HQ1NXQVVjG2f1oHR-fRZp2B6nZuyn7gvGg91n)

## Usage example

In [57]:
# Create the preprocessing components
missing_value_imputer = MissingValueImputer(mediator=None)
categorical_encoder = CategoricalEncoder(mediator=None)

# Create the preprocessing mediator and set it as the mediator for the components
mediator = PreprocessingMediator(components=[missing_value_imputer, categorical_encoder])
missing_value_imputer.mediator = mediator
categorical_encoder.mediator = mediator

# Preprocess the data using the mediator
mediator.preprocess_data(titanic_data)

# Display the preprocessed data
titanic_data.head()

Imputing missing values...
Encoding categorical variables...
Post-processing data...

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,FamilySize
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,-0.502163,NaN,S,2
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,0.786404,C85,C,2
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,-0.488580,NaN,S,1
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,0.420494,C123,S,2
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,-0.486064,NaN,S,1

In this code example, we have an abstract base class **PreprocessingComponent** representing a preprocessing component. It defines the preprocess method that performs the preprocessing logic. Each preprocessing component has a reference to the mediator object, allowing them to communicate with it.

The **MissingValueImputer** and **CategoricalEncoder** classes are concrete subclasses representing specific preprocessing components. They implement the preprocess method and notify the mediator when the preprocessing is complete.

The **PreprocessingMediator** class acts as the mediator that coordinates the communication between the preprocessing components. It receives notifications from the components and performs any necessary post-processing after all components have completed.

In the usage example, we load the Titanic dataset and create instances of the preprocessing components. We then create the preprocessing mediator and set it as the mediator for each component. The preprocessing components perform their preprocessing logic and notify

# 19. Behavioral - Memento

## 01. Problem:
In software development, you often encounter scenarios where you need to capture and restore an object's internal state without violating encapsulation. The problem is that directly exposing the internal state or providing public methods for state manipulation can compromise encapsulation and introduce complexity in managing object state changes.

## 02. Solution:
The Memento design pattern provides a solution by introducing three main components: the originator, the memento, and the caretaker. The originator represents the object whose state needs to be captured and restored. The memento is an object that stores the state of the originator. The caretaker is responsible for managing and storing the mementos. The originator creates mementos to save its state, and the caretaker stores and retrieves mementos as needed.

## 03. Why it works:
The Memento design pattern works by encapsulating and externalizing the object's state through mementos. The originator is responsible for creating mementos and restoring its state from a memento when needed. The caretaker manages the mementos, allowing for the saving and retrieval of object states without violating encapsulation.

## 04. Advantages:

* **Encapsulation**: The Memento pattern encapsulates the internal state of an object within mementos, preserving encapsulation and information hiding.
* **Undo/Redo Support**: The pattern allows for the capture and restoration of object states, enabling undo and redo functionality.
* **State History**: The caretaker can store multiple mementos, providing a history of object states that can be navigated and restored as needed.

## 05. Disadvantages:

* **Increased Memory Usage**: The Memento pattern can consume additional memory, especially when storing multiple mementos to support undo/redo or maintaining a large state history.
* **Performance Overhead**: Creating and restoring mementos can introduce a performance overhead, especially if the state being captured is large or if there are frequent state changes.

## Python example

In [58]:
class DatasetMemento:
    """
    Memento class representing the state of the dataset.
    """

    def __init__(self, dataset):
        self.state = dataset.copy()

    def get_state(self):
        """
        Returns the saved state of the dataset.
        """
        return self.state

class DatasetOriginator:
    """
    Originator class representing the dataset.
    """

    def __init__(self, dataset):
        self.dataset = dataset.copy()

    def create_memento(self):
        """
        Creates a memento to save the state of the dataset.
        """
        return DatasetMemento(self.dataset)

    def restore_from_memento(self, memento):
        """
        Restores the dataset from a given memento.
        """
        self.dataset = memento.get_state()

    def preprocess_data(self):
        """
        Preprocesses the dataset.
        """
        print("Performing dataset preprocessing...")
        # Perform dataset preprocessing logic

    def display_data(self):
        """
        Displays the current state of the dataset.
        """
        display(self.dataset.head())

## UML Diagram

[![](https://mermaid.ink/img/pako:eNqFU01rxCAQ_SviKaX7cffQ0_a4dKHXQBjiJBWiBp0UliX_veajrkmFejGZ997Mm1EfvLYSueB1B95fFLQOdGlYWHOEXYDAI11RoyHLHgs2rSPzBITil_JEXlmLVM1o8bLDx9Jk0n841SoDZN22glzgbI3aYShQ6cVZUmj1mnId-pAbq8ZZHRXrvteFRN9WyVTeO-ydrdH7anJUZChS-b6DewbPdHyL-bYNp5WKKVP0ls_4d3rH49v-yMQ6Kf-fZuNKsMGnkg14OsUqgfj0nD3btMHzOUYXjtJ9N_sEUtbE9viBa3QalAxXc9aXnL4CseQifEpsYOio5KUZAxUGsp93U3NBbsADH_owO1wvMxcNdD5G36UKPccgzr_X9Q1M2_gDbJEClQ?type=png)](https://mermaid.live/edit#pako:eNqFU01rxCAQ_SviKaX7cffQ0_a4dKHXQBjiJBWiBp0UliX_veajrkmFejGZ997Mm1EfvLYSueB1B95fFLQOdGlYWHOEXYDAI11RoyHLHgs2rSPzBITil_JEXlmLVM1o8bLDx9Jk0n841SoDZN22glzgbI3aYShQ6cVZUmj1mnId-pAbq8ZZHRXrvteFRN9WyVTeO-ydrdH7anJUZChS-b6DewbPdHyL-bYNp5WKKVP0ls_4d3rH49v-yMQ6Kf-fZuNKsMGnkg14OsUqgfj0nD3btMHzOUYXjtJ9N_sEUtbE9viBa3QalAxXc9aXnL4CseQifEpsYOio5KUZAxUGsp93U3NBbsADH_owO1wvMxcNdD5G36UKPccgzr_X9Q1M2_gDbJEClQ)

## Usage example

In [59]:
# Create an instance of the DatasetOriginator
originator = DatasetOriginator(titanic_data)

# Preprocess the data
originator.preprocess_data()

# Save the current state of the dataset
memento = originator.create_memento()

# Display the current state of the dataset
print("Current state:")
originator.display_data()

# Restore the dataset to its previous state
originator.restore_from_memento(memento)

# Display the restored state of the dataset
print("Restored state:")
originator.display_data()

Performing dataset preprocessing...
Current state:

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,FamilySize
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,-0.502163,NaN,S,2
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,0.786404,C85,C,2
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,-0.488580,NaN,S,1
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,0.420494,C123,S,2
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,-0.486064,NaN,S,1

Restored state:

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,FamilySize
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,-0.502163,NaN,S,2
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,0.786404,C85,C,2
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,-0.488580,NaN,S,1
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,0.420494,C123,S,2
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,-0.486064,NaN,S,1

In this code example, we have a **DatasetMemento** class that represents the state of the dataset. It has a get_state method to retrieve the saved state. The **DatasetOriginator** class represents the dataset and has methods to create a memento and restore the dataset from a memento. It also includes methods for dataset preprocessing and displaying the dataset.

In the usage example, we load the Titanic dataset and create an instance of the **DatasetOriginator** with the initial dataset state. We then preprocess the dataset and create a memento using the create_memento method to save the current state. The **display_data** method is used to display the current state of the dataset.

Next, we restore the dataset to its previous state using the **restore_from_memento** method, passing in the memento. Finally, we display the restored state of the dataset.

# 20. Behavioral - Observer

## 01. Problem:
In software development, you often encounter scenarios where multiple objects need to be notified and updated when the state of another object changes. The problem is that establishing direct dependencies between these objects can lead to tight coupling and code that is difficult to maintain, extend, and reuse.

## 02. Solution:
The Observer design pattern provides a solution by defining a one-to-many dependency between objects, where the subject (or observable) maintains a list of observers (or subscribers) and notifies them automatically when its state changes. The observers can then update themselves based on the new state of the subject.

## 03. Why it works:
The Observer design pattern works by decoupling the subject and observers, allowing them to vary independently. The subject only needs to know about the abstract Observer interface, while observers implement this interface to receive notifications. This loose coupling enables flexible and dynamic communication between objects.

## 04. Advantages:

* **Decoupling**: The Observer pattern decouples the subject and observers, reducing direct dependencies and improving code maintainability, extensibility, and reusability.
* **Flexibility**: New observers can be added or existing ones can be removed without modifying the subject. Similarly, subjects can change without affecting the observers, as long as they adhere to the Observer interface.
* **Event-driven Architecture**: The Observer pattern facilitates event-driven architecture, where objects communicate through events and notifications, enabling loosely coupled and highly modular systems.

## 05. Disadvantages:

* **Unintended Updates**: Observers may receive unnecessary or redundant updates if the subject's state changes frequently or if the update mechanism is not properly managed.
* **Performance Impact**: Notifying a large number of observers can impact performance, especially if observers perform computationally expensive operations or if the subject updates frequently. Care should be taken to optimize the notification process if performance is a concern.

## Python example

In [60]:
class Subject:
    """
    Subject class representing the dataset.
    """

    def __init__(self):
        self.observers = []

    def attach(self, observer):
        """
        Attaches an observer to the subject.
        """
        self.observers.append(observer)

    def detach(self, observer):
        """
        Detaches an observer from the subject.
        """
        self.observers.remove(observer)

    def notify(self, event):
        """
        Notifies all observers about the event.
        """
        for observer in self.observers:
            observer.update(event)

class SurvivalRateObserver:
    """
    Observer class representing an observer of the survival rate.
    """

    def update(self, event):
        """
        Updates the observer with the event.
        """
        if event == "survived":
            print("Survival rate increased.")
            # Perform observer-specific logic for the event

        if event == "not survived":
            print("Survival rate decreased.")
            # Perform observer-specific logic for the event

## UML Diagram

[![](https://mermaid.ink/img/pako:eNqlkrFuwyAQhl8F3ZQq8QswdGrHqlI9lg4XOBMqGyI4LEWR373EsWNH7RCpLBy_vvv5xXEGHQyBBN1iSi8ObcROeVHWqIg6779JszhfxcuqRNgnij3FJMX7VH5-LcBWIDPqw2bmFuxJij44s2YNPc76wK45bagnz1Ikjs7bO2xQfp1-tlrH34p8NMj0uEudY-96bD9K138d5_esquclnRRobSRbPNJv7M_r71tgBx3FDp0poxyTKeADdaRAltJQg7llBcoPBcXMoT55DZJjph1c00_DB9lgm27qq3Ec4k2k8fg2_ZnLNvwA98G9zw?type=png)](https://mermaid.live/edit#pako:eNqlkrFuwyAQhl8F3ZQq8QswdGrHqlI9lg4XOBMqGyI4LEWR373EsWNH7RCpLBy_vvv5xXEGHQyBBN1iSi8ObcROeVHWqIg6779JszhfxcuqRNgnij3FJMX7VH5-LcBWIDPqw2bmFuxJij44s2YNPc76wK45bagnz1Ikjs7bO2xQfp1-tlrH34p8NMj0uEudY-96bD9K138d5_esquclnRRobSRbPNJv7M_r71tgBx3FDp0poxyTKeADdaRAltJQg7llBcoPBcXMoT55DZJjph1c00_DB9lgm27qq3Ec4k2k8fg2_ZnLNvwA98G9zw)

## Usage example

In [61]:
# Create an instance of the Subject
dataset_subject = Subject()

# Create instances of the SurvivalRateObserver
observer1 = SurvivalRateObserver()
observer2 = SurvivalRateObserver()

# Attach the observers to the subject
dataset_subject.attach(observer1)
dataset_subject.attach(observer2)

# Simulate an event by notifying the observers
dataset_subject.notify("survived")

# Detach an observer from the subject
dataset_subject.detach(observer2)

# Simulate another event
dataset_subject.notify("not survived")

Survival rate increased.
Survival rate increased.
Survival rate decreased.

In this code example, we have a **Subject** class representing the dataset. It has methods to attach and detach observers, as well as notify all observers about events. The **SurvivalRateObserver** class represents an observer that tracks the survival rate and performs observer-specific logic when notified.

In the usage example, we load the Titanic dataset and create an instance of the **Subject**. We also create instances of the **SurvivalRateObserver**. We attach the observers to the subject using the attach method. Then, we simulate an event by notifying the observers with the "survived" event. Each observer can perform specific logic in response to the event. We can detach an observer using the detach method. Finally, we simulate another event by notifying the remaining observer with the "not survived" event.

# 21. Behavioral - State

## 01. Problem:
In software development, you often encounter scenarios where an object's behavior changes based on its internal state. The problem is that implementing conditional statements or switch-case statements to manage different behaviors can lead to complex and tightly coupled code that is difficult to maintain, extend, and understand.

## 02. Solution:
The State design pattern provides a solution by encapsulating each behavior in a separate state object and allowing the object to dynamically change its behavior by switching between these states. The object delegates the behavior to its current state object, decoupling the behavior from the object itself.

## 03. Why it works:
The State design pattern works by representing each behavior as a separate state class. The object that exhibits the behavior maintains a reference to its current state object and delegates method calls to the state object. When the object's state needs to change, it switches to a different state object. This approach enables the object to have different behaviors without altering its own implementation.

## 04. Advantages:

* **Encapsulated Behavior**: Each state is encapsulated within its own class, promoting better organization and separation of concerns. Each state object can be developed and tested independently.
* **Simplified Object**: The State pattern simplifies the object by removing conditional logic or switch-case statements, resulting in cleaner and more maintainable code.
* **Dynamic Behavior**: The object can dynamically change its behavior by switching between different states at runtime, allowing for flexible and extensible behavior changes.

## 05. Disadvantages:

* **Increased Number of Classes**: Implementing the State pattern may introduce a larger number of classes, especially if there are many different states and complex behavior variations.
* **State Transition Logic**: The responsibility of managing state transitions may become complex, especially if there are complex dependencies or specific rules for switching between states.

## Python example

In [62]:
class PreprocessingState:
    """
    Abstract base class representing a preprocessing state.
    """

    def preprocess(self, data):
        """
        Abstract method to perform preprocessing based on the state.
        """
        raise NotImplementedError("Subclasses must implement preprocess().")

class SimplePreprocessingState(PreprocessingState):
    """
    Concrete subclass representing a simple preprocessing state.
    """

    def preprocess(self, data):
        """
        Preprocesses the data using a simple strategy.
        """
        print("Performing simple preprocessing...")
        # Perform simple preprocessing logic

class AdvancedPreprocessingState(PreprocessingState):
    """
    Concrete subclass representing an advanced preprocessing state.
    """

    def preprocess(self, data):
        """
        Preprocesses the data using an advanced strategy.
        """
        print("Performing advanced preprocessing...")
        # Perform advanced preprocessing logic

class PreprocessingStateMachine:
    """
    State machine class that manages the preprocessing states.
    """

    def __init__(self):
        self.states = {
            "simple": SimplePreprocessingState(),
            "advanced": AdvancedPreprocessingState()
        }
        self.current_state = self.states["simple"]

    def set_state(self, state):
        """
        Sets the current preprocessing state.
        """
        self.current_state = self.states[state]

    def preprocess_data(self, data):
        """
        Preprocesses the data based on the current state.
        """
        self.current_state.preprocess(data)

## UML Diagram

[![](https://mermaid.ink/img/pako:eNqtUk1rwzAM_StGp5Y1f8DsMtiOhUGuhiJstTE4dvBHoXT573XcLKRbsl2qi229p4f0rCtIpwg4SIMhvGs8eWyFZTlKhn166ryTFIK2pzpiJHa940O8sG7CNwojcob2suXs7LS603ph53q1bjtDz1Z9U2e0ktSzdX_r7VE22j7IViwMSOCsMMIckcl7svFQGHxBb95doJG4Gekh-sx7aPDnHIdhjv-GWbDl9auqVj_j76p1s9fqvk1zuXpBlbPGGZV9gx205FvUKm9kcVhAbKglATxfFR0xmShA2D5TMUVXX6wEHn2iHaQu20DjDgM_oglT9kPp6PyUpPLcj6s_HP0NmhsH1A?type=png)](https://mermaid.live/edit#pako:eNqtUk1rwzAM_StGp5Y1f8DsMtiOhUGuhiJstTE4dvBHoXT573XcLKRbsl2qi229p4f0rCtIpwg4SIMhvGs8eWyFZTlKhn166ryTFIK2pzpiJHa940O8sG7CNwojcob2suXs7LS603ph53q1bjtDz1Z9U2e0ktSzdX_r7VE22j7IViwMSOCsMMIckcl7svFQGHxBb95doJG4Gekh-sx7aPDnHIdhjv-GWbDl9auqVj_j76p1s9fqvk1zuXpBlbPGGZV9gx205FvUKm9kcVhAbKglATxfFR0xmShA2D5TMUVXX6wEHn2iHaQu20DjDgM_oglT9kPp6PyUpPLcj6s_HP0NmhsH1A)

## Usage example

In [63]:
# Create an instance of the PreprocessingStateMachine
state_machine = PreprocessingStateMachine()

# Preprocess the data using the initial state
state_machine.preprocess_data(titanic_data)

# Set the state to advanced and preprocess the data again
state_machine.set_state("advanced")
state_machine.preprocess_data(titanic_data)

Performing simple preprocessing...
Performing advanced preprocessing...

In this code example, we have an abstract base class **PreprocessingState** representing a preprocessing state. It defines the preprocess method that performs the preprocessing based on the state. Each concrete state, such as **SimplePreprocessingState** and **AdvancedPreprocessingState**, implements the preprocess method with its specific strategy.

The **PreprocessingStateMachine** class acts as the state machine that manages the current preprocessing state. It has a dictionary of all possible states and a current state variable. The set_state method allows switching between different states, and the preprocess_data method delegates the preprocessing to the current state.

In the usage example, we load the Titanic dataset and create an instance of the **PreprocessingStateMachine**. We initially preprocess the data using the simple state. Then, we set the state to advanced and preprocess the data again. The state machine manages the different preprocessing strategies based on the current state.

# 22. Behavioral - Strategy

## 01. Problem:
In software development, you often encounter scenarios where you need to dynamically change an algorithm or behavior at runtime. The problem is that hardcoding these algorithms or using conditional statements can lead to code duplication, poor maintainability, and limited flexibility.

## 02. Solution:
The Strategy design pattern provides a solution by encapsulating each algorithm or behavior in a separate strategy class and allowing the client to choose the appropriate strategy at runtime. The client can switch between different strategies without having to modify the core logic, promoting code reuse and flexibility.

## 03. Why it works:
The Strategy design pattern works by defining a common interface for all strategies, allowing them to be interchangeable. The client operates on this interface, decoupling it from specific strategies. By providing different strategies that conform to the common interface, the client can dynamically select and use the appropriate strategy at runtime.

## 04. Advantages:

* **Flexibility**: The Strategy pattern allows for runtime selection and switching of algorithms or behaviors, providing flexibility in adapting to different scenarios or requirements.
* **Code Reusability**: Each strategy encapsulates a specific algorithm or behavior, promoting code reuse and reducing duplication.
* **Easy Maintenance**: The separation of strategies from the core logic simplifies maintenance, as changes in one strategy do not affect others or the client code.

## 05. Disadvantages:

* **Increased Complexity**: The Strategy pattern introduces additional classes and complexity, especially when dealing with a large number of strategies or complex interactions between strategies.
* **Overhead**: The use of the Strategy pattern may incur some overhead due to the need for additional objects and method calls.

## Python example

In [64]:
class PreprocessingStrategy:
    """
    Abstract base class representing a preprocessing strategy.
    """

    def preprocess(self, data):
        """
        Abstract method to perform preprocessing based on the strategy.
        """
        raise NotImplementedError("Subclasses must implement preprocess().")

class SimplePreprocessingStrategy(PreprocessingStrategy):
    """
    Concrete subclass representing a simple preprocessing strategy.
    """

    def preprocess(self, data):
        """
        Preprocesses the data using a simple strategy.
        """
        print("Performing simple preprocessing...")
        # Perform simple preprocessing logic

class AdvancedPreprocessingStrategy(PreprocessingStrategy):
    """
    Concrete subclass representing an advanced preprocessing strategy.
    """

    def preprocess(self, data):
        """
        Preprocesses the data using an advanced strategy.
        """
        print("Performing advanced preprocessing...")
        # Perform advanced preprocessing logic

class DataPreprocessor:
    """
    Client class that performs data preprocessing using a chosen strategy.
    """

    def __init__(self, strategy):
        self.strategy = strategy

    def set_strategy(self, strategy):
        """
        Sets the data preprocessing strategy.
        """
        self.strategy = strategy

    def preprocess_data(self, data):
        """
        Preprocesses the data based on the current strategy.
        """
        self.strategy.preprocess(data)

## UML Diagram

[![](https://mermaid.ink/img/pako:eNq1UstqwzAQ_BWxp5TGPyB6CaTHQsFXQVikjSuwJKNHwCT-98iPum5r4lP2ImmZmR1GewXpFAEHWWMIR42VRyMsyzV02KenxjtJIWhbldFjpKpl1xHS1ytrZshOYUTO0LYvnF2cViOsE3YpWWrT1PQE4YO6oJWkniB9zKAfWeeXagUL0wy-HtdycKB4-obvNni_DP31fep9b5lfT-LtVhSPfmGT-zDokf0vMJd565KcpUBBWNiDIW9Qq7yPQ74C4hcZEsDzVdEZUx0FCNtlKKboytZK4NEn2kNqchY0bTDwM9Zh7r4rHZ2fmzQ8P6bF74_uDmSvC2U?type=png)](https://mermaid.live/edit#pako:eNq1UstqwzAQ_BWxp5TGPyB6CaTHQsFXQVikjSuwJKNHwCT-98iPum5r4lP2ImmZmR1GewXpFAEHWWMIR42VRyMsyzV02KenxjtJIWhbldFjpKpl1xHS1ytrZshOYUTO0LYvnF2cViOsE3YpWWrT1PQE4YO6oJWkniB9zKAfWeeXagUL0wy-HtdycKB4-obvNni_DP31fep9b5lfT-LtVhSPfmGT-zDokf0vMJd565KcpUBBWNiDIW9Qq7yPQ74C4hcZEsDzVdEZUx0FCNtlKKboytZK4NEn2kNqchY0bTDwM9Zh7r4rHZ2fmzQ8P6bF74_uDmSvC2U)

## Usage example

In [65]:
# Create instances of the preprocessing strategies
simple_strategy = SimplePreprocessingStrategy()
advanced_strategy = AdvancedPreprocessingStrategy()

# Create an instance of the DataPreprocessor with the simple strategy
data_preprocessor = DataPreprocessor(simple_strategy)

# Preprocess the data using the current strategy
data_preprocessor.preprocess_data(titanic_data)

# Switch to the advanced strategy and preprocess the data again
data_preprocessor.set_strategy(advanced_strategy)
data_preprocessor.preprocess_data(titanic_data)

Performing simple preprocessing...
Performing advanced preprocessing...

In this code example, we have an abstract base class **PreprocessingStrategy** representing a preprocessing strategy. It defines the preprocess method that performs the preprocessing based on the strategy. Each concrete strategy, such as **SimplePreprocessingStrategy** and **AdvancedPreprocessingStrategy**, implements the preprocess method with its specific strategy.

The **DataPreprocessor** class acts as the client that performs data preprocessing. It has a reference to the current strategy and uses it to preprocess the data. The client can switch between different strategies by calling the set_strategy method.

In the usage example, we load the Titanic dataset and create instances of the **SimplePreprocessingStrategy** and **AdvancedPreprocessingStrategy**. We create an instance of the DataPreprocessor with the initial simple strategy. Then, we preprocess the data using the current strategy. We switch to the advanced strategy by calling set_strategy and preprocess the data again using the new strategy.

# 23. Behavioral - Visitor

## 01. Problem:
In software development, you often encounter scenarios where you need to perform operations on a group of objects that belong to different classes with different interfaces. The problem is that adding new operations or functionalities to these objects becomes challenging as it requires modifying the existing classes, violating the Open-Closed Principle.

## 02. Solution:
The Visitor design pattern provides a solution by separating the operations from the object structure. It introduces a Visitor class that defines separate visit methods for each type of object in the structure. Each object accepts a visitor and delegates the operation to the visitor, decoupling the objects from the specific operations performed on them.

## 03. Why it works:
The Visitor design pattern works by leveraging double dispatch. The object structure accepts a visitor and calls the appropriate visit method based on its own type. The visitor then performs the desired operation on the object. This approach allows adding new operations or functionalities without modifying the existing object classes.

## 04. Advantages:

* **Extensibility**: The Visitor pattern allows adding new operations to the object structure by introducing new visitor classes, without modifying the existing object classes.
* **Separation of Concerns**: The pattern separates the logic of operations from the object structure, promoting a clean and modular design.
* **Open-Closed Principle**: The Visitor pattern follows the Open-Closed Principle by allowing the addition of new operations without modifying existing code.

## 05. Disadvantages:

* **Object Structure Awareness**: The Visitor pattern requires the object structure to be aware of the visitor and call the appropriate visit method. This may introduce coupling between the object structure and the visitor.
* **Object Hierarchy Impact**: Adding new types of objects to the hierarchy may require modifying the visitor interface and all its implementations, potentially impacting existing code.

## Python example

In [66]:
class DatasetVisitor:
    """
    Visitor class representing operations on the dataset.
    """

    def visit(self, dataset):
        """
        Performs the operation on the dataset.
        """
        raise NotImplementedError("Subclasses must implement visit().")

class AgeStatisticsVisitor(DatasetVisitor):
    """
    Concrete subclass representing a visitor for age statistics.
    """

    def visit(self, dataset):
        """
        Calculates and prints age statistics from the dataset.
        """
        age_mean = dataset['Age'].mean()
        age_median = dataset['Age'].median()
        age_std = dataset['Age'].std()

        print(f"Age statistics:")
        print(f"Mean: {age_mean:.2f}")
        print(f"Median: {age_median:.2f}")
        print(f"Standard Deviation: {age_std:.2f}")

class FareStatisticsVisitor(DatasetVisitor):
    """
    Concrete subclass representing a visitor for fare statistics.
    """

    def visit(self, dataset):
        """
        Calculates and prints fare statistics from the dataset.
        """
        fare_mean = dataset['Fare'].mean()
        fare_median = dataset['Fare'].median()
        fare_std = dataset['Fare'].std()

        print(f"Fare statistics:")
        print(f"Mean: {fare_mean:.2f}")
        print(f"Median: {fare_median:.2f}")
        print(f"Standard Deviation: {fare_std:.2f}")

## UML Diagram

[![](https://mermaid.ink/img/pako:eNqtUcsKgzAQ_JWwp5bqD4ReCra3noSeclnMagMaS7IKYv33xgdSir05l2Qnw-xstoes1gQSshK9TwwWDitlRcDEiAQZPfHDeMO1E_38NuIk2pE86FkhBdruKEVbGz2LBmW_nS4FpYxsPJvM7-B3Q7eX4c-Q53ccb8b9r94MoyxEUJGr0OjwxVM0BfykihTIcNWUY1OyAmWHIMWG67SzGUh2DUXQvEJ0WpYCMsfSr-xVjx1WkqbyvuxyPIYPZkygCg?type=png)](https://mermaid.live/edit#pako:eNqtUcsKgzAQ_JWwp5bqD4ReCra3noSeclnMagMaS7IKYv33xgdSir05l2Qnw-xstoes1gQSshK9TwwWDitlRcDEiAQZPfHDeMO1E_38NuIk2pE86FkhBdruKEVbGz2LBmW_nS4FpYxsPJvM7-B3Q7eX4c-Q53ccb8b9r94MoyxEUJGr0OjwxVM0BfykihTIcNWUY1OyAmWHIMWG67SzGUh2DUXQvEJ0WpYCMsfSr-xVjx1WkqbyvuxyPIYPZkygCg)

## Usage example

In [67]:
# Create instances of the visitors
age_visitor = AgeStatisticsVisitor()
fare_visitor = FareStatisticsVisitor()

# Perform age statistics operation on the dataset
age_visitor.visit(titanic_data)

# Perform fare statistics operation on the dataset
fare_visitor.visit(titanic_data)

Age statistics:
Mean: 29.36
Median: 28.00
Standard Deviation: 13.02
Fare statistics:
Mean: -0.00
Median: -0.36
Standard Deviation: 1.00

In this code example, we have an abstract base class **DatasetVisitor** representing a visitor for different operations on the dataset. It defines the visit method, which needs to be implemented by concrete visitor subclasses. Each concrete visitor, such as **AgeStatisticsVisitor** and **FareStatisticsVisitor**, implements the visit method with its specific operation on the dataset.

In the usage example, we load the Titanic dataset and create instances of the **AgeStatisticsVisitor** and **FareStatisticsVisitor**. We then perform the age statistics operation and fare statistics operation on the dataset by calling the visit method of each visitor instance, passing in the dataset.

# Conclusions

In this tutorial, we explored the Gang of Four (GoF) design patterns and their application in data science projects. Design patterns provide proven solutions to common design problems, offering a structured and reusable approach to software development. By understanding and applying design patterns, data scientists and software engineers can improve code quality, maintainability, and extensibility in their projects.

Tips for Applying Design Patterns in Data Science Projects:

1. **Understand the Problem**: Before applying a design pattern, thoroughly understand the problem you're trying to solve. Consider the project requirements, constraints, and potential future changes. This will help you choose the most appropriate design pattern for the given context.

1. **Keep It Simple**: While design patterns offer powerful solutions, it's essential to avoid overengineering. Don't introduce unnecessary complexity or abstraction layers. Use design patterns judiciously, focusing on improving code clarity, maintainability, and flexibility.

1. **Follow Best Practices**: When implementing design patterns, follow best practices such as encapsulation, loose coupling, and separation of concerns. This will make your code more modular, testable, and easier to understand.

1. **Document and Communicate**: Clearly document the design patterns you use in your code. Provide comments, docstrings, or architectural diagrams to explain the design choices and the intent behind the patterns. Effective communication of design patterns fosters collaboration and makes it easier for others to understand and contribute to the project.

1. **Refactor and Iterate**: Design patterns are not set in stone. As your project evolves, be open to refactoring and iterating on the design patterns used. Continuously assess their effectiveness and adapt them if needed to ensure they align with the changing project requirements.

1. **Practice and Learn**: Design patterns, like any other skill, require practice and learning. Familiarize yourself with a wide range of design patterns, their applicability, and trade-offs. Study real-world examples and seek opportunities to apply design patterns in your data science projects.

Remember, design patterns are tools to assist you in solving common design problems, but they are not a one-size-fits-all solution. It's crucial to apply them judiciously and adapt them to suit your project's specific needs. By leveraging the power of design patterns in your data science projects, you can improve code quality, maintainability, and ultimately deliver robust and scalable solutions.