# House Prices Prediction Using Linear Regression

### Importing Libraries

In [1]:
import pandas as pd
from sklearn import preprocessing  
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

### Getting our Training Data

In [2]:
df = pd.read_csv('../input/house-prices-advanced-regression-techniques/train.csv')

In [3]:
df

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

### Data Preprocessing

In [4]:
label_encoder = preprocessing.LabelEncoder()  # label encoding for columns not with int/float type values

In [5]:
df['MSZoning'] = label_encoder.fit_transform(df['MSZoning'])   # label encoding column - MSZoning for an example 
df

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,3,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,3,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,3,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,3,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,3,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,3,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,3,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,3,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,3,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,3,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

In [6]:
l = list(zip(df.dtypes, df.columns))  # listing all columns with their datatypes
l

[(dtype('int64'), 'Id'),
 (dtype('int64'), 'MSSubClass'),
 (dtype('int64'), 'MSZoning'),
 (dtype('float64'), 'LotFrontage'),
 (dtype('int64'), 'LotArea'),
 (dtype('O'), 'Street'),
 (dtype('O'), 'Alley'),
 (dtype('O'), 'LotShape'),
 (dtype('O'), 'LandContour'),
 (dtype('O'), 'Utilities'),
 (dtype('O'), 'LotConfig'),
 (dtype('O'), 'LandSlope'),
 (dtype('O'), 'Neighborhood'),
 (dtype('O'), 'Condition1'),
 (dtype('O'), 'Condition2'),
 (dtype('O'), 'BldgType'),
 (dtype('O'), 'HouseStyle'),
 (dtype('int64'), 'OverallQual'),
 (dtype('int64'), 'OverallCond'),
 (dtype('int64'), 'YearBuilt'),
 (dtype('int64'), 'YearRemodAdd'),
 (dtype('O'), 'RoofStyle'),
 (dtype('O'), 'RoofMatl'),
 (dtype('O'), 'Exterior1st'),
 (dtype('O'), 'Exterior2nd'),
 (dtype('O'), 'MasVnrType'),
 (dtype('float64'), 'MasVnrArea'),
 (dtype('O'), 'ExterQual'),
 (dtype('O'), 'ExterCond'),
 (dtype('O'), 'Foundation'),
 (dtype('O'), 'BsmtQual'),
 (dtype('O'), 'BsmtCond'),
 (dtype('O'), 'BsmtExposure'),
 (dtype('O'), 'BsmtFinType1'),
 (dtype('int64'), 'BsmtFinSF1'),
 (dtype('O'), 'BsmtFinType2'),
 (dtype('int64'), 'BsmtFinSF2'),
 (dtype('int64'), 'BsmtUnfSF'),
 (dtype('int64'), 'TotalBsmtSF'),
 (dtype('O'), 'Heating'),
 (dtype('O'), 'HeatingQC'),
 (dtype('O'), 'CentralAir'),
 (dtype('O'), 'Electrical'),
 (dtype('int64'), '1stFlrSF'),
 (dtype('int64'), '2ndFlrSF'),
 (dtype('int64'), 'LowQualFinSF'),
 (dtype('int64'), 'GrLivArea'),
 (dtype('int64'), 'BsmtFullBath'),
 (dtype('int64'), 'BsmtHalfBath'),
 (dtype('int64'), 'FullBath'),
 (dtype('int64'), 'HalfBath'),
 (dtype('int64'), 'BedroomAbvGr'),
 (dtype('int64'), 'KitchenAbvGr'),
 (dtype('O'), 'KitchenQual'),
 (dtype('int64'), 'TotRmsAbvGrd'),
 (dtype('O'), 'Functional'),
 (dtype('int64'), 'Fireplaces'),
 (dtype('O'), 'FireplaceQu'),
 (dtype('O'), 'GarageType'),
 (dtype('float64'), 'GarageYrBlt'),
 (dtype('O'), 'GarageFinish'),
 (dtype('int64'), 'GarageCars'),
 (dtype('int64'), 'GarageArea'),
 (dtype('O'), 'GarageQual'),
 (dtype('O'), 'GarageCond'),
 (dtype('O'), 'PavedDrive'),
 (dtype('int64'), 'WoodDeckSF'),
 (dtype('int64'), 'OpenPorchSF'),
 (dtype('int64'), 'EnclosedPorch'),
 (dtype('int64'), '3SsnPorch'),
 (dtype('int64'), 'ScreenPorch'),
 (dtype('int64'), 'PoolArea'),
 (dtype('O'), 'PoolQC'),
 (dtype('O'), 'Fence'),
 (dtype('O'), 'MiscFeature'),
 (dtype('int64'), 'MiscVal'),
 (dtype('int64'), 'MoSold'),
 (dtype('int64'), 'YrSold'),
 (dtype('O'), 'SaleType'),
 (dtype('O'), 'SaleCondition'),
 (dtype('int64'), 'SalePrice')]

In [7]:
# converting all object type data into string for label encoding
a = ['Street','Alley','LotShape','LandContour','Utilities','LotConfig','LandSlope','Neighborhood','Condition1','Condition2','BldgType','HouseStyle','RoofStyle','RoofMatl','Exterior1st','Exterior2nd','MasVnrType','ExterQual','ExterCond','Foundation','BsmtQual','BsmtCond','BsmtExposure','BsmtFinType1','BsmtFinType2','Heating','HeatingQC','CentralAir','Electrical','KitchenQual','Functional','FireplaceQu','GarageType','GarageFinish','GarageQual','GarageCond','PavedDrive','PoolQC','Fence','MiscFeature','SaleType','SaleCondition']
for i in a:
  df[i] = df[i].astype('|S')
df

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,3,65.0,8450,b'Pave',b'nan',b'Reg',b'Lvl',b'AllPub',...,0,b'nan',b'nan',b'nan',0,2,2008,b'WD',b'Normal',208500
1,2,20,3,80.0,9600,b'Pave',b'nan',b'Reg',b'Lvl',b'AllPub',...,0,b'nan',b'nan',b'nan',0,5,2007,b'WD',b'Normal',181500
2,3,60,3,68.0,11250,b'Pave',b'nan',b'IR1',b'Lvl',b'AllPub',...,0,b'nan',b'nan',b'nan',0,9,2008,b'WD',b'Normal',223500
3,4,70,3,60.0,9550,b'Pave',b'nan',b'IR1',b'Lvl',b'AllPub',...,0,b'nan',b'nan',b'nan',0,2,2006,b'WD',b'Abnorml',140000
4,5,60,3,84.0,14260,b'Pave',b'nan',b'IR1',b'Lvl',b'AllPub',...,0,b'nan',b'nan',b'nan',0,12,2008,b'WD',b'Normal',250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,3,62.0,7917,b'Pave',b'nan',b'Reg',b'Lvl',b'AllPub',...,0,b'nan',b'nan',b'nan',0,8,2007,b'WD',b'Normal',175000
1456,1457,20,3,85.0,13175,b'Pave',b'nan',b'Reg',b'Lvl',b'AllPub',...,0,b'nan',b'MnPrv',b'nan',0,2,2010,b'WD',b'Normal',210000
1457,1458,70,3,66.0,9042,b'Pave',b'nan',b'Reg',b'Lvl',b'AllPub',...,0,b'nan',b'GdPrv',b'Shed',2500,5,2010,b'WD',b'Normal',266500
1458,1459,20,3,68.0,9717,b'Pave',b'nan',b'Reg',b'Lvl',b'AllPub',...,0,b'nan',b'nan',b'nan',0,4,2010,b'WD',b'Normal',142125
1459,1460,20,3,75.0,9937,b'Pave',b'nan',b'Reg',b'Lvl',b'AllPub',...,0,b'nan',b'nan',b'nan',0,6,2008,b'WD',b'Normal',147500

In [8]:
# checking from above and label encoding columns that are required to be encoded
label_object = {}
a = ['Street','Alley','LotShape','LandContour','Utilities','LotConfig','LandSlope','Neighborhood','Condition1','Condition2','BldgType','HouseStyle','RoofStyle','RoofMatl','Exterior1st','Exterior2nd','MasVnrType','ExterQual','ExterCond','Foundation','BsmtQual','BsmtCond','BsmtExposure','BsmtFinType1','BsmtFinType2','Heating','HeatingQC','CentralAir','Electrical','KitchenQual','Functional','FireplaceQu','GarageType','GarageFinish','GarageQual','GarageCond','PavedDrive','PoolQC','Fence','MiscFeature','SaleType','SaleCondition']
for i in a:
  labelencoder = label_encoder
  labelencoder.fit(df[i])
  df[i] = labelencoder.fit_transform(df[i])
  label_object[i] = labelencoder
df # getting final encoded dataframe

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,3,65.0,8450,1,2,3,3,0,...,0,3,4,4,0,2,2008,8,4,208500
1,2,20,3,80.0,9600,1,2,3,3,0,...,0,3,4,4,0,5,2007,8,4,181500
2,3,60,3,68.0,11250,1,2,0,3,0,...,0,3,4,4,0,9,2008,8,4,223500
3,4,70,3,60.0,9550,1,2,0,3,0,...,0,3,4,4,0,2,2006,8,0,140000
4,5,60,3,84.0,14260,1,2,0,3,0,...,0,3,4,4,0,12,2008,8,4,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,3,62.0,7917,1,2,3,3,0,...,0,3,4,4,0,8,2007,8,4,175000
1456,1457,20,3,85.0,13175,1,2,3,3,0,...,0,3,2,4,0,2,2010,8,4,210000
1457,1458,70,3,66.0,9042,1,2,3,3,0,...,0,3,0,2,2500,5,2010,8,4,266500
1458,1459,20,3,68.0,9717,1,2,3,3,0,...,0,3,4,4,0,4,2010,8,4,142125
1459,1460,20,3,75.0,9937,1,2,3,3,0,...,0,3,4,4,0,6,2008,8,4,147500

In [9]:
# checking for columns that may contain NULL values
b = list(zip(df.isnull().any(), df.columns))
b

[(False, 'Id'),
 (False, 'MSSubClass'),
 (False, 'MSZoning'),
 (True, 'LotFrontage'),
 (False, 'LotArea'),
 (False, 'Street'),
 (False, 'Alley'),
 (False, 'LotShape'),
 (False, 'LandContour'),
 (False, 'Utilities'),
 (False, 'LotConfig'),
 (False, 'LandSlope'),
 (False, 'Neighborhood'),
 (False, 'Condition1'),
 (False, 'Condition2'),
 (False, 'BldgType'),
 (False, 'HouseStyle'),
 (False, 'OverallQual'),
 (False, 'OverallCond'),
 (False, 'YearBuilt'),
 (False, 'YearRemodAdd'),
 (False, 'RoofStyle'),
 (False, 'RoofMatl'),
 (False, 'Exterior1st'),
 (False, 'Exterior2nd'),
 (False, 'MasVnrType'),
 (True, 'MasVnrArea'),
 (False, 'ExterQual'),
 (False, 'ExterCond'),
 (False, 'Foundation'),
 (False, 'BsmtQual'),
 (False, 'BsmtCond'),
 (False, 'BsmtExposure'),
 (False, 'BsmtFinType1'),
 (False, 'BsmtFinSF1'),
 (False, 'BsmtFinType2'),
 (False, 'BsmtFinSF2'),
 (False, 'BsmtUnfSF'),
 (False, 'TotalBsmtSF'),
 (False, 'Heating'),
 (False, 'HeatingQC'),
 (False, 'CentralAir'),
 (False, 'Electrical'),
 (False, '1stFlrSF'),
 (False, '2ndFlrSF'),
 (False, 'LowQualFinSF'),
 (False, 'GrLivArea'),
 (False, 'BsmtFullBath'),
 (False, 'BsmtHalfBath'),
 (False, 'FullBath'),
 (False, 'HalfBath'),
 (False, 'BedroomAbvGr'),
 (False, 'KitchenAbvGr'),
 (False, 'KitchenQual'),
 (False, 'TotRmsAbvGrd'),
 (False, 'Functional'),
 (False, 'Fireplaces'),
 (False, 'FireplaceQu'),
 (False, 'GarageType'),
 (True, 'GarageYrBlt'),
 (False, 'GarageFinish'),
 (False, 'GarageCars'),
 (False, 'GarageArea'),
 (False, 'GarageQual'),
 (False, 'GarageCond'),
 (False, 'PavedDrive'),
 (False, 'WoodDeckSF'),
 (False, 'OpenPorchSF'),
 (False, 'EnclosedPorch'),
 (False, '3SsnPorch'),
 (False, 'ScreenPorch'),
 (False, 'PoolArea'),
 (False, 'PoolQC'),
 (False, 'Fence'),
 (False, 'MiscFeature'),
 (False, 'MiscVal'),
 (False, 'MoSold'),
 (False, 'YrSold'),
 (False, 'SaleType'),
 (False, 'SaleCondition'),
 (False, 'SalePrice')]

In [10]:
# replacing all null values with 0
df = df.fillna(0)
df

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,3,65.0,8450,1,2,3,3,0,...,0,3,4,4,0,2,2008,8,4,208500
1,2,20,3,80.0,9600,1,2,3,3,0,...,0,3,4,4,0,5,2007,8,4,181500
2,3,60,3,68.0,11250,1,2,0,3,0,...,0,3,4,4,0,9,2008,8,4,223500
3,4,70,3,60.0,9550,1,2,0,3,0,...,0,3,4,4,0,2,2006,8,0,140000
4,5,60,3,84.0,14260,1,2,0,3,0,...,0,3,4,4,0,12,2008,8,4,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,3,62.0,7917,1,2,3,3,0,...,0,3,4,4,0,8,2007,8,4,175000
1456,1457,20,3,85.0,13175,1,2,3,3,0,...,0,3,2,4,0,2,2010,8,4,210000
1457,1458,70,3,66.0,9042,1,2,3,3,0,...,0,3,0,2,2500,5,2010,8,4,266500
1458,1459,20,3,68.0,9717,1,2,3,3,0,...,0,3,4,4,0,4,2010,8,4,142125
1459,1460,20,3,75.0,9937,1,2,3,3,0,...,0,3,4,4,0,6,2008,8,4,147500

In [11]:
# verifying that no null value is present now
df.isnull().any()

Id               False
MSSubClass       False
MSZoning         False
LotFrontage      False
LotArea          False
                 ...
MoSold           False
YrSold           False
SaleType         False
SaleCondition    False
SalePrice        False
Length: 81, dtype: bool

### Splitting Data for Training and Testing

In [12]:
# splitting data into 70:30 ratio for training and testing
data = df.values
X, y = data[:,:-1], data[:,-1]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=10)

### Linear Regression Model

In [13]:
# initialising the model
model = LinearRegression()

In [14]:
# training the model with train data
model.fit(X_train, y_train)

LinearRegression()

In [15]:
# making predictions
y_pred = model.predict(X_test)

In [16]:
# checking accuracy using Mean Squared Error
mean_squared_error(y_test,y_pred)

977943167.7434596

### Getting our Testing Data for making Predictions

In [17]:
test = pd.read_csv('../input/house-prices-advanced-regression-techniques/test.csv')

In [18]:
test

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1461,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,...,120,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal
1,1462,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal
2,1463,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal
3,1464,60,RL,78.0,9978,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2010,WD,Normal
4,1465,120,RL,43.0,5005,Pave,NaN,IR1,HLS,AllPub,...,144,0,NaN,NaN,NaN,0,1,2010,WD,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,2915,160,RM,21.0,1936,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2006,WD,Normal
1455,2916,160,RM,21.0,1894,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,4,2006,WD,Abnorml
1456,2917,20,RL,160.0,20000,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,9,2006,WD,Abnorml
1457,2918,85,RL,62.0,10441,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,MnPrv,Shed,700,7,2006,WD,Normal
1458,2919,60,RL,74.0,9627,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,11,2006,WD,Normal

### Dataset Cleaning

In [19]:
c = ['MSZoning','Street','Alley','LotShape','LandContour','Utilities','LotConfig','LandSlope','Neighborhood','Condition1','Condition2','BldgType','HouseStyle','RoofStyle','RoofMatl','Exterior1st','Exterior2nd','MasVnrType','ExterQual','ExterCond','Foundation','BsmtQual','BsmtCond','BsmtExposure','BsmtFinType1','BsmtFinType2','Heating','HeatingQC','CentralAir','Electrical','KitchenQual','Functional','FireplaceQu','GarageType','GarageFinish','GarageQual','GarageCond','PavedDrive','PoolQC','Fence','MiscFeature','SaleType','SaleCondition']
for i in c:
  test[i] = test[i].astype('|S')
test

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1461,20,b'RH',80.0,11622,b'Pave',b'nan',b'Reg',b'Lvl',b'AllPub',...,120,0,b'nan',b'MnPrv',b'nan',0,6,2010,b'WD',b'Normal'
1,1462,20,b'RL',81.0,14267,b'Pave',b'nan',b'IR1',b'Lvl',b'AllPub',...,0,0,b'nan',b'nan',b'Gar2',12500,6,2010,b'WD',b'Normal'
2,1463,60,b'RL',74.0,13830,b'Pave',b'nan',b'IR1',b'Lvl',b'AllPub',...,0,0,b'nan',b'MnPrv',b'nan',0,3,2010,b'WD',b'Normal'
3,1464,60,b'RL',78.0,9978,b'Pave',b'nan',b'IR1',b'Lvl',b'AllPub',...,0,0,b'nan',b'nan',b'nan',0,6,2010,b'WD',b'Normal'
4,1465,120,b'RL',43.0,5005,b'Pave',b'nan',b'IR1',b'HLS',b'AllPub',...,144,0,b'nan',b'nan',b'nan',0,1,2010,b'WD',b'Normal'
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,2915,160,b'RM',21.0,1936,b'Pave',b'nan',b'Reg',b'Lvl',b'AllPub',...,0,0,b'nan',b'nan',b'nan',0,6,2006,b'WD',b'Normal'
1455,2916,160,b'RM',21.0,1894,b'Pave',b'nan',b'Reg',b'Lvl',b'AllPub',...,0,0,b'nan',b'nan',b'nan',0,4,2006,b'WD',b'Abnorml'
1456,2917,20,b'RL',160.0,20000,b'Pave',b'nan',b'Reg',b'Lvl',b'AllPub',...,0,0,b'nan',b'nan',b'nan',0,9,2006,b'WD',b'Abnorml'
1457,2918,85,b'RL',62.0,10441,b'Pave',b'nan',b'Reg',b'Lvl',b'AllPub',...,0,0,b'nan',b'MnPrv',b'Shed',700,7,2006,b'WD',b'Normal'
1458,2919,60,b'RL',74.0,9627,b'Pave',b'nan',b'Reg',b'Lvl',b'AllPub',...,0,0,b'nan',b'nan',b'nan',0,11,2006,b'WD',b'Normal'

In [20]:
# label encoding
label_objectTest = {}
for i in c:
  labelencoder = label_encoder
  labelencoder.fit(test[i])
  test[i] = labelencoder.fit_transform(test[i])
  label_objectTest[i] = labelencoder
test

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1461,20,2,80.0,11622,1,2,3,3,0,...,120,0,2,2,3,0,6,2010,8,4
1,1462,20,3,81.0,14267,1,2,0,3,0,...,0,0,2,4,0,12500,6,2010,8,4
2,1463,60,3,74.0,13830,1,2,0,3,0,...,0,0,2,2,3,0,3,2010,8,4
3,1464,60,3,78.0,9978,1,2,0,3,0,...,0,0,2,4,3,0,6,2010,8,4
4,1465,120,3,43.0,5005,1,2,0,1,0,...,144,0,2,4,3,0,1,2010,8,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,2915,160,4,21.0,1936,1,2,3,3,0,...,0,0,2,4,3,0,6,2006,8,4
1455,2916,160,4,21.0,1894,1,2,3,3,0,...,0,0,2,4,3,0,4,2006,8,0
1456,2917,20,3,160.0,20000,1,2,3,3,0,...,0,0,2,4,3,0,9,2006,8,0
1457,2918,85,3,62.0,10441,1,2,3,3,0,...,0,0,2,2,2,700,7,2006,8,4
1458,2919,60,3,74.0,9627,1,2,3,3,0,...,0,0,2,4,3,0,11,2006,8,4

In [21]:
# replacing all NULL values with 0
test = test.fillna(0)
test  # our testing dataset is ready to be used for making predictions

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1461,20,2,80.0,11622,1,2,3,3,0,...,120,0,2,2,3,0,6,2010,8,4
1,1462,20,3,81.0,14267,1,2,0,3,0,...,0,0,2,4,0,12500,6,2010,8,4
2,1463,60,3,74.0,13830,1,2,0,3,0,...,0,0,2,2,3,0,3,2010,8,4
3,1464,60,3,78.0,9978,1,2,0,3,0,...,0,0,2,4,3,0,6,2010,8,4
4,1465,120,3,43.0,5005,1,2,0,1,0,...,144,0,2,4,3,0,1,2010,8,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,2915,160,4,21.0,1936,1,2,3,3,0,...,0,0,2,4,3,0,6,2006,8,4
1455,2916,160,4,21.0,1894,1,2,3,3,0,...,0,0,2,4,3,0,4,2006,8,0
1456,2917,20,3,160.0,20000,1,2,3,3,0,...,0,0,2,4,3,0,9,2006,8,0
1457,2918,85,3,62.0,10441,1,2,3,3,0,...,0,0,2,2,2,700,7,2006,8,4
1458,2919,60,3,74.0,9627,1,2,3,3,0,...,0,0,2,4,3,0,11,2006,8,4

In [22]:
# getting Ids of all houses whose sale prices are to be predicted 
d = pd.DataFrame(test['Id'])

### Making Final Predictions

In [23]:
final_pred = model.predict(test)

In [24]:
# getting our final predictions dataframe ready
Predictions = pd.DataFrame(final_pred)
Predictions = Predictions.rename(columns={0:'SalePrice'})
Predictions = d.join(Predictions)
Predictions

        Id      SalePrice
0     1461  191900.166074
1     1462  250258.495917
2     1463  251360.931273
3     1464  277392.417998
4     1465  279786.432663
...    ...            ...
1454  2915  167209.725147
1455  2916  143248.686062
1456  2917  241013.599240
1457  2918  213672.492781
1458  2919  337830.181138

[1459 rows x 2 columns]

In [25]:
# saving predictions to csv file
Predictions.to_csv('Predictions.csv',index=False)