In [1]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv('/kaggle/input/spaceship-titanic/train.csv')
df

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported
0,0001_01,Europa,False,B/0/P,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,Maham Ofracculy,False
1,0002_01,Earth,False,F/0/S,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,Juanna Vines,True
2,0003_01,Europa,False,A/0/S,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,49.0,Altark Susent,False
3,0003_02,Europa,False,A/0/S,TRAPPIST-1e,33.0,False,0.0,1283.0,371.0,3329.0,193.0,Solam Susent,False
4,0004_01,Earth,False,F/1/S,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,2.0,Willy Santantines,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8688,9276_01,Europa,False,A/98/P,55 Cancri e,41.0,True,0.0,6819.0,0.0,1643.0,74.0,Gravior Noxnuther,False
8689,9278_01,Earth,True,G/1499/S,PSO J318.5-22,18.0,False,0.0,0.0,0.0,0.0,0.0,Kurta Mondalley,False
8690,9279_01,Earth,False,G/1500/S,TRAPPIST-1e,26.0,False,0.0,0.0,1872.0,1.0,0.0,Fayey Connon,True
8691,9280_01,Europa,False,E/608/S,55 Cancri e,32.0,False,0.0,1049.0,0.0,353.0,3235.0,Celeon Hontichre,False
8692,9280_02,Europa,False,E/608/S,TRAPPIST-1e,44.0,False,126.0,4688.0,0.0,0.0,12.0,Propsh Hontichre,True

In [3]:
df.info( )

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8693 entries, 0 to 8692
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   PassengerId   8693 non-null   object
 1   HomePlanet    8492 non-null   object
 2   CryoSleep     8476 non-null   object
 3   Cabin         8494 non-null   object
 4   Destination   8511 non-null   object
 5   Age           8514 non-null   float64
 6   VIP           8490 non-null   object
 7   RoomService   8512 non-null   float64
 8   FoodCourt     8510 non-null   float64
 9   ShoppingMall  8485 non-null   float64
 10  Spa           8510 non-null   float64
 11  VRDeck        8505 non-null   float64
 12  Name          8493 non-null   object
 13  Transported   8693 non-null   bool
dtypes: bool(1), float64(6), object(7)
memory usage: 891.5+ KB

In [4]:
df.drop(df.iloc[:,12:13],axis=1,inplace=True)

In [5]:
df

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Transported
0,0001_01,Europa,False,B/0/P,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,False
1,0002_01,Earth,False,F/0/S,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,True
2,0003_01,Europa,False,A/0/S,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,49.0,False
3,0003_02,Europa,False,A/0/S,TRAPPIST-1e,33.0,False,0.0,1283.0,371.0,3329.0,193.0,False
4,0004_01,Earth,False,F/1/S,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,2.0,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8688,9276_01,Europa,False,A/98/P,55 Cancri e,41.0,True,0.0,6819.0,0.0,1643.0,74.0,False
8689,9278_01,Earth,True,G/1499/S,PSO J318.5-22,18.0,False,0.0,0.0,0.0,0.0,0.0,False
8690,9279_01,Earth,False,G/1500/S,TRAPPIST-1e,26.0,False,0.0,0.0,1872.0,1.0,0.0,True
8691,9280_01,Europa,False,E/608/S,55 Cancri e,32.0,False,0.0,1049.0,0.0,353.0,3235.0,False
8692,9280_02,Europa,False,E/608/S,TRAPPIST-1e,44.0,False,126.0,4688.0,0.0,0.0,12.0,True

In [6]:
df.drop(df.iloc[:,0:2],axis=1,inplace=True)
df

,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Transported
0,False,B/0/P,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,False
1,False,F/0/S,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,True
2,False,A/0/S,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,49.0,False
3,False,A/0/S,TRAPPIST-1e,33.0,False,0.0,1283.0,371.0,3329.0,193.0,False
4,False,F/1/S,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,2.0,True
...,...,...,...,...,...,...,...,...,...,...,...
8688,False,A/98/P,55 Cancri e,41.0,True,0.0,6819.0,0.0,1643.0,74.0,False
8689,True,G/1499/S,PSO J318.5-22,18.0,False,0.0,0.0,0.0,0.0,0.0,False
8690,False,G/1500/S,TRAPPIST-1e,26.0,False,0.0,0.0,1872.0,1.0,0.0,True
8691,False,E/608/S,55 Cancri e,32.0,False,0.0,1049.0,0.0,353.0,3235.0,False
8692,False,E/608/S,TRAPPIST-1e,44.0,False,126.0,4688.0,0.0,0.0,12.0,True

In [7]:
df.drop(df.iloc[:,1:3],axis=1,inplace=True)
df

,CryoSleep,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Transported
0,False,39.0,False,0.0,0.0,0.0,0.0,0.0,False
1,False,24.0,False,109.0,9.0,25.0,549.0,44.0,True
2,False,58.0,True,43.0,3576.0,0.0,6715.0,49.0,False
3,False,33.0,False,0.0,1283.0,371.0,3329.0,193.0,False
4,False,16.0,False,303.0,70.0,151.0,565.0,2.0,True
...,...,...,...,...,...,...,...,...,...
8688,False,41.0,True,0.0,6819.0,0.0,1643.0,74.0,False
8689,True,18.0,False,0.0,0.0,0.0,0.0,0.0,False
8690,False,26.0,False,0.0,0.0,1872.0,1.0,0.0,True
8691,False,32.0,False,0.0,1049.0,0.0,353.0,3235.0,False
8692,False,44.0,False,126.0,4688.0,0.0,0.0,12.0,True

In [8]:
df=df.replace(to_replace=False,value=0)
df=df.replace(to_replace=True,value=1)
df

,CryoSleep,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Transported
0,0.0,39.0,0.0,0.0,0.0,0.0,0.0,0.0,0
1,0.0,24.0,0.0,109.0,9.0,25.0,549.0,44.0,1
2,0.0,58.0,1.0,43.0,3576.0,0.0,6715.0,49.0,0
3,0.0,33.0,0.0,0.0,1283.0,371.0,3329.0,193.0,0
4,0.0,16.0,0.0,303.0,70.0,151.0,565.0,2.0,1
...,...,...,...,...,...,...,...,...,...
8688,0.0,41.0,1.0,0.0,6819.0,0.0,1643.0,74.0,0
8689,1.0,18.0,0.0,0.0,0.0,0.0,0.0,0.0,0
8690,0.0,26.0,0.0,0.0,0.0,1872.0,1.0,0.0,1
8691,0.0,32.0,0.0,0.0,1049.0,0.0,353.0,3235.0,0
8692,0.0,44.0,0.0,126.0,4688.0,0.0,0.0,12.0,1

In [9]:
df.isnull().sum()

CryoSleep       217
Age             179
VIP             203
RoomService     181
FoodCourt       183
ShoppingMall    208
Spa             183
VRDeck          188
Transported       0
dtype: int64

In [10]:
df['Age'].fillna(df['Age'].mean(),inplace=True)
df['CryoSleep'].fillna(df['CryoSleep'].mean(),inplace=True)
df['VIP'].fillna(df['VIP'].mean(),inplace=True)
df['RoomService'].fillna(df['RoomService'].mean(),inplace=True)
df['FoodCourt'].fillna(df['FoodCourt'].mean(),inplace=True)
df['ShoppingMall'].fillna(df['ShoppingMall'].mean(),inplace=True)
df['Spa'].fillna(df['Spa'].mean(),inplace=True)
df['VRDeck'].fillna(df['VRDeck'].mean(),inplace=True)
df

,CryoSleep,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Transported
0,0.0,39.0,0.0,0.0,0.0,0.0,0.0,0.0,0
1,0.0,24.0,0.0,109.0,9.0,25.0,549.0,44.0,1
2,0.0,58.0,1.0,43.0,3576.0,0.0,6715.0,49.0,0
3,0.0,33.0,0.0,0.0,1283.0,371.0,3329.0,193.0,0
4,0.0,16.0,0.0,303.0,70.0,151.0,565.0,2.0,1
...,...,...,...,...,...,...,...,...,...
8688,0.0,41.0,1.0,0.0,6819.0,0.0,1643.0,74.0,0
8689,1.0,18.0,0.0,0.0,0.0,0.0,0.0,0.0,0
8690,0.0,26.0,0.0,0.0,0.0,1872.0,1.0,0.0,1
8691,0.0,32.0,0.0,0.0,1049.0,0.0,353.0,3235.0,0
8692,0.0,44.0,0.0,126.0,4688.0,0.0,0.0,12.0,1

In [11]:
x=df.iloc[:,0:8]
y=df.Transported
x

,CryoSleep,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck
0,0.0,39.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,24.0,0.0,109.0,9.0,25.0,549.0,44.0
2,0.0,58.0,1.0,43.0,3576.0,0.0,6715.0,49.0
3,0.0,33.0,0.0,0.0,1283.0,371.0,3329.0,193.0
4,0.0,16.0,0.0,303.0,70.0,151.0,565.0,2.0
...,...,...,...,...,...,...,...,...
8688,0.0,41.0,1.0,0.0,6819.0,0.0,1643.0,74.0
8689,1.0,18.0,0.0,0.0,0.0,0.0,0.0,0.0
8690,0.0,26.0,0.0,0.0,0.0,1872.0,1.0,0.0
8691,0.0,32.0,0.0,0.0,1049.0,0.0,353.0,3235.0
8692,0.0,44.0,0.0,126.0,4688.0,0.0,0.0,12.0

In [12]:
y

0       0
1       1
2       0
3       0
4       1
       ..
8688    0
8689    0
8690    1
8691    0
8692    1
Name: Transported, Length: 8693, dtype: int64

In [13]:
x.isnull().sum()

CryoSleep       0
Age             0
VIP             0
RoomService     0
FoodCourt       0
ShoppingMall    0
Spa             0
VRDeck          0
dtype: int64

In [14]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.8,random_state=0)

In [15]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
model.fit(x_train,y_train)

LogisticRegression()

In [16]:
model.predict(x_test)

array([0, 1, 0, ..., 1, 0, 0])

In [17]:
model.score(x_test,y_test)

0.777458309373203

In [18]:
df1=pd.read_csv('/kaggle/input/spaceship-titanic/test.csv')
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4277 entries, 0 to 4276
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   PassengerId   4277 non-null   object
 1   HomePlanet    4190 non-null   object
 2   CryoSleep     4184 non-null   object
 3   Cabin         4177 non-null   object
 4   Destination   4185 non-null   object
 5   Age           4186 non-null   float64
 6   VIP           4184 non-null   object
 7   RoomService   4195 non-null   float64
 8   FoodCourt     4171 non-null   float64
 9   ShoppingMall  4179 non-null   float64
 10  Spa           4176 non-null   float64
 11  VRDeck        4197 non-null   float64
 12  Name          4183 non-null   object
dtypes: float64(6), object(7)
memory usage: 434.5+ KB

In [19]:
df1.drop(df1.iloc[:,12:],axis=1,inplace=True)
df1

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck
0,0013_01,Earth,True,G/3/S,TRAPPIST-1e,27.0,False,0.0,0.0,0.0,0.0,0.0
1,0018_01,Earth,False,F/4/S,TRAPPIST-1e,19.0,False,0.0,9.0,0.0,2823.0,0.0
2,0019_01,Europa,True,C/0/S,55 Cancri e,31.0,False,0.0,0.0,0.0,0.0,0.0
3,0021_01,Europa,False,C/1/S,TRAPPIST-1e,38.0,False,0.0,6652.0,0.0,181.0,585.0
4,0023_01,Earth,False,F/5/S,TRAPPIST-1e,20.0,False,10.0,0.0,635.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
4272,9266_02,Earth,True,G/1496/S,TRAPPIST-1e,34.0,False,0.0,0.0,0.0,0.0,0.0
4273,9269_01,Earth,False,NaN,TRAPPIST-1e,42.0,False,0.0,847.0,17.0,10.0,144.0
4274,9271_01,Mars,True,D/296/P,55 Cancri e,NaN,False,0.0,0.0,0.0,0.0,0.0
4275,9273_01,Europa,False,D/297/P,NaN,NaN,False,0.0,2680.0,0.0,0.0,523.0
4276,9277_01,Earth,True,G/1498/S,PSO J318.5-22,43.0,False,0.0,0.0,0.0,0.0,0.0

In [20]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4277 entries, 0 to 4276
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   PassengerId   4277 non-null   object
 1   HomePlanet    4190 non-null   object
 2   CryoSleep     4184 non-null   object
 3   Cabin         4177 non-null   object
 4   Destination   4185 non-null   object
 5   Age           4186 non-null   float64
 6   VIP           4184 non-null   object
 7   RoomService   4195 non-null   float64
 8   FoodCourt     4171 non-null   float64
 9   ShoppingMall  4179 non-null   float64
 10  Spa           4176 non-null   float64
 11  VRDeck        4197 non-null   float64
dtypes: float64(6), object(6)
memory usage: 401.1+ KB

In [21]:
df1.drop(df1.iloc[:,1:2],axis=1,inplace=True)
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4277 entries, 0 to 4276
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   PassengerId   4277 non-null   object
 1   CryoSleep     4184 non-null   object
 2   Cabin         4177 non-null   object
 3   Destination   4185 non-null   object
 4   Age           4186 non-null   float64
 5   VIP           4184 non-null   object
 6   RoomService   4195 non-null   float64
 7   FoodCourt     4171 non-null   float64
 8   ShoppingMall  4179 non-null   float64
 9   Spa           4176 non-null   float64
 10  VRDeck        4197 non-null   float64
dtypes: float64(6), object(5)
memory usage: 367.7+ KB

In [22]:
df1.drop(df1.iloc[:,2:4],axis=1,inplace=True)
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4277 entries, 0 to 4276
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   PassengerId   4277 non-null   object
 1   CryoSleep     4184 non-null   object
 2   Age           4186 non-null   float64
 3   VIP           4184 non-null   object
 4   RoomService   4195 non-null   float64
 5   FoodCourt     4171 non-null   float64
 6   ShoppingMall  4179 non-null   float64
 7   Spa           4176 non-null   float64
 8   VRDeck        4197 non-null   float64
dtypes: float64(6), object(3)
memory usage: 300.9+ KB

In [23]:
df1

,PassengerId,CryoSleep,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck
0,0013_01,True,27.0,False,0.0,0.0,0.0,0.0,0.0
1,0018_01,False,19.0,False,0.0,9.0,0.0,2823.0,0.0
2,0019_01,True,31.0,False,0.0,0.0,0.0,0.0,0.0
3,0021_01,False,38.0,False,0.0,6652.0,0.0,181.0,585.0
4,0023_01,False,20.0,False,10.0,0.0,635.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...
4272,9266_02,True,34.0,False,0.0,0.0,0.0,0.0,0.0
4273,9269_01,False,42.0,False,0.0,847.0,17.0,10.0,144.0
4274,9271_01,True,NaN,False,0.0,0.0,0.0,0.0,0.0
4275,9273_01,False,NaN,False,0.0,2680.0,0.0,0.0,523.0
4276,9277_01,True,43.0,False,0.0,0.0,0.0,0.0,0.0

In [24]:
df1=df1.replace(to_replace=True,value=1)
df1=df1.replace(to_replace=False,value=0)
df1

,PassengerId,CryoSleep,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck
0,0013_01,1.0,27.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0018_01,0.0,19.0,0.0,0.0,9.0,0.0,2823.0,0.0
2,0019_01,1.0,31.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0021_01,0.0,38.0,0.0,0.0,6652.0,0.0,181.0,585.0
4,0023_01,0.0,20.0,0.0,10.0,0.0,635.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...
4272,9266_02,1.0,34.0,0.0,0.0,0.0,0.0,0.0,0.0
4273,9269_01,0.0,42.0,0.0,0.0,847.0,17.0,10.0,144.0
4274,9271_01,1.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0
4275,9273_01,0.0,NaN,0.0,0.0,2680.0,0.0,0.0,523.0
4276,9277_01,1.0,43.0,0.0,0.0,0.0,0.0,0.0,0.0

In [25]:
df1['CryoSleep'].fillna(df1['CryoSleep'].mean(),inplace=True)
df1['Age'].fillna(df1['Age'].mean(),inplace=True)
df1['VIP'].fillna(df['VIP'].mean(),inplace=True)
df1['RoomService'].fillna(df['RoomService'].mean(),inplace=True)
df1['FoodCourt'].fillna(df['FoodCourt'].mean(),inplace=True)
df1['ShoppingMall'].fillna(df['ShoppingMall'].mean(),inplace=True)
df1['Spa'].fillna(df['Spa'].mean(),inplace=True)
df1['VRDeck'].fillna(df['VRDeck'].mean(),inplace=True)
df1

,PassengerId,CryoSleep,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck
0,0013_01,1.0,27.000000,0.0,0.0,0.0,0.0,0.0,0.0
1,0018_01,0.0,19.000000,0.0,0.0,9.0,0.0,2823.0,0.0
2,0019_01,1.0,31.000000,0.0,0.0,0.0,0.0,0.0,0.0
3,0021_01,0.0,38.000000,0.0,0.0,6652.0,0.0,181.0,585.0
4,0023_01,0.0,20.000000,0.0,10.0,0.0,635.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...
4272,9266_02,1.0,34.000000,0.0,0.0,0.0,0.0,0.0,0.0
4273,9269_01,0.0,42.000000,0.0,0.0,847.0,17.0,10.0,144.0
4274,9271_01,1.0,28.658146,0.0,0.0,0.0,0.0,0.0,0.0
4275,9273_01,0.0,28.658146,0.0,0.0,2680.0,0.0,0.0,523.0
4276,9277_01,1.0,43.000000,0.0,0.0,0.0,0.0,0.0,0.0

In [26]:
passid=df1['PassengerId']

In [27]:
df1.drop(['PassengerId'],axis=1,inplace=True)
df1

,CryoSleep,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck
0,1.0,27.000000,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,19.000000,0.0,0.0,9.0,0.0,2823.0,0.0
2,1.0,31.000000,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,38.000000,0.0,0.0,6652.0,0.0,181.0,585.0
4,0.0,20.000000,0.0,10.0,0.0,635.0,0.0,0.0
...,...,...,...,...,...,...,...,...
4272,1.0,34.000000,0.0,0.0,0.0,0.0,0.0,0.0
4273,0.0,42.000000,0.0,0.0,847.0,17.0,10.0,144.0
4274,1.0,28.658146,0.0,0.0,0.0,0.0,0.0,0.0
4275,0.0,28.658146,0.0,0.0,2680.0,0.0,0.0,523.0
4276,1.0,43.000000,0.0,0.0,0.0,0.0,0.0,0.0

In [28]:
df1.isnull().sum()

CryoSleep       0
Age             0
VIP             0
RoomService     0
FoodCourt       0
ShoppingMall    0
Spa             0
VRDeck          0
dtype: int64

In [29]:
al=model.predict(df1)
aal=pd.DataFrame(al)

In [30]:
aal

      0
0     1
1     0
2     1
3     1
4     1
...  ..
4272  1
4273  1
4274  1
4275  1
4276  1

[4277 rows x 1 columns]

In [31]:
af=pd.DataFrame({'PassengerId':passid,'Transported':al.astype('bool')})

In [32]:
af.to_csv('output.csv',index=False)