In [1]:
import os
import sys
import warnings

if not sys.warnoptions:
    warnings.simplefilter("ignore")

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.ensemble import AdaBoostClassifier, RandomForestClassifier

In [2]:
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

/kaggle/input/titanic/train.csv
/kaggle/input/titanic/test.csv
/kaggle/input/titanic/gender_submission.csv

In [3]:
Train_df = pd.read_csv('/kaggle/input/titanic/train.csv')
Test_df = pd.read_csv('/kaggle/input/titanic/test.csv')
gender_df = pd.read_csv('/kaggle/input/titanic/gender_submission.csv')

In [4]:
Train_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [5]:
Test_df.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [6]:
gender_df

     PassengerId  Survived
0            892         0
1            893         1
2            894         0
3            895         0
4            896         1
..           ...       ...
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]

In [7]:
# Select the parameters that will only get in the way
not_need_columns = [
    'PassengerId', 'Name', 'Cabin'
]

In [8]:
train_df = Train_df.drop(axis=1, columns=not_need_columns)
test_df = Test_df.drop(axis=1, columns=not_need_columns)

In [9]:
train_df.head()

,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,0,3,male,22.0,1,0,A/5 21171,7.2500,S
1,1,1,female,38.0,1,0,PC 17599,71.2833,C
2,1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,1,1,female,35.0,1,0,113803,53.1000,S
4,0,3,male,35.0,0,0,373450,8.0500,S

In [10]:
test_df.head()

   Pclass     Sex   Age  SibSp  Parch   Ticket     Fare Embarked
0       3    male  34.5      0      0   330911   7.8292        Q
1       3  female  47.0      1      0   363272   7.0000        S
2       2    male  62.0      0      0   240276   9.6875        Q
3       3    male  27.0      0      0   315154   8.6625        S
4       3  female  22.0      1      1  3101298  12.2875        S

In [11]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  891 non-null    int64
 1   Pclass    891 non-null    int64
 2   Sex       891 non-null    object
 3   Age       714 non-null    float64
 4   SibSp     891 non-null    int64
 5   Parch     891 non-null    int64
 6   Ticket    891 non-null    object
 7   Fare      891 non-null    float64
 8   Embarked  889 non-null    object
dtypes: float64(2), int64(4), object(3)
memory usage: 62.8+ KB

In [12]:
# Changing the categorical features into numerical features
le = LabelEncoder()

train_df['Sex'] = le.fit_transform(train_df['Sex'])
train_df['Embarked'] = le.fit_transform(train_df['Embarked'])
train_df['Age'] = train_df['Age'].fillna(value=train_df['Age'].mean())

test_df['Sex'] = le.fit_transform(test_df['Sex'])
test_df['Embarked'] = le.fit_transform(test_df['Embarked'])
test_df['Age'] = test_df['Age'].fillna(value=test_df['Age'].mean())

In [13]:
tickets = train_df['Ticket'].str.split()
tickets = [ticket[-1] if len(ticket) > 1 else ticket[0] for ticket in tickets]
tickets = [int(elem) if elem.isdigit() else 9999999 for elem in tickets]

In [14]:
train_df['Ticket'] = tickets

In [15]:
tickets = test_df['Ticket'].str.split()
tickets = [ticket[-1] if len(ticket) > 1 else ticket[0] for ticket in tickets]
tickets = [int(elem) if elem.isdigit() else 9999999 for elem in tickets]
test_df['Ticket'] = tickets

In [16]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  891 non-null    int64
 1   Pclass    891 non-null    int64
 2   Sex       891 non-null    int64
 3   Age       891 non-null    float64
 4   SibSp     891 non-null    int64
 5   Parch     891 non-null    int64
 6   Ticket    891 non-null    int64
 7   Fare      891 non-null    float64
 8   Embarked  891 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 62.8 KB

In [17]:
test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Pclass    418 non-null    int64
 1   Sex       418 non-null    int64
 2   Age       418 non-null    float64
 3   SibSp     418 non-null    int64
 4   Parch     418 non-null    int64
 5   Ticket    418 non-null    int64
 6   Fare      417 non-null    float64
 7   Embarked  418 non-null    int64
dtypes: float64(2), int64(6)
memory usage: 26.2 KB

In [18]:
test_df['Fare'] = test_df['Fare'].fillna(value=test_df['Fare'].mean())

In [19]:
test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Pclass    418 non-null    int64
 1   Sex       418 non-null    int64
 2   Age       418 non-null    float64
 3   SibSp     418 non-null    int64
 4   Parch     418 non-null    int64
 5   Ticket    418 non-null    int64
 6   Fare      418 non-null    float64
 7   Embarked  418 non-null    int64
dtypes: float64(2), int64(6)
memory usage: 26.2 KB

In [20]:
Y_train = train_df.loc[:, ['Survived']]
X_train = train_df.drop(axis=1, columns=['Survived'])

In [21]:
x_train, x_test, y_train, y_test = train_test_split(X_train, Y_train,
                                                    random_state=42)

In [22]:
adc = AdaBoostClassifier()
adc.fit(x_train, y_train)
Y_pred = adc.predict(x_test)
accuracy_score(Y_pred, y_test)

0.7892376681614349

In [23]:
rfc = RandomForestClassifier()
rfc.fit(x_train, y_train)
Y_pred = rfc.predict(x_test)
accuracy_score(Y_pred, y_test)

0.8116591928251121

In [24]:
tree = DecisionTreeClassifier()
tree.fit(x_train, y_train)
Y_pred = tree.predict(x_test)
accuracy_score(Y_pred, y_test)

0.7937219730941704

In [25]:
rfc = RandomForestClassifier(n_estimators=25, max_depth=7, random_state=42)
rfc.fit(X_train, Y_train)
Y_pred = rfc.predict(test_df)

In [26]:
accuracy_score(Y_pred, gender_df.loc[:, ['Survived']])

0.8755980861244019

In [27]:
submission = pd.DataFrame({
        "PassengerId": Test_df["PassengerId"],
        "Survived": Y_pred
    })

In [28]:
submission.to_csv('submission.csv', index=False)

In [29]:
pd.read_csv('submission.csv')

     PassengerId  Survived
0            892         0
1            893         0
2            894         0
3            895         0
4            896         1
..           ...       ...
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]

# Thanks for reading. Don't forget to upvote the work. Good luck kaggling!